0~Having learnt by revelation, of the captivity in Babylon in store for the Jews on account of their sins, the prophet prays for his unfortunate countrymen; then he announces their deliverance by Cyrus, king of Persia. According to St. Jerome, Theodoret, Theophylact, Rupert, Euthymius, Jansenius of Ghent, Cornelius a Lapide, and most of the other commentators, we have here a manifest figure of the divine work wrought by Jesus Christ to deliver mankind from the slavery of the devil.
1~“<l>Auditionem tuam.</s>” That is: All that Thou hast revealed to me.
2~"Vivifica.</s>” According to Du Hamel: <l>Perfice</s>—Perfect. Lallemant gives this explanation: Complete Thy work, the deliverance of the Jews from the captivity of Babylon, and in mercy shorten the time of our chastisement. But this passage is better understood in the figurative sense, thus: Bring to perfection the work of man’s redemption by means of the Messias: Grant that it may have its full force and effect within the space of years which Thou hast determined.
3~In the midst of those years appointed; that is, anticipating the time fixed, Thou wilt make manifest the work of the deliverance of the Jews from the captivity of Babylon. (This is in the literal sense; but in the mystical sense is signified the redemption of mankind.) And though angry at the sons of men, yet Thou wilt be mindful of Thy mercy, and wilt not withhold it from us: <l>Licet peccatis hominum iratus,</s> says Du Hamel, 
<l>misericordiam tuam non subtrahes.</s>
4~God will come from the South to deliver his people, as the Holy One of Israel came of old on Sinai, appearing from Mount Pharan (Deut. 33:2). So too, from Persia and Media, lying to the South, came Cyrus and Darius to deliver the Jews from Babylon. In the figurative sense this verse, as understood by St. Jerome, Theodoret, Theophylact, and others cited by Tirinus, this verse applies to the Messias who was to be born at Bethlehem situated to the south of Jerusalem. “<l>Sanctus de monte Pharan.</s>” Tirinus says that hereby is meant the Holy Ghost, who descended on Mount Pharan and communicated the spirit of prophecy to the seventy judges of the people (Num. 11:25).
5~His glory overspread the heavens, causing their brightness to pale, and the whole earth was filled with their praises. In a figurative sense this signifies: The Messias who is to come will fill heaven with glory, and the angels will praise him on earth. It is thus that they chanted at his birth: <l>Gloria in altissimis Deo</s>—Glory to God in the highest (Luke, 2:14).
6~He shall appear resplendent with light as the sun, and his hands shall be armed with power. “<l>Splendor ejus ut lux erit.</s>” This may mean, in the literal sense, that at the coming of Cyrus the light of liberty will shine forth for the Jews; and in the figurative sense that at the coming of the Messias, of whom Cyrus was a figure, the true light shall shine forth on the world, according to what is said in the Gospel: <l>Erat Lux vera, quæ illuminat omnem hominem</s>—That was the true light which enlighteneth every man (John, 1:9). “<l>Cornua in manibus ejus.</s>” <l>Cornu</s> and <l>Cornua</s> in Scripture mean strength. Tirinus and Du Hamel, with St. Cyprian and St. Augustine, thus apply this passage to Jesus Christ: All his strength to conquer the devil and the world shall be in his hands pierced upon the cross. St. Augustine says: <l>Quid fortius manu hac, quæ mundum vicit, non ferro armata, sed transfixa?</s>—What is there stronger than that hand which conquered the world, not armed, but transfixed with iron? (In Ps. xxxiv. s. 1, n. 1.)
7~In the figurative sense: There (that is, in his pierced hands) is hidden his power; so that before his power, death will fly, conquered by his death: <l>Absorpta est mors in victoria</s>—Death is swallowed up in victory (1 Cor. 15:54).
8~At the entrance of the people into the Land of Promise the Lord was preceded by the devil, the executor of his vengeance; whereupon the enemies being vanquished, he distributed their lands to his people. “<l>Egredietur diabolus ante pedes ejus.</s>” This is explained figuratively: The devil shall be utterly vanquished, and shall go forth with shame, to be led in triumph before the feet of Jesus Christ, his conqueror, who will despoil him of his power, according to the words of St. Paul: <l>Exspolians principatus et potestates, traduxit confidenter, palam triumphans illos in semetipso</s>—Despoiling the principalities and powers, he hath exposed them confidently in open show, triumphing over them in himself (Col. 2:15). “<l>Stetit, et mensus est terram.</s>” Then Jesus as conqueror seated at the right hand of his Father, as Du Hamel says, and looking over the earth, divided it among his Apostles, that they might fill it with the light of the Gospel: <l>Qui, sedens ad dexteram Patris, terram Apostolis suis divisit, ut Evangelii luce eam complerent.</s>
9~With his looks he broke asunder the nations; and the great ones of the world, who seemed like mountains, were brought to naught. In the figurative sense: He looked upon the earth and the nations, and, giving them the light of faith, he set them free from the yoke of Satan; and as for the princes of the world, who as mountains were lifted up, they were brought low and shattered at the coming of Jesus Christ.
10~These proud hills of the world have been laid low beneath the feet of the Eternal. In the figurative sense: These princes of the world shall bow down before the Redeemer, bending the knee to adore him, as they consider that on him depends the course of eternal ages. “<l>Ab itineribus æternitatis ejus.</s>” According to the Hebrew: <l>Itinera sæculi æterni ejus sunt</s>—His are the journeys of the eternal age.
11~I saw the tents of the Ethiopians cast down for their wickedness, and the tabernacles of the Madianites thrown to the earth. In the mystical sense: As the hosts of the Ethiopians and of the Madianites were seen destroyed on account of their wicked doings against God’s people, so shall those that oppose the Gospel be likewise punished.
13~Thou didst save Thy people, and didst deliver them from the Egyptians, mounting upon the clouds as on horses which draw the chariot.
14~Thou wilt resume Thy bow, that is, the bow of Thy power, and wilt fulfil the promises that Thou hast sworn to the tribes of Israel. Thus Tirinus, Du Hamel, and Rotigni explain it.
15~Thou didst cut in twain the course of the Jordan, that Thy people might pass over. Its waters saw Thee, that is, understood Thy command, and raising themselves like mountains, remained suspended in the air, as if grieving to see themselves stopped in their course; and thus Thy people crossed over the river.
16~The waters flowed back with noise, and in lifting themselves on high they seemed to raise up their hands to implore Thy permission to return again to their course.
17~At Josue’s voice, in the battle with the Amorrhites, Thou didst cause the sun and the moon to stand still in their course (Jos. 10:13); and didst make his army march by the glare of Thy lightnings, and by the glitterings of Thy spear from which thunderbolts flashed.
18~Thou didst tread underfoot, that is, Thou didst go through the earth with the roar of thunderings and of lightnings; and the hostile nations were astonished and in dismay at Thy wrath.
19~“<l>Cum Christo tuo.</s>” Such was Cyrus who came to set free the people from captivity, as Isaias had foretold: <l>Hæc dicit Dominus Christo meo Cyro, cujus apprehendi dexteram, ut subjiciam ante faciem ejus gentes</s>—Thus said the Lord to my anointed Cyrus, whose right hand I have taken hold of to subdue nations before his face (Is. 45:1). Now, Cyrus was a type of Jesus Christ, who has saved us by his merits, as remark St. Jerome, St. Augustine (De Civ. D. 1. 18, c. 32), and others. The verse is translated thus according to the sixth Greek version: <l>Egressus es ut salvares populum per Jesum Christum tuum.</s>
20~“<l>Percussisti caput de domo impii.</s>” Thou hast struck the head of the house of the impious one, that is, king Balthassar, the head of the Chaldeans, and Thou hast utterly ruined him (Dan. 5). In the mystical sense: Thou hast laid prostrate the devil, the head of impiety. “<l>Denudasti fundamentum ejus usque ad collum.</s>” Tirinus thus interprets this: <l>Denudatum evertisti ab imo sursum.</s> Thou hast despoiled him of his empire, and hast upset him from top to bottom, that is, Thou hast taken from him all his tyrannical power. It is thus, O Lord! that Thou hast willed to save Thy people by means of Jesus Christ.
21~Thou hast cursed his empire, that, namely, of king Balthassar, along with the head of his soldiers, who are come as a whirlwind to destroy Thy people. This is understood mystically of the curse pronounced on the devil, who held sway over the human race, and on his associates, who all contrived our ruin.
22~“<l>Qui devorat pauperem in abscondito.</s>” Who robs and kills a poor man in a secret place where no one can come to his help.
23~Thou didst open a passage in the Red Sea, making the horses of Thy people pass upon its muddy bed in the midst of the piled-up masses of waters. Tirinus observes that here the canticle ends, and that the prophet adds what follows.
24~The prophet, knowing by revelation what God’s people would have to suffer before their deliverance, says: I heard this prediction and my heart was troubled; at what was told me my lips quivered, so that I was unable to utter a word.
26~So that I may find myself at rest in the tomb on the day of so great a tribulation, and thus be united with our people who have already fought the fight against the enemy. But we read in the old Vulgate: <l>Ad populum peregrinationis meæ.</s> That is: To the people who regard this life as a pilgrimage, as I myself regard it.
27~In the mystical sense, this is what it may mean: In the desolation to which the Jews shall be brought in punishment for having put their Saviour to death, they will cease to produce any fruit of good works, having lost the kingdom of God, which shall be given to the Christian people who will bring forth fruits of holiness, according to the words of Jesus Christ: <l>Ideo dico vobis, quia auferetur a vobis regnum Dei, et dabitur 
genti facienti fructus ejus</s>—Therefore I say to you, that the kingdom of God shall be taken from you, and shall be given to a nation yielding the fruits thereof (Matt. 21:43).
28~“<l>Mentietur opus olivæ.</s>” The olive crop shall lie; that is, shall disappoint expectation.
29~St. Augustine (De Civ. D. l. 18, c. 32) applies this passage to the Jews, who after having put Jesus Christ to death, were to remain without pastors, without Temple, and without spiritual food.
30~“<l>In Deo, Jesu meo.</s>” In the Hebrew, according to Pagnini, Vatablus, and others, we have: <l>In Deo, salute mea.</s> But some, says Tirinus, interpret the Hebrew in the sense of the Septuagint, which agrees with the Chaldee and Syriac, namely: <l>In Deo, Jesu,</s> or <l>Salvatore,</s> or <l>Redemptore meo.</s> Thus St. Augustine and others understand it.
31~That is understood of the return of the Jews from the captivity of Babylon. In the mystical sense it is applied to the Gentiles hastening to come to God when set free by Jesus Christ from the bondage of Satan.
32~The vanquisher of enemies will lead me up to Mount Sion, there to sing his glories. In the spiritual sense, according to St. Jerome: He will bring me to heaven, there to glorify him with hymns of praise and thanksgiving.
