0~The Most Blessed Virgin extols in this canticle the goodness of God for having chosen her to be his Mother, and for having redeemed the world by means of Jesus Christ. This canticle may be divided into three parts. In the first, the Blessed Virgin thanks the Lord for the favors that have been conferred upon her. In the second, she praises him for the benefits granted to the Hebrew people. In the third, she glorifies him for the grace that he has bestowed upon all men in giving them Jesus Christ for their Saviour.
1~“<l>Magnificat.</s>” That is, according to the Greek text: It extols the greatness of.
2~“<l>Salutari.</s>” According to the Hebrew and the Greek: <l>Jesu,</s> or <l>Salvatore.</s> The Blessed Virgin found all her delight in rejoicing in her God; and such also should be ours.
3~“<l>Humilitatem.</s>” According to the Greek: <l>Vilitatem, Abjectionem</s>—Meanness, Littleness, Lowliness. The most humble Mary could not mean by this word the virtue of humility, for if so she would be praising herself; whereas humility, says Euthymius, alone amongst the virtues does not know itself: <l>Sola inter virtutes humilitas seipsam ignorat.</s> “<l>Ecce enim ...</s>” For behold from this time forth all nations and all ages shall call me BLESSED. This prophecy has been perfectly verified; for there is not one among Catholics that does not in a special manner venerate this great Mother of God.
4~Because the Almighty, whose name is holy, has wrought great and marvellous things in me, making me Virgin and Mother of my Creator.
5~“<l>Timentibus eum.</s>” Extends itself to all those that fear him with a filial fear.
6~God has shown forth his power by putting to rout the proud, that is, the haughty princes of the earth (we may also here understand the rebel angels), and he has defeated all their wicked designs whereby they sought to oppress the innocent.
7~“<l>Potentes.</s>” These proud princes.
9,10~He has taken under his protection Israel, his servant, that is, his chosen people, being mindful of the promise which, in his mercy, he had made to him, to send the Messias to redeem him, as he promised to our fathers, especially to Abraham, and to all his descendants.
