<?php
function hymn2($file, $option=0) {
	$dir = "/wamp/www/b/content/00/Hymn/";
echo '<text:p text:style-name="Head2">Hymn</text:p>';
	require $dir.'0Hymn.php';
echo '<text:p text:style-name="BodySm"/>';
}

$_GET['O'] = 1;
echo '<text:p text:style-name="P181"/>';
hymn2('ad_regias_agni_dapes.php');
hymn2('aeterna_caeli_gloria.php');
hymn2('aeterne_rerum_conditor.php');
hymn2('ales_diei_nutius.php');
hymn2('alto_ex_olympi_vertice.php');
hymn2('audi_benigne_conditor.php');
hymn2('aurora_caelum_purpurat.php');
hymn2('aurora_jam_spargit_polum.php');
hymn2('ave_maris_stella.php');
hymn2('a_solis_ortus_cardine.php');
hymn2('beata_nobis_gaudia.php');
hymn2('caelestis_urbs_jerusalem.php');
hymn2('caeli_deus_sanctissime.php');
hymn2('cor_arca_legem_continens.php');
hymn2('creator_alme_siderum.php');
hymn2('crudelis_herodes_deum.php');
hymn2('deus_tuorum_militum.php');
hymn2('domare_cordis_impetus_elisabeth.php');
hymn2('ecce_jam_noctis_tenuatur_umbra.php');
hymn2('egregie_doctor_paule_mores_instrue.php');
hymn2('en_clara_vox_redarguit.php');
hymn2('en_ut_superba_criminum.php');
hymn2('exsultet_orbis_gaudiis.php');
hymn2('fortem_virili_pectore.php');
hymn2('hominis_superne_conditor.php');
hymn2('immense_caeli_conditor.php');
hymn2('invicte_martyr_unicum.php');
hymn2('iste_confessor_domini_colentes.php');
hymn2('jam_lucis_orto_sidere.php');
hymn2('jam_sol_recedit_igneus.php');
hymn2('jesu_corona_celsior.php');
hymn2('jesu_corona_virginum.php');
hymn2('jesu_decus_angelicum.php');
hymn2('jesu_dulcis_memoria.php');
hymn2('jesu_redemptor_omnium_perpes.php');
hymn2('jesu_redemptor_omnium_quem.php');
hymn2('lucis_creator_optime.php');
hymn2('lustra_sex_qui_jam_peregit.php');
hymn2('lux_ecce_surgit_aurea.php');
hymn2('lux_o_decora_patriae.php');
hymn2('magnae_deus_potentiae.php');
hymn2('nox_et_tenebrae_et_nubila.php');
hymn2('nunc_sancte_nobis_spiritus.php');
hymn2('opes_decusque_regium_reliqueras.php');
hymn2('o_gente_felix_hospita.php');
hymn2('o_gloriosa_virginum.php');
hymn2('o_lux_beata_caelitum.php');
hymn2('o_sola_magnarum_urbium.php');
hymn2('o_sol_salutis_intimis.php');
hymn2('pange_lingua_gloriosi.php');
hymn2('paschale_mundo_gaudium.php');
hymn2('rector_potens_verax_deus.php');
hymn2('rerum_deus_tenax_vigor.php');
hymn2('rex_gloriose_martyrum.php');
hymn2('salutis_humanae_sator.php');
hymn2('salvete_flores_martyrum.php');
hymn2('sanctorum_meritis_inclyta_gaudia.php');
hymn2('sedibus_caeli_nitidis_receptos.php');
hymn2('splendor_paternae_gloriae.php');
hymn2('telluris_alme_conditor.php');
hymn2('te_lucis_ante_terminum.php');
hymn2('tristes_erant_apostoli.php');
hymn2('tu_natale_solum_protege_tu_bonae.php');
hymn2('tu_trinitatis_unitas.php');
hymn2('veni_creator_spiritus.php');
hymn2('verbum_supernum_prodiens.php');
hymn2('vexilla_regis_prodeunt.php');
?>
