0~According to interpreters this psalm was composed by David, happy to see himself delivered from the hands of Saul, or of Absalom. In a mystical sense it is applied to Jesus Christ inasmuch as he is the end of the law and of the prophets.
1~When I called upon my God, he heard me, he who is the defender of my innocence: Yea, Lord, when I was in tribulation, Thou didst enlarge my heart by Thy consolations.
2~Continue, then, to have pity on me, and hearken to my prayers whenever I have recourse to Thee.
3~“<l>Usquequo gravi corde?</s>” How long do you wish to have your heart thus heavy, that is, so bowed down to earth, and inclined to earthly passions? “<l>Vanitatem ... mendacium</s>” Vain and deceitful things, false goods.
4~Know that the Lord has made his holy one admirable, that is, me his servant, whom he has sanctified as King and Prophet; he will, therefore, continue to hearken to me whenever I shall have recourse to him in prayer.
5~If you become angry, take care not to commit sin, that is, be angry with a just anger, when the honor of God or your own duty require you to do so, and then do not be disturbed. St. Paul says: <l>Irascimini, et nolite peccare; sol non occidat super iracundiam vestram</s>—Be angry, and sin not. Let not the sun go down upon your anger (Eph. 4:26). And if your conscience reproaches you for having yielded to some fit of passion, then retire to your chambers at night, and ask God’s pardon with compunction. “<l>Compungimini.</s>” According to the Chaldee: <l>Deum apud vos cogitate</s>—Think with yourselves on God.
6~Offer to God the sacrifice of justice, that is, of a just life, and put all your trust in the Lord. “<l>Quis ostendit nobis bona?</s>” Interpreters refer these words to the followers of David, who, seeing themselves persecuted with him, said: When shall we recover peace? According to Bellarmine, we can explain them in two ways either by supposing them as coming from the mouth of worldlings, who make but little account of heavenly goods, and say: Who has ever come back from the other world to tell us of these goods, which we do not see? Or else: What is this holiness, this justice, which you so much recommend to us? who will show us the way to acquire them?
7~“<l>Signatum est.</s>” According to the Hebrew: <l>Eleva</s>—Lift up; or: <l>Elevatum est ut signum</s>—Is lifted up as a sign; which comes to the same thing. The sense, then, of the verse is: Thou hast shown us the light of Thy face, that is, Thy goodness, and thereby Thou hast rejoiced my heart.
8~That is: I behold my enemies multiplying with the good things that they enjoy.
9~But for me, confiding in Thy goodness, I shall continue to sleep and to repose in peace.
10~“<l>Singulariter.</s>” In a singular manner. According to the Greek: <l>Solitarie.</s> That is as much as to say: Thou takest care of me as if Thou hast none else than me to look after.
