0~Addressing himself to God, David represents to him his innocence and at the same time the anguish of his heart; this was at the time of the persecution that he had to endure from Saul or from Absalom—more probably from Saul. The holy king exhorts at the same time his enemies to be converted, and predicts to them the chastisement of heaven if they are not converted.
2~“<l>Animam meam.</s>” My soul, or my life.
3~“<l>Si feci istud.</s>” If I have done the wrong that is laid to my charge. This may mean that the enemies of David accused him of having wished to usurp the throne of Saul.
5~“<l>Conculcet in terra vitam meam.</s>” May he trample with his feet the earth stained with my blood in the place where he will take away my life.
6~This verse means: But if I am innocent, O Lord! show forth Thy just anger by punishing my enemies as they deserve. We should not here reproach David with having asked to be revenged upon his enemies; for we must understand him either as speaking in a prophetic manner, announcing the chastisements with which God would punish them, or as praying to God to send them temporal punishment that they may amend themselves.
7~“<l>In præcepto quod mandasti.</s>” That is to say: My God, arise in order to save innocence, according to the precept that Thou hast given to men to defend the innocent. “<l>Synagoga populorum.</s>” According to the Hebrew, <l>Congregatio tribuum:</s> The congregation of the tribes. That is to say: And then all the people shall gather around Thee, to praise the justice of Thy judgments.
8~“<l>Dominus judicat populos.</s>” It belongs to Thee, as the Lord of the universe, to judge the people.
10~The astuteness of sinners shall not avail them; for Thou who art God, and who knowest the secrets of their hearts, well knowest how to direct the just man, so that he may escape their snares. 
11~The Lord will not fail to give me his just help; for he saves those that act with an upright heart.
12~“<l>Justus, fortis, et patiens; numquid irascitur per singulos dies?</s>” It must be here observed that the Hebrew presents another sense, namely, <l>Justus et fortis, et comminans (irascens) tota die.</s> Hence, according to the present Hebrew text, we read that God threatens or is angry every day; in the Vulgate, on the contrary, it is said that God does not threaten and is not angry everyday. The version of the Septuagint agrees with the Vulgate, and with Bellarmine I prefer to adhere to it for the reason already given, namely, that it is believed that the Hebrew text of the time of the Septuagint was more correct than that which we now have; the more so since, as Bellarmine remarks, the sense as given in the Vulgate agrees better with the following verse.
13~This verse, united with the preceding one, signifies that God is not always angry and in the mind of punishing sinners as they deserve; but when they are obstinate and will not be converted, he will draw his sword and will punish them according to his justice; for this reason he always holds in readiness and has bent his bow to let fly the arrow of his just vengeance.
14~“<l>Vasa mortis.</s>” That is to say: The weapons that bring death. “<l>Sagittas suas ardentibus effecit.</s>” By this is meant thunderbolts; such is precisely the explanation given by St. Jerome: <l>Sagittas suas ad comburendum ignitas ejfecit:</s> He hath set his arrows on fire to burn.
15~“<l>Concepit dolorem, et peperit iniquitatem.</s>” The sinner first conceives grief in his heart, that is, hatred against the just man, called grief, because it afflicts the soul of him who cherishes it; then he gives birth to iniquity by seeking to oppress the person whom he hates (Job 15:35; Is. 59:4).
16~He has opened and dug a precipice, or a covered trap; but God has permitted that he should himself fall into it.
17~The evil that he wished to cause others shall descend upon himself.
18~Conclusion: As for myself, I will praise the justice of the Lord.
