0~The subject of this psalm, as St. Peter testifies (Acts 2:25), is a prayer addressed to God by our Lord Jesus Christ during the three days that his holy body was lying in the sepulchre. Resting on the authority of the prince of the apostles, Xavier Mattei and Father Rotigni rightly think that the literal sense and the spiritual sense are one and the same, and that thus the whole psalm directly refers to Jesus Christ raising his voice to his heavenly Father to address to him from the depth of the sepulchre the following prayer.
1~“<l>Bonorum meorum non eges.</s>” That is to say, that God is the sovereign master of all things.
2~According to interpreters, Jesus Christ, who is here speaking, says: God, my Father, wishes that my will should tend in a marvellous manner to benefit the saints that live on earth.
3~Jesus Christ continues to speak: Their former infirmities (that is their sins) were numerous; but afterwards healed by my merits, they became holy so that they were able to hasten to God.
4~“<l>Non congregabo conventicula eorum de sanguinibus.</s>” St. Jerome translates this after this manner: <l>Non libabo libamina eorum de sanguine</s>—Their libations of blood I will not offer. That is to say: I will never approve of the assemblies that they before held in the state of their infirmity, to celebrate sacrifices of blood.
5~“<l>Pars ... calicis mei.</s>” In olden times those that presided at a banquet assigned to each guest the portion of wine that was due to him. “<l>Restitues hereditatem meam mihi.</s>” Jesus Christ says these words to God his Father, when speaking of his resurrection.
6~It must here be observed that in ancient times the fields were measured with cords, and the part that fell to the lot of each in an inheritance.
7~I will bless the Lord, who has given me the understanding to choose himself for my inheritance; and all the affections of my heart (<l>renes mei</s>) have excited me to suffer for him with patience all tribulations, even death itself (<l>usque ad noctem</s>).
8~“<l>Ne commovear.</s>” That I may not be shaken in my desire and in the hope that I have placed in him.
9~“<l>Caro mea requiescet in spe.</s>” My body, separated from my soul, shall rest in hope of the resurrection and of the glory that the Lord has prepared for me.
10~Thou, O Lord! wilt not allow my soul to remain long in limbo, nor wilt Thou suffer my body, which is holy, to undergo corruption in the tomb.
11~“<l>Vias vitæ.</s>” The ways of life, that is to say, of resurrection, which I know is soon to restore life to my body. “<l>Delectationes in dextera tua usque in finem.</s>” Thou wilt make me enjoy Thy glory, by placing me at Thy right hand for all eternity.
