0~The just man prays to God to be delivered from the persecutions to which he sees himself exposed.
1~Show favor to my innocence by hearing me; lend me a gracious ear.
2~Hear my petitions that I lay before Thee, not in words of falsehood, but of sincerity.
3~I beseech Thee that the judgment of my cause may proceed from Thy mouth, and from no other; regard justice, and judge me according to its laws.
4~“<l>Nocte.</s>” During the darkness of my desolation. “<l>Igne.</s>” By the penetrating fire of tribulation.
5~In order to avoid speaking against my persecutors, I have been attentive to the words of Thee, who commandest me to be silent, and thereby have walked in hard and very toilsome ways. I have had much to suffer.
6~Continue to direct me in Thy ways in which Thou wishest that I should walk, so that I may not go astray.
7~I have invoked Thee, and Thou hast heard me; cease not to incline Thy ear towards me by hearing all the prayers that I shall address to Thee.
9~“<l>Dextera tuæ.</s>” From those that resist Thy right hand, which defends me. “<l>Ut pupillam oculi.</s>” With great care.
10~Hide me from the eyes of the wicked who seek to oppress me.
11~“<l>Animam meam circumdederunt.</s>” They have surrounded me to take away my life. “<l>Adipem suum concluserunt.</s>” St. Jerome translates: <l>Adipe suo concluserunt; Viscera</s> being understood. That is to say, as in the human body fat closes the bowels, so the abundance of riches fills the wicked with pride, and shuts in them the bowels of compassion for others.
12~“<l>Oculos suos statuerunt declinare in terram.</s>” Miserable men! they are determined not to lift their eyes from the ground to which they keep their hearts attached.
13~“<l>In abditis.</s>” In secret places to devour those passing by. Father Rotigni observes that this verse is applied to Jesus Christ more easily than to David, who was never taken by his enemies.
14~“<l>Animam meam.</s>” My life. “<l>Frameam tuam ab inimicis manus tuæ.</s>” Take away Thy sword, that is to say, the power to harm, which comes from Thee, from the enemies, that is to say, from those that abuse the gifts of Thy hand.
15~“<l>A paucis de terra divide eos in vita eorum.</s>” This is a passage which some, such as Bellarmine, Gordona, and Lallemant, explain thus: Separate the multitude of the wicked from the small number of Thy servants who live upon earth. Others, as Bossuet, Tirinus, and Mattei, expound it as follows: Separate, that is to say, detach the wicked during life from that little portion of earthly goods which they possess and which renders them so proud. This last interpretation seems to me to be more probable; for St. Jerome translates the Hebrew: <l>Quoniam pars in vita</s>—Whose portion is in their life; the meaning of this is, that they found on such things their present happiness; so that St. Jerome, or according to the Hebrew text the expression <l>A paucis,</s> has reference, not to the number of the just, but to the goods that the wicked enjoy in this life. In any case this passage is very obscure. “<l>De absconditis tuis adimpletus est venter eorum.</s>” They have their belly or their heart filled with their earthly goods, which they keep hidden, or which they carefully preserve; but in reality all these goods are Thine. This is the explanation also given of these obscure words: <l>De absconditis tuis.</s>
16~“<l>Parvulis.</s>” Bossuet understands by this word grand children, descendants, <l>Nepotibus.</s>
17~I hope to appear just in Thy eyes on the day when I am judged, that I may be admitted into heaven, where I shall be satiated by beholding Thy glory.
