0~In this psalm we hear exalted the perfections of God, the sanctity of his law, and the magnificence of his works. In the spiritual sense it is to Jesus Christ and his Apostles that all these praises apply, according to St. Augustine, Bellarmine, Rotigni, Malvenda, Tirinus, and Gordona.
1~The heavens, by the prodigious works that we admire therein, make us know God. By the heavens the above-mentioned interpreters understand the Apostles, who by the preaching of the Gospel and by miracles have propagated upon earth the faith in Jesus Christ.
2~Each day produces or communicates for the day following and night the succeeding night, the manner of praising God; so that the heavens are unceasingly publishing the glory of the Most High.
3,4~This accords with the command that our Lord gave to his Apostles: <l>Euntes ergo docete omnes gentes</s>—Going, therefore, teach ye all nations (Matt. 28:19). And St. Paul, speaking of the preaching of the New Law by the ministry of the Apostles, says: <l>Numquid non audierunt? Et quidem in omnem terram exivit sonus eorum, et in fines orbis terræ verba eorum</s>—Have they not heard? Yea, verily: their sound hath gone forth into all the earth, and their words unto the ends of the whole world (Rom. 10:18).
5~“<l>In sole posuit tabernaculum suum.</s>” The Lord has placed his pavilion in the sun, as being the principal part of the heavens. This explanation which Bellarmine gives does not please Mattei; he prefers the sense of the Hebrew text, namely: <l>Soli posuit tentorium in eis</s>—He has set in them a pavilion for the sun. But Bellarmine observes that the version of the Septuagint, which the Vulgate has followed, says, as above, that God has set his pavilion in the sun; now we should here prefer the interpretation of the Septuagint, because we may reasonably believe that at that time the Hebrew text was more correct than it is at the present day.
8~The law of the Lord is beautiful, without a defect, so that it converts souls or withdraws them from evil and from error. It is his testimony, that is to say, it makes us know his will; it is faithful in its promises, and it renders wise the little ones, that is to say, those that are docile and those that willingly submit to his precepts.
9~“<l>Justitiæ Domini.</s>” The commandments of God. “<l>Illuminans oculos.</s>” This law is full of a heavenly light, which enlightens the mind: the mind is the eye of the soul.
10~“<l>Timor Domini sanctus, permanens in sæculum sæculi.</s>” The divine law, which teaches holy fear, is permanent as to the eternal reward that it promises to him who observes it. “<l>Judicia.</s>” The precepts.
11~The divine precepts are more agreeable to virtuous souls than anything in this world.
13~“<l>Delicta quis intellegit?</s>” What man is there that knows all the sins, or, according to the translation of St. Jerome, all the errors into which we are exposed to fall, so as to be able to avoid them? “<l>Ab alienis parce servo tuo.</s>” Do not permit Thy servant to associate with those that have strange, that is, bad manners. St. Jerome translates: <l>A superbis quoque libera servum tuum</s>—From the proud deliver Thy servant.
14~If I do not let my sins get the mastery over me, then I shall be free from every fault, and pure especially from grievous sins.
15~My word, or my prayers will be agreeable to Thee as well as my meditations, which I shall ever make in Thy presence.
16~It is Thou that aidest me in need and deliverest me in danger.
