0~This psalm is to be understood in the literal sense of Jesus Christ, and especially of the prayer which he said before his death from the height of the cross, as also of his glorious resurrection. According to Cardinal Bellarmine, it would be an act of temerity to seek to turn it to any other sense. We have then in this psalm an express prophecy of all that which our Lord suffered when dying on the cross.
1~My God, look upon the affliction in which I am; why hast Thou abandoned me? I see well that my sins, that is, the sins of my people, which I have taken upon myself to expiate, as if they were my own. Keep me far from my salvation, that is, make it impossible for me not to die. We make here the following observation on the abandonment of Jesus Christ: It is certain that the divine Word did not abandon the humanity of Jesus Christ when he was dying upon the cross. But why did our Saviour say: <l>Deus meus, Deus meus, ut quid dereliquisti me?</s>—My God, my God, why hast Thou forsaken me? (Matt. 27:46.) St. Leo answers: <l>Vox ista doctrina est, non querela</s>—That voice utters teaching, not complaint (De Pass. s. 16). Jesus Christ did not thus speak to the eternal Father to be delivered from death, nor was he speaking of his own abandonment, but of the abandonment of grace, of which all men would have remained deprived if he had not died for our salvation. He was praying then in our name, that we might be delivered from eternal death; in our name also he prayed for his resurrection, to make us also have a share therein. So that he then put himself in our place, and thus prayed not to be abandoned, whilst at the same time he offered up his own death in order to save us from the abandonment that we had deserved, and he did not die himself until he had at first made our salvation secure. This is the reason why, towards the end of the psalm, he gives thanks to his Father, and sings the fruits of his victory.
2~I invoke Thee by day, and Thou dost not hear me; I invoke Thee also by night; ah! attribute not my prayers to imprudence and indiscretion.
3~“<l>Laus Israel.</s>” Thou art the praise of Israel on account of the many graces that Thou hast vouchsafed to him; but now it seems to me that Thou wilt not listen to me.
4~Our Lord is here speaking of the deliverance which the holy Fathers under the Old Law were to obtain by his death.
6~“<l>Sum vermis, et non homo.</s>” Behold! I am no longer looked upon as a man, but as a worm of the earth.
7~All seeing me reduced to this miserable state have set themselves to mock me: they have spoken against me, and insult me by wagging their heads. A reference to the words that we read in the Gospel: <l>Prætereuntes autem blasphemabant eum, moventes capita sua</s>—And they that passed by blasphemed him, wagging their heads (Matt. 27:39).
8~They have said: He put his hope in the Lord; let then the Lord deliver him, since he has a will for him and protects him. Moreover, we read in the Gospel: <l>Confidit in Deo; liberet nunc, si vult eum</s>—He trusted in God; let him now deliver him, if he will have him (Matt. 27:43).
9,10~It was Thou, O Lord, who hast drawn me out of the womb of my mother, and from her breasts; since then I have placed in Thee all my hopes; I have always acknowledged Thee for my God; in mercy, then, do not abandon me.
11~Bellarmine says that Jesus Christ is here speaking of his death which is approaching, as what precedes and what follows clearly prove.
12~By bulls are meant the chief priests and Pharisees, who by their sharp words and mocking jeers, as if with thrusts of horns, insulted Jesus Christ, saying: <l>Alios salvos fecit, seipsum non potest salvum facere; si rex Israel est, descendat nunc de cruce, et credemus ei</s>—He saved others; himself he cannot save; if he be the king of Israel, let him now come down from the cross, and we will believe him (Matt. 27:42).
13~“<l>Sicut leo rapiens et rugiens.</s>” Like so many famished lions greedy to devour me, roaring with rage. Such were the Jews when they cried out to Pilate: <l>Tolle, tolle; crucifige eum</s>—Away with him, away with him, crucify him (John 19:15).
14~“<l>Sicut aqua effusus sum.</s>” I am spent of all my strength through the shedding of my blood, which has poured forth from my body like water from a vase. “<l>Dispersa.</s>” According to the Hebrew: <l>Divulsa</s>—Torn from their sockets, out of joint.
15~Notwithstanding all that, my heart, far from being hardened against my enemies, has become soft like melted wax, through the compassion that I have for their evils.
16~“<l>Et in pulverem mortis deduxisti me.</s>” In short, Thou hast, O my God, brought me to lie beneath the dust of the tomb that covers the dead.
18~They have pierced my hands and my feet with nails; they have so stretched my body upon the cross that all my bones can be counted. In these words David clearly describes the crucifixion of Jesus Christ; thus St. Jerome, St. Augustine, Theodoret, and Euthymius explain the passage.
19~My executioners after crucifying me have set themselves to watch me with contempt, and to gaze upon my sufferings with complacency. They have parted my garments among them, and for my under-tunic, which was woven entire, and without seam, they cast lots. This text is quoted in the Gospel where we read: <l>Ut impleretur quod dictum est per Prophetam, dicentem: Diviserunt sibi,</s> etc.—That it might be fulfilled which was spoken by the prophet, saying: They divided my garments, etc. (Matt. 27:35). This is a certain proof that our Saviour died naked upon the cross.
21~Save my life promptly from the sword of death by raising up my body after I shall be dead. Cause my soul, which appears now left alone and abandoned, to triumph over the infernal dog.
22~Save me from the lion, which keeps its mouth open to devour me; and protect my weakness from the assaults of these ferocious unicorns.
23~The prophet here speaks more expressly of the resurrection of our Lord, and of the fruit that it would produce, namely, the conversion of the Gentiles. He says: I will publish the glory of Thy name by means of my brethren the apostles, etc.
24~“<l>Semen Jacob.</s>” By this is meant Christians who have the faith of Jacob.
25~“<l>Pauperis.</s>” This poor man is Jesus Christ himself, who died upon the cross naked and abandoned by all.
27~I will praise Thee, O Lord, in the great assembly, the Church of the faithful gathered together from all the nations. In their presence I will pay my vows, renewing my sacrifice, by the ministry of my priests.
28~The poor in spirit, who are conscious of their spiritual misery, shall feed upon and be satiated with grace; and they that seek the Lord shall praise him, and hence their souls shall live eternally.
29,30~All the nations even to the farthest bounds of the earth shall call to mind the benefits of God, and the mysteries of the Redemption, which shall be preached to them, and they shall be converted to the Lord; so that all the nations of the Gentiles shall enter the Church to adore the true God.
32~Not only the poor, but also “<l>Pingues terræ.</s>” the great and powerful of the earth, who abound in riches, shall eat at the table of the Lord, and shall adore him; and in bowing down to adore, they shall humble themselves even to the earth. “<l>In terram.</s>” According to the Hebrew: <l>In pulverem</s>—To the dust. Hence this other interpretation, which is also probable: All men, who since they are mortal must return to dust, shall prostrate themselves before him.
34~The generation to come of believers shall receive the good tidings of the Lord, that is to say, the knowledge of the faith; and the heavens, or heavenly men, shall publish the justice of God, or the justice of faith, which makes men just, to the new people that shall be born to the life of grace; a people which the Lord has made, that is, a special people of God, created in Jesus Christ.
