0~The prophet here invites the people to come to adore God in his Temple. Under this figure the Gentiles are invited to receive the Gospel, which had to be preached in the midst of persecutions, here represented by the winds, the tempests, and the thunders, which are mentioned in this psalm.
1~“<l>Filios arietum.</s>” Young rams, to offer them to him in sacrifice.
3~The Lord makes his voice heard upon the waters during the storms; in the noise that is then produced by the abundance of the waters, mingled with peals of thunder, he makes the voice of his majesty heard.
4~“<l>In virtute.</s>” According to the Hebrew: <l>In potentia</s>—In power. The Lord makes his voice known in his power and in his grandeur; for when he wills he makes the earth and the sea tremble.
5~“<l>Cedros Libani.</s>” That is to say: The loftiest and strongest trees, which it destroys by the violence of the tempests.
6~“<l>Comminuet.</s>” According to the Hebrew: <l>Saltare faciet</s>—He shall make them leap as a calf that goes bounding over the mountain of Libanon. “<l>Dilectus.</s>” The unicorn, when little, is admired for its beauty.
7~“<l>Intercidentis flammam.</s>” St. Jerome’s translation is: <l>Dividens flammas;</s> that is to say, the thunder darts a number of lightning flashes one after the other. “<l>Desertum Cades.</s>” A vast desert of Arabia.
8~“<l>Præparantis cervos.</s>” This means, according to some interpreters, that the thunder so terrifies the deer that parturition is hastened. These authors rest on the Hebrew text, which is thus translated: <l>Vox Domini parere faciens cervas</s>—The voice of the Lord makes hinds bring forth. But I prefer the interpretation of Mattei, who says that the voice of the Lord, or the thunder, so frightens the deer as to drive them from their thickets; and he observes that the Vulgate does not use the word <l>Cervas,</s> but <l>Cervos.</s> “<l>Et revelabit condensa; et in templo ejus omnes dicent gloriam.</s>” That is to say, the Lord lays open to daylight the thick forests by shivering and uprooting the trees with his thunderbolts; after which all men will go to render homage to the glory or to the power of the Most High in his Temple.
9~God makes the deluge of waters that inundate the earth to dwell, to abide, or last; and he himself, as Lord and eternal King seated upon the clouds, disposes everything for his glory.
10~The Lord will give to his people the virtue of trusting in his protection; and then blessing them he will fill them with peace.
