0~Forced by his son Absalom to leave Jerusalem, David asks help of God. This psalm is perfectly suited to a Christian who sees himself assailed by temptations, and who, animated by confidence, asks God for aid and protection. It must be remarked that our Lord Jesus Christ makes to himself the application of the sixth verse of this psalm: a proof that the persecution of David prefigures that which our Redeemer had to endure at the hands of the Jews.
1~“<l>In justitia tua libera me.</s>” Deliver me from confusion by Thy justice, according to which Thou punishest the guilty and protectest the innocent.
2~Incline Thy ear to my prayers, and hasten to deliver me from the peril in which I find myself.
4~Thou art my strength in temptations, and my refuge in persecutions; I hope that for the glory of Thy name Thou wilt lead me safe through all dangers, and provide for me in all my wants.
6~Into Thy hands I commit my life, because many other times Thou hast delivered me from death, Thou who art my Lord and my God, ever faithful in Thy promises. Some think that these words, and indeed the whole psalm, are to be understood of Jesus Christ, because before expiring he said on the cross: <l>Pater, in manus tuas commendo spiritum meum.</s> Bellarmine, however, justly observes that our Lord, in dying, might well use these words, but not the following: <l>Redemisti me, Domine, Deus veritatis</s>—Thou hast redeemed me, O Lord God of truth; for Jesus Christ was himself the Redeemer, and not the redeemed.
7~“<l>Observantes vanitates, supervacue.</s>” St. Jerome translates the passage thus: <l>Custodientes vanitates frustra</s>—Thou dost hate those who keep, that is, who love the vanities, or the false goods of this world; which they do uselessly, <l>supervacue,</s> for they will never find the peace for which they hope.
9~Thou hast looked upon my weakness, and Thou hast saved my life from many dangers.
10~Thou hast given me a large field, to deliver myself from the enemies that would close the way against me.
11~Have pity on me, O Lord! for I see myself troubled by the remembrance of my sins; my eyes, my soul, and my bowels, that is to say, all my powers, exterior and interior, are troubled at the sight of Thy anger, provoked by my infidelity. Such is the explanation given by Bellarmine, who follows St. Augustine.
14~“<l>Timor notis meis.</s>” My friends are afraid of being known to be my friends.
20~“<l>Illustra faciem tuam super servum tuum.</s>” Turn Thy gracious eyes upon me. “<l>Non confundar.</s>” I hope that I shall not be abandoned by Thee.
21~“<l>Erubescant impii, et deducantur in infernum.</s>” May confusion fall rather upon the wicked, and may they be buried in eternal oblivion.
22~“<l>In abusione.</s>” According to the Hebrew and Greek: <l>In contemptu</s>—with contempt.
23~“<l>Quam abscondisti.</s>” An expression that shows that this treasure is hidden from the wicked, who do not fear God.
25~Thou wilt make them enjoy in secret Thy sensible presence, as happens to certain privileged souls. In this secret place they are sure not to be troubled by men of the world, or by human passions.
28~“<l>In excessu mentis meæ.</s>” According to the Hebrew: <l>In stupore meo</s>—In the excess of my tribulation, which held me stupefied.
30~“<l>Veritatem requiret.</s>” According to the Hebrew: <l>Sinceros tuetur</s>—He protects the sincere. The sense of the verse is: All you that serve the Lord, love him; for he will test your innocence, and he will know well how to defend those that love him, as he knows how to punish the proud with terrible torments.
