0~This psalm teaches us what a happy life one leads when, having returned from wicked ways, one does penance; and, on the other hand, what an unhappy life one leads when one persists in remaining in sin.
1~“<l>Quorum tecta sunt peccata.</s>” Whose sins have been covered, that is to say, blotted out. Protestants use these words, to prove, as they say, that sins, though forgiven by the mercy of God, are not removed from the soul, but are only covered, so that the stain of guilt remains in the soul, and that God always sees this stain; but he remits the penalty due, as if he did not see it. They add that God remits the sin only so far as he does not impute it to the sinner, according to what is said in the following verse: <l>Beatus vir citi non imputavit Dominus peccatum</s>—Blessed is the man to whom the Lord hath not imputed sin. But all this is false; for God, in forgiving sins, does not cover them, but for the merits of Jesus Christ he takes them away from the penitent soul, as holy Scripture says: <l>Dominus quoque transtulit peccatum tuum</s>—The Lord also hath taken away thy sins (2 Kings 12:13). <l>Ecce Agnus Dei, ecce qui tollit peccatum mundi</s>—Behold the Lamb of God, behold him who taketh away the sins of the world. Moreover, as the Council of Trent has declared, man is justified not only by the remission of sin, but by grace and inherent justice. And if it is said that God does not impute sin, this is, so far as he remits and blots it out, as the same Council also teaches (Sess. 6, de Justif. cap. 7, can. 11).
2~“<l>Non imputavit peccatum.</s>” Has not imputed his sin, because he has forgiven it him. “<l>Nec est in spiritu ejus dolus.</s>” He has sincerely repented of his fault.
3~I did not confess my sin, and this silence made me lament the whole day long, so that my bones have grown old; that is to say, my continual tears have weakened me, as if my bones had become old, or had lost their strength and were broken. St. Jerome’s translation is: <l>Attrita sunt ossa mea, in rugitu meo tota die</s>—My bones are bruised so that the whole day I cried out through pain.
4~Thou hast afflicted me with justice; and hence when tribulation was piercing me like a sharp thorn, the only course I took was to return to Thee, my God, beseeching Thy mercy. “<l>Configitur.</s>” According to the Hebrew: <l>Configitur mihi.</s>
6~When I had resolved to confess my injustice, Thou didst at once pardon me my enormous fault.
7~“<l>Pro hac.</s>” That is to say, according to Bellarmine and Mattei: For this reason. “<l>Omnis sanctus.</s>” According to the Chaldee: “<l>Omnis pius.</s>” That is to say: Every sinner truly penitent, who is holy and pious, because in stripping himself of his impiety he clothes himself with holiness by means of grace. “<l>In tempore opportune</s>” In this life, when we can obtain forgiveness of our sins before death.
8~In the flood of many waters, that is to say, at death and at judgment, when scourges shall fall as a torrent upon the wicked, they shall then no more approach God, because there will then be no longer any pardon for them.
10~Here David makes the Lord speak to the penitent sinner. “<l>Firmabo super te oculos meos.</s>” I will continue to look upon thee with a favorable eye, and to protect thee.
11~The Lord addresses these words to those that are hardened sinners.
12~Restrain, O Lord! those that keep far from Thee, and force them to obey Thee.
13~Many are the chastisements reserved for sinners; but he that hopes in God shall be surrounded by his mercy so that he will not be able to go beyond its reach and be lost.
14~“<l>Gloriamini.</s>” Let your glory be to serve and to love the Lord.
