0~St. Ambrose, St. Jerome, St. Augustine, and Euthymius see in this whole psalm only Jesus Christ and the holy Church, that is, the Head of his mystical body. And, in fact, in his Epistle to the Hebrews (10:5 <l>et seq.</s>) St. Paul applies to Jesus Christ certain verses of this psalm, which can really not be understood of David without counting several other passages which it would at least be difficult to apply to the holy king. If Jesus Christ addresses himself to his Father with so much humility and gratitude, it is because he speaks according to his humanity; he likewise speaks inasmuch as he is the Head of the predestined, and inasmuch as he has as man assumed our obligations towards God. And it is thus that, charged with our sins and as our established mediator between us and God, he prays, humbles himself, and trembles.
1~“<l>Expectans expectavi Dominum.</s>” I have waited a long time for the Lord as liberator and redeemer of his people. “<l>Intendit mihi.</s>” According to the Hebrew: <l>Inclinavit se ad me</s>—He has inclined himself to me to listen to me.
2~“<l>De lacu miseriæ et de luto fæcis.</s>” These expressions denote, according to the Hebrew text, as Bellarmine remarks, a deep abyss, without light, filled with filthy mud, in which have fallen and flounder confusedly a miserable multitude; such are those that are plunged into the mire of their carnal appetites.
3~“<l>Super petram.</s>” That is to say: Upon myself, I who am the foundation-rock of the Church: <l>Petra autem erat Christus</s>—The rock was Christ (1 Cor. 10:4). “<l>Et direxit gressus meos.</s>” He placed my feet on a way that is not only solid, but also straight; and he thus guided my steps.
4~“<l>Canticum novum, carmen.</s>” A new canticle, a canticle of love, of thanksgiving, and of praise; according to the Hebrew, which would be <l>Laudem</s>—Praise, instead of <l>Carmen.</s>
5~Many shall see, or shall come to know, the misery of the pit in which they are, and shall have fear or horror of it; they shall then see their deliverer, and shall put their trust in the Lord.
6~“<l>Vanitates.</s>” Human supports, which are all vain. “<l>Insanias falsas.</s>” Earthly goods, from which it is only folly to hope for happiness.
7~“<l>Cogitationibus tuis.</s>” In the inventions of Thy love which Thou hast conceived and carried into effect for our good.
8~“<l>Multiplicati.</s>” Bellarmine thinks, according to the Hebrew text, that perhaps an error has here crept in, and that it should be: <l>Multiplicatæ (cogitationes tuæ)</s> or <l>Multiplicata (mirabilia tua)</s>—Thy thoughts or Thy marvels are multiplied. But St. Ambrose, St. Jerome, and St. Augustine say that the verse is to be read as it stands: <l>Multiplicati sunt super numerum;</s> this is to be understood of unbelievers who have been converted to follow Jesus Christ.
9~“<l>Sacrificium et oblationem noluisti.</s>” Thou hast refused the sacrifices and the offerings of the Law, which could not avail to purify the consciences. This means that God did not accept those sacrifices as sufficient to expiate for sin and to remove it from the soul; but that he accepted them only as figures of the sacrifice of Jesus Christ. Hence the Redeemer says: <l>Aures autem perfecisti mihi;</s> this St. Paul thus expresses: <l>Corpus autem aptasti mihi</s>—A body Thou hast fitted to me (Heb. 10:5). We must not deviate from this text of the Apostle, who by it explains that of David; so that it means: Thou hast formed for me a body fitted to suffer and to die.
10~“<l>Tunc dixi: Ecce venio.</s>” Then that is, on hearing Thy decree that I should assume human nature and offer myself on the cross as a sacrifice to atone for the sins of men I said: Behold I come to obey Thee.
11~“<l>In capite Libri.</s>” According to the Hebrew: <l>In volumine Libri.</s> That is to say: In the volume of the Law. By this St. Ambrose understands the beginning of Genesis, where we read: <l>Quamobrem relinquet homo patrem suum et matrem, et adhærebit uxori suæ; et erunt duo in carne una</s>—Wherefore, a man shall leave father and mother, and shall cleave to his wife, and they shall be two in one flesh (Gen. 2:24). On this passage St. Paul comments thus: <l>Sacramentum hoc magnum est, ego autem dico in Christo et in Ecclesia</s>—This is a great sacrament, but I speak in Christ and in the Church (Eph. 5:32). According to St. Jerome it refers to the Gospel of St. John, which begins with these words: <l>In principio erat Verbum ... Et Verbum caro factum est</s>—In the beginning was the Word ... and the Word was made flesh. But Bellarmine thinks that the expression <l>In volumine Libri</s> denotes rather the whole volume of the Bible, which speaks throughout of the Messias who was to come, as say St. John Chrysostom and Theodoret, because Jesus Christ is the end of the Law. — St. Paul, after having said that God did not accept the ancient sacrifices that were offered for sin, quotes this text: <l>Tunc dixi: Ecce venio,</s> etc.—Then said I: Behold I come, etc. He then adds: <l>Aufert primum, ut sequens statuat. In qua voluntate sanctificati sumus per oblationem corporis Jesu Christi semel</s>—He taketh away the first, that he may establish that which followeth: in the which will we are sanctified by the oblation of the body of Jesus Christ once (Heb. 10:7-10). He thus gives us to understand that by the one sacrifice of the cross, by which Jesus Christ delivered us from sin and sanctified us, all the ancient sacrifices were abolished.
12~I have made known Thy just law in a great assembly, that is, to a numerous people; and Thou knowest that I have done so, and that I shall continue to do so by myself till my death, and after death by means of my disciples.
13~I have preached publicly to a great multitude of people Thy justice and Thy truth, by which Thou renderest to every one to his works, and I have announced at the same time the salvation that Thou hast promised to him that hopes in Thee. “<l>Non abscondi in corde meo.</s>” In contrast with those that keep the truth shut up in their heart, and do not preach it through some human respect.
16~“<l>Comprehenderunt me iniquitates meæ.</s>” My sins have laid hold of me to afflict me with remorse, so that I am unable to look at them for horror.
17~My heart has abandoned, or failed me from sorrow.
21~“<l>Euge, euge.</s>” Well done, well done, we have made an end of him.
22~“<l>Salutare tuum.</s>” The salutation that they hope from Thee.
23~Although I see myself poor and miserable, I console myself with the thought that the Lord takes care of me, that is, of my salvation.
24~“<l>Ne tardaveris.</s>” Do not delay to help me when Thou seest me in danger.
