0~This psalm, like the preceding, refers to the Passion of Jesus Christ; it is so interpreted by St. Ambrose, St. Jerome, St. Augustine, and particularly by St. John Chrysostom, who says that it would be rash to interpret it otherwise; for Jesus Christ himself, as we see in the Gospel of St. John (John 13:18), cites a verse of this Psalm (the 10th) to signify that the treason of Judas had long before been predicted by the prophet. This psalm speaks also of the mystical Body of Jesus Christ, of the Church.
1~Happy is he that devotes himself to the work of helping the poor, or whoever is in need of assistance; in the evil day, that is, the day of his death, the Lord will deliver him from all his trials.
2~“<l>Dominus conservet eum, et vivificet eum.</s>” The Lord will preserve him in the midst of dangers, and will so fortify him that he will come safe out of them. “<l>In animam.</s>” According to some Greek copies, as St. Ambrose remarks, it is: <l>In manus.</s> But Bellarmine justly observes that the sense is almost the same, except that the expression <l>In animam,</s> that is, <l>voluntatem, arbitrium</s>—to the will, or good pleasure, is more expressive than <l>In manus</s>—to the power.
3~At the time of his last illness the Lord will bring him help in his sufferings: Thou, O good Master, wilt prepare his couch, so that, reduced to extremity, he may find some alleviation.
4~“<l>Sana animam meam, quia peccavi tibi.</s>” Heal my soul, which has become sick through the offences that I have committed against Thee.
6~“<l>Vana loquebantur.</s>” He feigned a cordial compassion. “<l>Congregavit iniquitatem sibi.</s>” He consoled himself by redoubling his wicked hope of seeing me die.
7~He then went out to make others take part in his wickedness.
8~“<l>Adversum me cogitabant mala mihi.</s>” They united to plot against me, and to wish me all the evil that could befall me.
9~They are confirmed in their design upon my life, saying: Shall then he that dies think to return to life again?
10~This verse refers to the treason of Judas, according to what we read in the Gospel of St. John: “<l>Ut adimpleatur Scriptura: Qui manducat mecum panem, levabit contra me calcaneum suum</s>”—That the Scripture may be fulfilled: He that eateth bread with me shall lift up his heel against me (John 13:18). “<l>Magnificavit super me supplantationem.</s>” He has made it his boast to complete my ruin by offering to give me up into the hands of my enemies.
11~“<l>Resuscita me; et retribuam eis.</s>” Prediction of the resurrection of Jesus Christ: After I shall be dead on the cross, make me rise again; and then, as judge, I shall inflict upon them the punishment that they deserve. The Son of God here prays his Father to raise him up again, because he is praying as a servant; but he was well able for that matter to raise up his body again by his own power, as the Word of the Father and true God equal to his Father. This is what in fact happened, as he himself declared: <l>Potestatem habeo ponendi eam (animam meam), et Potestatem habeo iterum sumendi eam</s>—I have power to lay down my life; and I have power to take it up again (John 10:18).
12~“<l>Super me.</s>” Over me, on account of my death.
13~On account of my innocence, Thou hast defended me from my enemies, and Thou hast placed me in heaven at Thy right hand for all eternity. This happened at the Ascension of Jesus Christ.
14~“<l>Fiat, fiat.</s>” In the Hebrew: <l>Amen, amen.</s> So be it; let all be for his praise and glory.
