0~A canticle in honor of Jesus Christ and of the Church, his Spouse. The prophet plainly announces the mystery of the Incarnation of the Word and the victory which the Redeemer was to gain over the world.
1~My heart, full of divine illuminations, breaks out in holy words, and utters this hymn in honor of my King, who is the Messias.
2~My tongue is as the pen in the hand of a rapid writer, who writes all that is dictated to him by the Holy Spirit.
3~Thou, my King and my Saviour.
5~“<l>Specie tua et pulchritudine tua.</s>” St. Jerome translates: <l>Gloria tua et decore tuo.</s> “<l>Intende.</s>” Go forward. “<l>Prospere procede, et regna.</s>” Do not cease to advance from victory to victory, and establish Thy reign in the world.
6~Reign with truth, that is, with fidelity to Thy promises, with the meekness that Thou usest towards sinners, and with the justice that Thou exercisest in judging the obstinate; thus will Thy power lead Thee on wonderfully to extend Thy kingdom.
7~The people, conquered by Thy arrows, or by the rays of Thy light which has power to penetrate hearts, will fall and submit themselves to Thee, so that Thy enemies, who before despised Thee, shall be brought to adore Thee.
8~Thus, O God, Saviour of the world! Thy throne, or Thy reign, unlike the temporal reigns of other kings, shall be eternal in the Church; and Thy rod, that is, Thy sceptre or Thy government, shall ever be most just. — “<l>Virga directionis</s>” means the same as <l>Virga rectissima.</s>
9~“<l>Præ consortibus tuis.</s>” That is, Exalting Thee, so as to make Thee sit at his right hand a glory that surpasses that of all the men and angels who shall be with Thee in heaven. It is here said that Jesus Christ is anointed or constituted King of the world. This is to be understood, not of his divinity, but of his humanity. We are to understand also that he is anointed with the unction of grace as Head of the faithful, who through his merits shall receive graces from God.
10~“<l>A vestimentis tuis, a domibus eburneis.</s>” Here by the garments and by the ivory houses is to be understood the most sacred humanity of the Redeemer. Hence the verse is thus explained: From Thy humanity comes the odor of most pure and sweet perfumes; an odor that leads the daughters of the kings, or great souls, to rejoice Thee by running to adore Thee.
11~“<l>Regina.</s>” By this Queen is understood the Church, and we may also understand the Mother of God, or every holy soul that is a spouse of Jesus Christ, and therefore a queen, as St. Bernard says: <l>Singulæ animæ singulæ sponsæ</s>—Every soul, a spouse.
12~Then is said to this Queen: “<l>Vide, et inclina aurem tuam.</s>” Behold the honor to which thou art raised, and listen to that which thou hast to do.
13~The King shall love thy beauty, he who is thy Spouse, whom alone thou shouldst love, since he is the Lord, thy God, and whom in the end all must adore.
14~This is addressed only to the Church: The daughters of Tyre, that is, the Gentile nations, shall honor thee with gifts and offerings; among them shall be seen all the great ones of the people prostrating themselves before thee, to implore thy protection.
15~Her glory should consist in interior virtues of the soul, more than in exterior ornaments or in what is manifest to others.
16,17~In the train of the Spouse many virgins shall be brought to the King in his temple; but they shall be those only that are her nearest, that is, united with the Queen and Spouse, who is the Church, according to the explanation of St. Basil and St. Augustine.
18~According to St. Basil, St. John Chrysostom, St. Jerome, and St. Augustine, these words are addressed to the Church, and their sense is: O Spouse of the Saviour! instead of the fathers of old, the patriarchs and the prophets, who are now no more, there are born to thee sons, the apostles, the disciples and their successors, whom thou hast constituted princes over the whole earth; for by their preaching the Gospel thou hast subjected all the nations to thy obedience.
19~O Lord! these apostles, these disciples and their successors in every age, shall continue to preach throughout all generations Thy name, that is, Thy power and Thy mercy towards men. “<l>Memores erunt.</s>” Many, according to the present Hebrew text and the Greek version, read: <l>Memor ero</s>—I shall remember. But St. Jerome and St. Augustine follow the Vulgate.
20~Therefore the nations, converted to the faith, will never cease to adore Thee.
