0~The psalmist here addresses the faithful, to teach them to despise the goods of this world and to fear only a bad death which must be followed by the sentence of condemnation. Then he raises their thoughts to the consideration of this truth, that only in God can true happiness be found. Of course, all this is said in an obscure manner; but thanks to the light of the Gospel, we are able to see the thought of the prophet.
3~I shall speak to you only of the things that it is necessary to know; I will tell you what I have meditated in my heart, that you may know how to act prudently in all that you do.
4~I shall attentively hear the truths that are proposed to me in parable; and this enigma I will explain to you to the sound of the harp. “<l>Propositionem meam.</s>” According to the Hebrew: <l>Ænigma meum.</s>
5~Why should I fear on the evil day, that is, on the day of my judgment? Only my iniquity makes me fear, especially the iniquity of my heel; that is, that which shall follow me unto death, which is the end of my life, as the heel is the end of my body.
7~“<l>Frater non redimit, redimet homo.</s>” <l>Non</s> is again understood before <l>homo,</s> according to the usage of Scripture, as Bellarmine remarks. The sense, then, is: At the moment of death their brother will be unable to deliver them from the peril; and much less will any other man be able to do so.
9~“<l>Non videbit interitum.</s>” These words, according to Bossuet, are to be understood in an ironical sense as if the prophet said: <l>An putabit se non visurum interitum?</s>—Will he suppose that he will not see death? Others give this interpretation: He shall not see death, that is, he shall not die before having finished the natural course of his life, although he sees wise men die. Or, as Bellarmine says, we may understand the passage to mean: He shall neglect to provide for death, which is waiting for him at its time; for the sinners avoid thinking of death; but alike for the fool as for the wise, there must come a day when they must die.
11~It is there that they shall dwell for several generations; there shall be nothing left of them in their lands but their names written on tablets of marble, or on the walls of their houses.
12~“<l>Non intellexit.</s>” He did not understand what he should have understood as man.
13~“<l>Hæc via illorum scandalum ipsis.</s>” Such is their way, that is, their life, in which they find many dangerous occasions that may bring them to ruin.
14~These miserable men, living like animals without reason, they will one day find themselves as victims of divine justice, cast into hell, where death shall feed on them; that is, where their death will be eternal. As sheep feed upon the blades of grass, and leave the roots to sprout forth again, so death torments unceasingly the reprobate, still leaving them life, that they may go on suffering eternally.
15~At the general resurrection, which is “morning,” or the beginning of the age to come, the wicked shall see the just established their masters and their judges; then the power which they had in this world will be shattered and destroyed in hell, after all the vain glory of which they boasted during their life. “<l>Auxilium.</s>” According to the Hebrew: <l>Robur, potestas.</s>
16~“<l>Cum acceperit me.</s>” When he shall receive me among his servants, after having completed the work of Redemption.
18~“<l>Non sumet omnia.</s>” A Hebraism: He shall take nothing away with him.
19~The sinner shall be blessed, that is, applauded by worldlings during his life upon earth; while he will not praise you, save when you load him with earthly goods.
20~After his wicked life this wicked man shall go into the abode of his ancestors, whose bad example he has followed, and there he will remain forever, never more to see the light.
21~Repetition of verse 12 for the conclusion.
