0~David, contrite and humbled, bewails his sins. In this psalm is perfectly expressed the sorrow that a sinner feels when repenting of his faults he humbly asks God’s pardon. It is the fourth penitential psalm.
1~Show to me great mercy because I am a great sinner.
2~“<l>Dele iniquitatem meam.</s>” Blot out from my soul all my sins.
4~I well know the enormity of my sin, which is continually before my eyes, reproaching me with the evil that I have done.
5~O Lord, against Thee alone I have sinned, and I have dared to do evil before Thy eyes; but I hope to receive from Thee the pardon which Thou hast promised to repentant sinners so that Thou mayest be justified in Thy words. <l>In sermonibus tuis,</s> that is, in regard to Thy promises to pardon him who repents, and that Thou wilt overcome, that is, Thou wilt shut the mouth of my enemies, who think and dare to say that it is not just that I should receive pardon for so great a sin, when Thou shalt judge me. It must be remarked that this verse is variously explained by others. “<l>Tibi soli peccavi.</s>” Bellarmine, Tirinus, and Mattei, following the commentary of St. Cyril and of St. Gregory, explain thus: <l>Tibi soli peccavi ut judici</s>—Against Thee only have I sinned as Judge. I have sinned against Thee alone, in this sense, that Thou alone art to judge me; for though it is true that I have also sinned against my neighbor by causing the death of Urias and by scandalizing the people, nevertheless I am afraid of Thee alone; because as king I have no one on earth to judge me, and yet I have to be judged, and by Thee alone be punished, and not by men. This commentary is beautiful, but the interpretation given above appears to me more simple and more appropriate: “Lord against Thee alone I have sinned,” for it was God’s law only that David transgressed. It is no objection that he had also offended against Urias and the people; for these offences were sins only so far as they were transgressions of the law of God, since all the malice of sin consists in the transgression of the divine law, according to what the Apostle says: “<l>Peccatum non cognovi, nisi per legem.</s>”—But I did not know sin, but by the law (Rom. 7:7). Hence David said with good reason: Against Thee only I have sinned; for Thy law alone I have transgressed. “<l>Ut justificeris.</s>” Theodoret says that the particle <l>Ut</s> does not here signify cause but consequence. “<l>Judicaris.</s>” According to the Hebrew: <l>Judicaveris</s>—Thou shalt judge.
6~I have had the misfortune of being conceived in sin; when my mother conceived me I appeared in the world already a sinner.—As if he would say: what, O Lord! couldst Thou expect, from a man conceived in sin?—Grotius explains this passage thus: I was guilty from my birth. But this interpretation seems to favor the opinion of Socinus, who denied original sin, and denied that it was contracted from the moment of conception; whereas this text proves perhaps more clearly than any other that all men are conceived in original sin.
7~Thou lovest the truth, and him also who confesses his fault: I confess my ingratitude, inasmuch as Thou hast favored me by making known to me the secrets of Thy wisdom, secrets uncertain and hidden to others.
8~Reference is here made to the sprinkling of the blood of the victims, which was made over the lepers with hyssop to purify them (Levit. 14:6). That is to say: Cleanse me, O Lord! ever more and more.
9~In making me hear that Thou hast pardoned me, Thou wilt give to my soul a joy and gladness so great that my very bones, that is, all my interior powers, which have been so greatly afflicted, shall leap for joy.
10~My God, turn, then, Thy face from my sins, that is, look no longer upon them; and blot out from my soul all my faults, which gave Thee horror.
11~Change my heart, and give me a pure heart, that loves none but Thee: and renew within my bowels, that is, my interior, that right spirit which I had lost by sin.
13~Restore to me the joy of the salvation which Thou hast given me, and confirm me in good by means of a principal spirit, that is, one that is strong, inspired by Thee.
14~I promise Thee, on account of the scandal that I have given, to instruct sinners in Thy law, and I hope that they will be converted to Thee.
15~“<l>Sanguinibus.</s>” Rotigni and Lallemant give to this word a sense that is very probable, by explaining it to refer to the remorse of conscience with which David was afflicted on account of the blood of Urias.—“<l>Justitiam tuam.</s>” Bellarmine says that the pardon of sin is mercy with respect to us; but that it is justice with regard to Jesus Christ who, by his death, has merited for us pardon; and this is the divine justice of which David meant to speak.
17~If to satisfy for my sins Thou hadst required of me sacrifices, I would willingly have offered them to Thee; but I well know that with holocausts Thou art not satisfied.
18~The sacrifice that is pleasing to Thee, O my God! is a soul afflicted on account of its sin; when a heart is contrite and humbled Thou knowest not how to despise it.
19~That is: If I do not deserve to be heard, look, O Lord! with a gracious eye upon Thy city Sion, and according to Thy good-will, that is, in accordance with the purpose of Thy good pleasure, which Thou hadst in choosing it as Thy dwelling-place, show to it Thy favor, so that the walls of Jerusalem, now fallen in ruins, may be rebuilt.
20~Then wilt Thou accept with joy my sacrifices of justice, that is, as Bellarmine understands it, my homage justly due to Thee, and all my offerings and holocausts; and many, after my example, will offer to Thee upon Thy altar, calves, that is, choice victims, amongst which the calf was the noblest.
