0~David flying from the presence of Saul, who was seeking his death, retires among the Philistines; but when recognized by them who he was, he finds himself in great danger (1 Kings 21:10). Under these circumstances he composes this prayer, which every Christian can use when he sees himself in danger of falling into sin and becoming the prey of the devil.
1~The man, who is my enemy, has sought to tread me under foot; and therefore persecuting me the whole day, he has striven to afflict me.
2~All my enemies have united to plot continually my ruin.
3~“<l>Ab altitudine diei.</s>” Many, as Menochius, understand hereby the great dangers that threaten; but I prefer the interpretation of Calmet and Tirinus, which is more literal. According to it the verse is explained thus: During the whole day, from the rising of the sun, I am in a continual fear; but I hope from Thee, O Lord! the help that I need.
4~“<l>Sermones meos.</s>” According to the Hebrew: <l>Verbum ejus.</s> The promises that he has made me, or the word that he has given me. “<l>Caro.</s>” The carnal man, who in regard to God is but weakness (see verse 11).
7~“<l>Sustinuerunt animam meam.</s>” They have waited for the opportunity to take away my life. “<l>Pro nihilo salvos facies illos.</s>” So Thou wilt on no account save them. This is St. Jerome’s explanation. St. Augustine, on the contrary, gives this interpretation: Thou wilt save them, of pure grace, without any merit on their part. The sense of St. Jerome agrees better with the words that follow: “<l>In ira populos confringes.</s>” In Thy just wrath, Thou wilt break to pieces this crowd of enemies who would destroy me.
8~I lay before Thee all the afflictions of my life; I hope that Thou wilt always have my tears before Thy eyes.
9~As Thou hast promised, I hope that my enemies, filled with confusion, at seeing their designs brought to naught, will turn backwards.
10~I shall not fail to call upon Thee every day; for I have well known that Thou art my God, coming to my assistance, as Thou hast every time that I have called on Thee.
11~I shall always praise in my God and my Lord his faithfulness to his promises; and therefore, trusting in him, I will not fear that man can do me any harm (see verse 4).
12~This is the explanation that Bellarmine gives with St. Jerome: In me, that is, in my memory are always “<l>Vota tua</s>” the promises that I have made to Thee; hence I will never cease to offer to Thee the praises and the thanksgivings that are contained in these promises.
13~“<l>Ut placeam coram Deo in lumine viventium.</s>” In order that I may be well pleasing to Thee by means of the light of grace, whereby Thy servants live in the fidelity to Thee.
