0~In a figurative sense this psalm refers to Jesus Christ, who overcame death and ascended gloriously into heaven. It also foreshadows the sanctity of the Church and the protection that God, according to his promise, does not cease to give it a protection that should firmly establish it and make it glorious by so many victories. The prophet describes various prodigies of the Old Testament, figures of the prodigies that occurred in the New Testament. This psalm is, moreover, very obscure.
3~“<l>Delectentur in lætitia.</s>” Let them rejoice at their victory.
4~“<l>Qui ascendit super occasum.</s>” Who ascends above the darkness of the grave. “<l>Dominus nomen illi.</s>” For his name is that of the Lord: all things are under his dominion.
5~When he shall judge the world, sinners shall tremble with fear, while you shall stand rejoicing; for he is the Father of orphans, and the Judge who defends widows. This signifies that at the Last Judgment he will console all those that have been afflicted here on earth.
6~God sits in his sanctuary in heaven; and there in his house he makes his servants dwell; “<l>Unius moris,</s>” of one manner, that is, as one in unity of virtue and sentiments.
7~He sets free those that are held captive by their passions, and likewise those that have embittered him by their faults, and have dwelt in the sepulchre, the abode of death; that is, in his displeasure.
8,9~When Thou didst go forth in the sight of Thy people set free from Egypt, and didst go before them in the desert, in a cloud of light, the whole earth was moved, because the heavens showered down manna.
10~In the same way Thou dost wish to store up a great outpouring of grace for Thy inheritance, that is, for Thy new Church; so that, however infirm it may be, Thou knowest how to heal her and make her perfect.
11~There Thy flock shall abide, for which because of itself it is utterly poor, Thou hast in Thy goodness prepared abundant pastures.
12~The Lord will inspire words to those that will announce the new law, giving them great power to convert entire nations.
13~“<l>Rex virtutum dilecti dilecti.</s>” According to the Hebrew: <l>Reges exercituum confæderabuntur</s>—The most powerful kings of the earth will become subjects of the Well-Beloved (according to the Hebrew <l>Dilecti dilecti</s>); that is, of the Redeemer, who will be greatly beloved by them. “<l>Et speciei domus dividere spolia.</s>” And he, in order to render his house, that is, his Church, beautiful, will give her the power to divide the spoils of those kings converted by means of the Evangelists: that is, of the apostles, who divided among themselves all the kingdoms of the world, to lead them to embrace the faith.
14~This verse is very obscure, says Bellarmine; hence it will be necessary to explain it in detail. “<l>Si dormiatis.</s>” If you who preach the word of God sleep, that is, if you repose. “<l>Inter medios cleros.</s>” The word <l>Clerus</s> in Greek signifies lot, or inheritance; meaning: In the midst of the Church. But St. Jerome, St. Augustine, Theodoret, and others, understand by the word <l>Cleros,</s> the Old and New Testaments, and explain the first part of the words thus: If you repose in the midst of the two Testaments. “<l>Pennæ columbæ deargentatæ.</s>” The Church, or the union of the faithful, will be like a dove with its wings silvered with the purity of wisdom. “<l>Et posteriora dorsi ejus in pallore auri.</s>” And with its back gilt by the fervor of charity, which makes it all beautiful.
15,16~“<l>Dum discernit cælestis reges.</s>” While the heavenly King, that is, Christ, will divide and send forth his preachers, raised to the dignity of kings by the spiritual power given them over souls. “<l>Super eam.</s>” Over the Church scattered throughout the kingdoms of the earth. “<l>Nive dealbabuntur.</s>” Then the nations, purified from the blackness of their sins, will be come whiter than snow. “<l>Mons Dei, mons pinguis, mons coagulatus.</s>” The mountain of God, the Church, is a fat, or rich mountain, a coagulated, that is, a very rich mountain; for the milk of divine grace, with which it abounds, does not run off, but remains there coagulated and firm. “<l>Ut quid suspicamini montes coagulatos?</s>” O men, why do you think that there is another Church as fat and as rich as this one?
18~The chariot of the Lord is borne by many thousands of angels in great jubilee; it was thus the Lord was borne upon these celestial spirits, when he descended upon the holy mountain of Sinai.
19~This passage is referred to by St. Paul (Eph. 4:8): <l>Ascendens in altum, captivam duxit captivitatem; dedit dona hominibus</s>—Ascending on high, He led captivity captive; He gave gifts to men. He adds: <l>Quod autem ascendit, quid est, nisi quia et descendit primum in inferiores partes terræ?</s>—Now, that he ascended, what is it, but because he also descended first into the lower parts of the earth? The verse is, therefore, thus explained: Thou, O Saviour of the world! coming forth from the sepulchre, didst ascend to the highest heavens, and didst take with Thee those that were captives here below; and in heaven Thou didst receive the gifts from Thy Father, to dispense them to men.
20~For Thou hast bestowed Thy gifts on those who before did not believe that the Lord dwells in his holy mountain, that is, in his Church.
22~He is our God, whose property it is to save us; and it is his own gift to set us free from death. “<l>Exitus mortis.</s>” According to Bellarmine and Menochius: <l>Evasio mortis, ereptio et liberatio a morte</s>—Rescue and deliverance from death.
23~“<l>Verticem capilli.</s>” Denoting the top of the hair of the head; which means, that God will bring down the summit of their proud locks, or the crest of those that walk with pride in their sins, and do not walk in the law of God.
24~“<l>Ex Basan convertam.</s>” Mattei translates the Hebrew thus: <l>Ex Basan reducam.</s> That is: My people, I will deliver thee from the Basanites, or the people of Basan: and I will cast that people into the depths of the sea, as I did with Pharao.
26~Then did they see Thy glorious march, and Thy triumphs, O my King and my God! who art now in the holy place; that is, according to Bellarmine and Menochius, in heaven, or in the Church.
27~“<l>Principes.</s>” The heads of the people.
28~“<l>De fontibus Israel.</s>” According to the Chaldee version: <l>De semine Israel</s>—From the race of Israel. This is the reading adopted by St. Hilary, Theodoret, Euthemius, Vatable, and Tirinus, who cites these authors; and it is applicable to Jesus Christ: <l>Christo Domino, ortum habenti ex Israel</s>—To the Lord God, who has sprung from Israel.
29,30~“<l>Ibi.</s>” There in that triumph, described in verses 26, 27, and 28. “<l>Benjamin adolescentulus.</s>” The tribe of Benjamin, who was the last of the children of Jacob. “<l>In mentis excessu.</s>” In a transport of joy, as if in ecstacy. St. Hilary, St. Jerome, Theodoret, Bellarmine, and others, apply this passage to the apostles, who were almost all from one of the four tribes here named: St. Paul was of the tribe of Benjamin; St. James and St. John, and other relatives of our Lord, were of the tribe of Juda; and Galilee comprised especially the whole tribe of Zabulon and Nephthali.
32~“<l>A templo tuo.</s>” Mattei translates: <l>Post templum tuum;</s> and Bossuet: <l>Propter templum tuum.</s> The verse, then, is thus explained: After Thy temple has been built at Jerusalem, or, because of Thy temple that shall be built in Jerusalem, kings will offer Thee their gifts.
33~“<l>Feras arundinis.</s>” Bellarmine says that by this we are to understand the wild animals that hide among rushes. “<l>In vaccis.</s>” According to the Hebrew: <l>In vitulis</s>—Calves. The verse therefore means: Frighten our enemies, who, as wild beasts, and like an assemblage or a troop of savage bulls, together with the calves of the people, that is, the dissolute young men, will seek to exclude from the temple those that have been proved as silver. Such is the explanation given by Bellarmine, Menochius, and Tirinus.
34~“<l>Præveniet manus ejus Deo.</s>” St. Jerome thus translates the Hebrew: <l>Festinet manus Deo;</s> and Father Mariana’s interpretation is: <l>Junget manus pacem petens.</s> The sense of the verse, then, is: Thou wilt scatter, O Lord! the nations that wish for war; then ambassadors from Egypt and Ethiopia will come running with joined hands to ask for peace.
36~“<l>Cælum cæli.</s>” A Hebraism, which signifies: The highest heaven. “<l>Ad Orientem.</s>” Towards the east; that is, towards the Mount of Olives situated at the east of Jerusalem. It is thus explained by Menochius and Tirinus, following St. Hilary and St. Jerome. The sense is, therefore: Give praise to God, who ascends from the Mount of Olives to the highest heaven.
37~“<l>Vocem virtutis.</s>” A voice of power and efficacy. “<l>Deo super Israel.</s>” To the God of Israel. “<l>In nubibus.</s>” According to the Hebrew: <l>In cælis.</s> According to St. Augustine, this may be understood of the day of judgment when Jesus Christ will come <l>in nubibus coeli</s>—in the clouds of heaven; then, <l>dabit voci suæ vocem virtutis</s>—he will give unto his voice the voice of power; he will speak with so great power, that he will cause a great terror by the sentence that he will pronounce against the reprobate.
38~God will give to his people a virtue and a strength that will make them victorious over their enemies; let this great God be, therefore, ever blessed.
