0~David speaks here of his son Salomon, the presumptive heir of the kingdom of Israel, a figure of the spiritual kingdom of Jesus Christ. Thus speak commonly the holy Fathers and the commentators. Indeed, it seems to me that the whole or nearly the whole psalm should be applied to Jesus Christ; for certain expressions that are found in it, and especially verses 5, 11, 12, and 17, can only refer to Jesus Christ, to his coming among us, and to the vocation of the Gentiles; all of which mysteries David clearly saw by the prophetic light.
1~Give to the king the grace to judge justly, and grant to the son of David a righteous justice like Thine own.
3~“<l>Montes.</s>” This word is variously understood. Maldonatus understands it as if it were <l>Undique;</s> and meaning: May peace be enjoyed everywhere, even on the mountains. Emmanuel Sa writes: <l>Montes, id est, primores, sen præfecti</s>—the chief men or rulers. Malvenda: <l>Montes, id est, totum regnum montibus abundans</s>—the whole kingdom abounding with mountains. It is in this way Bossuet, with Bellarmine and Menochius, explains the verse: <l>Descendat de cælo pax et justitia, et super regnum Israeliticum requiescat</s>—May peace and justice descend from heaven and rest upon the kingdom of Israel. Lastly, Mariana, and with him Tirinus, says: <l>Montes, ubi scilicet solent esse latrones et feræ</s>—Mountains, that is, where robbers and wild beasts are wont to be. This last interpretation, as Lallemant thinks, seems to be the most probable. Hence the sense would be: May the mountains and the hills receive peace for the good of the people, that is: may even the people of the mountains, who are usually fierce and turbulent, taste the sweetness of peace and enjoy the fruits of the justice of the prince.
5~“<l>Ante lunam.</s>” Translation of St. Jerome: <l>Ultra lunam</s>—Beyond the moon. That is: His kingdom shall endure as long as the sun and the moon, and even beyond that.
6~“<l>Vellus.</s>” About this word there is a great diversity of opinion. Malvenda, Bellarmine, Menochius, Tirinus, etc., understand by it the fleece, or skin covered with wool, upon which Gedeon asked that all the dew that fell from heaven might be collected (Judges 6:37). Others, as Maldonatus, Mariana, Bossuet, Mattei, with Mark Marino, and Father Lallemant, are of opinion that the word Vellus here means something cut or shorn; hence Lallemant translates the passage thus: His coming to the throne will be like a rain that waters a meadow newly mown. But the first interpretation agrees better with that of St. Ambrose, Rupertus, and Procopius, who understand by the fleece the Mother of God, and by the dew the divine Word, who came down gently as the dew into the womb of the Virgin Mary, by the operation of the Holy Ghost. Moreover, the verse taken in this sense, has a better connection with the following: <l>Orietur in diebus ejus justitia et abundantia pacis</s>—In his days shall justice spring up, and abundance of peace. This is certainly to be understood of the coming of the Messias.
7~“<l>In diebus ejus.</s>” Under his reign. “<l>Donec auferatur luna.</s>” This happy state will last till the end of the world.
8~“<l>A flumine.</s>” St. Augustine, Theodoret, etc., understand by the river, the Jordan, because it was there, at the baptism of Jesus Christ, the eternal Father’s voice was heard saying: <l>Hic est Filius meus dilectus, in quo mihi complacui</s>—This is my beloved Son in whom I am well pleased (Matt. 3:17).
9~“<l>Terram lingent.</s>” Shall lick the earth, that is, shall bow down to kiss the earth that is under his feet.
10~“<l>Reges Tharsis, et insulæ.</s>” The kings of India and the inhabitants of the isles.
11~These verses, from verse 5th, can apply only to Jesus Christ.
12~“<l>Pauperem.</s>” The weak, or the feeble.
13~“<l>Parcet.</s>” According to the Chaldee: <l>Miserebitur</s>—He will have compassion.
14~“<l>Ex usuris.</s>” According to the Chaldee: <l>Ab oppressione</s>—From oppression. “<l>Et iniquitate.</s>” And from iniquity, that is, from injustice.
15~“<l>Vivet.</s>” He shall live, that is, his reign shall be everlasting. “<l>Vivet et dabitur ei.</s>” According to the Hebrew: <l>Vivet, et dabit ei.</s> Hence Maldonatus thus interprets this passage: The poor delivered by him shall live, and out of gratitude will give him gold of Arabia. “<l>Adorabunt de ipso.</s>” St. Jerome translates: <l>Orabunt de eo.</s> These words are thus commented upon by Emmanuel Sa: <l>De eo, id est, pro eo.</s> The people will continually pray for him and for the prosperity of his kingdom.
16~“<l>Firmamentum.</s>” The Hebrew text, St. Jerome, Bellarmine, Mattei, Lallemant, and all the interpreters of the Compilation of Venice, attest that <l>Firmamentum</s> is put here for <l>Frumentum;</s> and this is the explanation that is given: There will be such an abundance of wheat upon earth, and even on the summits of the mountains, that its fruits will rise above Lebanon, that is, the ears will rise higher than the cedars of Lebanon; and the inhabitants of the city of God, which is the Church, shall flourish or spring up like the herb of the field.
17~“<l>Nomen ejus.</s>” The name of this new king. “<l>Ante solem.</s>” According to the Hebrew: <l>Coram sole;</s> and as St. Jerome translates: <l>Ultra solem.</s> “<l>Permanet.</s>” According to St. Jerome, Menochius, Bossuet, etc., this verb is to be understood in the future.
