0~This psalm describes the wretched happiness of the wicked and the blessed afflictions of the just, since the end of the one class will be very different from that of the other. We learn, hence, not to be astonished when we see the wicked prosper and the good afflicted.
1~“<l>Israel.</s>” To Israel, or towards the people of Israel. Father Lallemant has understood this name as if it were in the genitive; but in the Greek it is preceded by the article in the dative, and so in the Hebrew text, of which the sense is: <l>Certe bonus est Deus Israeli</s>—Truly, God is good to Israel. It is thus that Bossuet, with several others, explains it.
2~That is to say: My belief was almost shaken through the emotion that I felt.
3~“<l>Super iniquos.</s>” St. Jerome’s translation is: <l>Contra iniquos.</s> “<l>Pacem peccatorum videns.</s>” At seeing the peace in which sinners live on account of the prosperity which they enjoy, or to speak more correctly, which they flatter themselves that they enjoy.
4~“<l>Quia non est respectus morti eorum.</s>” St. Jerome translates: <l>Quod non recogitaverint de morte sua</s>—Because they have not reflected on their death. “<l>Et firmamentum in plaga eorum.</s>” This passage is obscure, and is differently explained by interpreters. The word <l>Firmamentum</s> presents the greatest difficulty; But Gordona observes that if the particle <l>Non</s> be repeated, by understanding <l>Et</s> as <l>Nec,</s> the sense becomes easy. Thus: “<l>Nec est firmamentum in plaga eorum;</s>” <l>hoc est: Si quod illis accidit malum, cito transit, leve est, et sine firmamento</s>—Nor is there firmness in their wounds; that is, if any evil happens to them, it quickly passes, it is light and has no firmness. Hence the most natural explanation seems to be this: And in their wound, that is, when they feel themselves tormented by the fear of death, their affliction has no strength or firmness, and does not last long.
5~They are not in the travail of men, that is, they are exempt from poverty, from fatigues, and from other evils that afflict the generality of men; so that they are not scourged, that is, they do not suffer with other men.
7~“<l>Prodiit quasi ex adipe iniquitas eorum.</s>” Their iniquity has been produced by fatness, that is, by the abundance of their good things of the earth. Such is the explanation of Menochius. “<l>Transierunt in affectum cordis.</s>” According to the Hebrew: <l>Transierunt cogitationes cordis;</s> that is: <l>Omnia contingunt illis supra spem</s>—They all have come to surpass their desires by obtaining more than they wished and hoped for.
8~They have meditated and uttered their wickedness, that is, they have employed their thoughts and their words to put in execution their wicked designs; and they have not been ashamed to publish their iniquity “<l>in excelso</s>” as from a high place, to make it known to the whole world.
9~They have opened their mouth ever against heaven; that is, according to Bellarmine, against God and his saints, and they have not abstained either from employing their tongue on earth against men. Malvenda’s comment is: <l>Quasi dicat: Nec Deo nec hominibus parcunt</s>—As though he would say: They spare neither God nor man.
10~Wherefore my people shall turn and see that for these impious men, notwithstanding their iniquity, these are days full of worldly satisfaction. Such is the explanation of Bellarmine and Lallemant.
11~And the men of my people say: How can it be that God, in whom is the science or knowledge of all that comes to pass on earth, should know this; and it may be added, should permit it?
12~“<l>Abundantes in sæculo.</s>” According to the Hebrew : <l>Pacifici sæculi.</s> Behold these sinners abound in riches in this world, so that they are esteemed as those who enjoy peace on earth.
13~“<l>Sine causa justificavi.</s>” According to the Hebrew: <l>Frustra mundavi.</s> “<l>Inter innocentes.</s>” That is, with the innocent. 
14~“<l>Flagellatus.</s>” Scourged, chastised; that is, afflicted by the wicked.
15~St. Jerome’s translation: <l>Et dixi: Si narravero sic, ecce generationem filiorum tuorum reliqui.</s> The sense of the verse is: But afterwards I said: If I spoke thus, I should do wrong, and I should come to abandon the society of Thy children, that is, to disapprove of the religion of Thy faithful. 
16~I thought to be able to understand this conduct of Thy Providence; but I perceived that my labor was vain. “<l>Labor est ante me.</s>” That is, above my comprehension.
17~“<l>In sanctuarium.</s>” According to Bossuet: <l>In arcanum;</s> or according to Malvenda: <l>In sacratiora adyta.</s> The sense of the verse is: Until, by means of prayer, I enter into the sanctuary, that is, into the secret judgments of God; and then I came to understand the end of sinners, and what will be the miserable end of their happiness here on earth.
18~“<l>Posuisti eis.</s>” Menochius says: <l>Subintellige “Mala” ut habent aliqui textus græci</s>—Here we must supply <l>Mala,</s> as being understood, which some of the Greek texts have. The sense, then, is: Nevertheless, because of the deceits which they employ to exalt themselves, Thou hast prepared punishment for them; Thou hast caused their feet to fail them, and hast cast them down whilst they sought to raise themselves to power here on earth.
20~“<l>Velut somnium surgentium.</s>” St. Jerome translates: <l>Quasi somnium evigilantis.</s> “<l>In civitate tua.</s>” According to Menochius: <l>In superna civitate.</s> That is: O Lord! at the end of all things, these miserable men shall be afflicted, as those are afflicted who, after dreaming that they have come to a great fortune, find themselves on awaking in the same poverty as before; and whereas Thy faithful servants shall be honored, in Thy city of heaven, they on the contrary shall be excluded from it, and the great figure that they have made in the world will be brought to nothing.
21~“<l>Inflammatum est cor meum, et renes mei commutati sunt.</s>” According to the Septuagint: <l>Lætatum est cor meum, et renes mei dilatati sunt;</s> and as Mattei says, the same version is found in St. Ambrose, as also in the ancient psalters. The passage is thus explained: Wherefore my heart was inflamed with joy and my reins were stirred with gladness, when I saw my fears vanish. “<l>Et ego ad nihilum redactus sum, et nescivi.</s>” And at the same time I was brought to naught, that is, I became aware of my own nothingness, of which I was before ignorant.
22~I confess that hitherto I have been like a beast of burden, not knowing the truth of my nothingness; and, therefore, henceforth, I desire to be always united to Thee, who art my only good.
23~Thou hast held my right hand; that is, Thou hast kept me up, so that I might not be lost; Thou hast led me to live according to Thy will, and Thou hast covered me with glory.
25~My flesh and my heart have failed, that is, can no longer resist the attraction of Thy love, which draws me to Thee; Thou art the God of my heart; it is for Thee alone to possess it eternally; Thou alone must be my portion and all my good.
26~Those that withdraw from Thee will in the end perish; for Thou justly sendest to perdition those that love other objects than Thee. It is thus that Menochius, Sa, Mariana, and Tirinus understand the expression: “<l>Qui fornicantur abs te.</s>”
27~My only good is to adhere and entirely unite myself to God, and to place in him all my hopes.
28~And thus I hope, one day, to publish Thy glories in Jerusalem, which is called the daughter of Jerusalem.
