0~The Jewish people, submissive and humbled, weep over their captivity and the destruction of the temple; then, imploring Heaven to favor their religion and their kingdom, the children of Israel called to mind the many prodigies worked by God and the numerous benefits received from his bounty. Bellarmine and other interpreters think that there is question here of the persecution of Antiochus at the time of the Machabees. This psalm may be used for asking God’s help in the persecutions that the Church suffers at the hands of her enemies.
2~“<l>Ab initio.</s>” Menochius understands by this the time when the people of Israel had no other king than God: <l>Quæ nullum habuit regem ante te.</s>
3~“<l>Virgam.</s>” According to St. Augustine, Theodoret, Symmachus, Euthymius, Bellarmine, and Mattei: <l>Sceptrum</s> or <l>Regnum.</s> Explanation: Thou didst redeem the sceptre of Thy inheritance, that is, the kingdom of the Promised Land, by driving out the enemies that occupied it; there is Mount Sion, where Thou hast vouchsafed to dwell for our good.
4~Raise the hands of Thy dread power, to strike down entirely their arrogance; Thou knowest how many evils this hostile people has wrought in the holy place; that is, in the holy city, or in the holy Temple.
5~Those that hated Thee have gloried in their insults committed in the Temple when solemnities were offered to Thy name. “<l>In medio solemnitatis tuæ.</s>” According to Menochius: <l>Dum sacra solemnia peragerentur</s>—Whilst the sacred solemnities were going on.
6~“<l>Posuerunt signa sua, signa.</s>” They have placed their signs, that is, their banners, on the summit of the Temple. “<l>Et non cognoverunt.</s>” According to St. Jerome, Theodoret, Tirinus, etc.: <l>Neque curarunt quantus honor deberetur Templo tuo</s>—And had no thought of how great honor was done to Thy Temple. “<l>Sicut in exitu.</s>” According to Mattei: As a common thoroughfare; or, according to Lallemant: As the vilest place to be found in the whole city.
12~Why holdest Thou Thy hand afar off, and almost wholly idle, in Thy bounteous bosom, without pouring upon us Thy accustomed graces?
13~“<l>In medio terræ.</s>” Mazzocchi says that this is a Hebraism, and that it means the same as <l>In terra.</s>
14~Here the psalmist begins to relate the wonders wrought in behalf of his people: By Thy virtue, or by Thy power, Thou didst make the sea firm and stable, after having divided it for the passage of the Hebrews; and Thou didst lay low, submerged in those waters, the heads of the dragons, that is, the chiefs of the Egyptians; as is explained by Euthymius and other interpreters.
15~Thou didst break the pride of the dragon; that is, of this hostile people who, being sunk, was made by Thee the prey of the Ethiopians, who reaped the spoils. According to Malvenda and Menochius, by the Ethiopians are meant properly the Arabians who inhabit, the shores of the Red Sea, and are called Ethiopians in Scripture.
16~“<l>Dirupisti fontes et torrentes.</s>” According to Bellarmine: <l>Dirupta petra, fecisti scaturire fontes et torrentes</s>—When Thy people passed through the desert, Thou, from a dry rock broken by Moses, didst cause to spring forth fountains and torrents of water. “<l>Siccasti fluvios Ethan.</s>” Thou didst dry up the river Ethan. Bellarmine, Menochius, Lallemant, and Panigarola understand here the river Jordan; but Mattei says that it is in vain to seek what is this river <l>Ethan,</s> and that this word is rather an adjective, which means <si>Rapid.</s> In fact, St. Jerome translates: <l>Flumina fortia</s>—Strong rivers. Bellarmine, Menochius, and Tirinus also give this meaning. Rotigni and Mattei say, however, with Bellarmine: <l>Interpretes cœteri relinquere maluerunt ipsam vocem hebraicam non interpretatam</s>—that is, they prefer to leave the word untranslated.
17~“<l>Tuus est dies, et tua est nox.</s>” That is: Thou hast made both the day and the night.
18~“<l>Æstatem et ver.</s>” By the summer and the spring is meant the whole year; because anciently, say the learned, the year was divided only in two parts; and in fact, according to the Hebrew, instead of “<l>Ver</s>” it is <l>Hyemem</s>—Winter.
19~“<l>Hujus.</s>” Some refer this pronoun to what has gone before as if the psalmist said: O Lord! remember this, namely, these works of Thine. But others more commonly, with Bellarmine, refer it to that which follows, in this sense: Have before Thy eyes what I am about to say to Thee. “<l>Incitavit.</s>” Has provoked or blasphemed.
20~“<l>Ne tradas bestiis animas confitentes tibi.</s>” Abandon not to the power of these wild beasts, as are these our enemies, the lives of those that are faithful to Thee.
21~“<l>Testamentum tuum.</s>” That is, the covenant that Thou hast made with our fathers. “<l>Qui obscurati sunt terræ.</s>” According to Bellarmine: <l>Qui obscurati sunt in terra, viles et barbari homines.</s> “<l>Iniquitatem.</s>” that is, <l>Inique.</s> Hence this interpretation: Consider how these vile men have unjustly possessed themselves of our houses and of all our property. This second part of the verse is very obscure, as Mattei and others remark.
22~Permit not, O Lord! that Thy people, after having been so humiliated, should be brought to confusion: they are poor, are needy; but raised up by Thee, they will know how to praise Thy name and to give Thee thanks.
23~“<l>Causam tuam.</s>” This cause which is not only ours, but in truth Thy own.
24~“<l>Voces.</s>” The blasphemies.
