0~In this psalm a prayer is offered to God to hasten to the help of the good and the punishment of the wicked. Yet it is in some way a dialogue between God and his people who are in slavery. May the just here learn to reanimate their courage, and the wicked to tremble.
2~“<l>Cum accepero tempus.</s>” That is: When the fitting time has come. (Here it is God that speaks). “<l>Justitias judicabo.</s>” <l>Quod justum est, decernam</s>—What is just I will determine. This is the explanation of Tirinus with St. Jerome and Theodoret.
3~“<l>Liquefacta est.</s>” St. Jerome translates: <l>Dissolvetur.</s> Then in the time of my vengeance the earth shall be dissolved, and all its inhabitants with it through the terror that they shall feel; but I will again set up its columns, that is, its foundations, its solidity. This verse is obscure, and different interpretations are given of it.
4~(Some think that God continues to speak; but Lallemant with more probability says that it is the psalmist who speaks here). “<l>Cornu.</s>” According to Bellarmine: <l>Superbiam</s>—Pride.
5~“<l>Cornu vestrum.</s>” According to the Chaldee: <l>Gloriam vestram</s>—Do not take pride in your glory.
6~“<l>Neque ab Oriente.</s>” ... According to Bossuet and Mattei here should be supplied: <l>Veniet vobis auxilium.</s> The sense is: At the time of punishment there shall come to you no help, neither from the East nor from the West. ... Others explain thus: In vain will you hope to fly for refuge in the East. ... But the former explanation is more common, and pleases me better. “<l>Quoniam Deus judex est.</s>” God himself being judge, no one can hinder the execution of his judgments.
7~“<l>Vini meri plenus misto.</s>” Full of pure wine, that is, of justice, and also, at the same time, of mixture, that is, of pity, so as to temper justice with mercy, as says St. Jerome (In Malach, iii.)
8~“<l>Inclinavit.</s>” According to the Hebrew: <l>Effudit, propinavit.</s> From this cup thus tempered the Lord pours in turn one and the other on men, giving them at one time graces, at another punishments. “<l>Verumtamen fax ejus non est exinanita; bibent omnes peccatores terræ.</s>” But let sinners know that the dregs, that is, the bitterest part of this cup, is not entirely emptied; the wicked shall all drink of it. Bellarmine remarks that for sinners the greater part of their pains, besides those of this life, is reserved for them on the Day of Judgment.
10~I will ever strive to repress and break down the pride of sinners; and will, on the other hand, publish the glory of the just, who shall be exalted.
