0~This psalm is a canticle of praise and thanksgiving which the Jews address to God for having aided them to be victorious over their enemies. Some Fathers believe that it was composed after the victory gained over the Assyrians and the defeat of the army of Sennacherib (4 Kings 19:35), the title of it being according to the Vulgate: <l>Canticum ad Assyrios.</s> But Grotius and Xavier Mattei think that David composed it after his victory over the Ammonites (2 Kings 10), and that afterward Ezechias recited it after the defeat of the Assyrians. It may be used by Christians to thank God for having delivered them from their enemies.
2~“<l>In pace.</s>” According to the Hebrew: <l>In Salem.</s> The word <l>Salem</s> signifies <si>Peace;</s> but here it denotes the city of Jerusalem. Lallemant with others has, therefore, well translated the verse: He has chosen his dwelling-place in Jerusalem, and his habitation on the mountain of Sion.
3~He has broken: “the powers of the bows,” that is, the bows of the hostile powers, and the shields, and the swords, and all the forces of their enemies who were making war.
4~“<l>A montibus æternis.</s>” Nearly all the modern interpreters read according to the Hebrew: <l>A montibus prædæ</s> or <l>rapinæ;</s> and this agrees with the translation of St. Jerome: <l>A montibus captivitatis.</s> Whence it is thus explained: Thou, O Lord! hast caused a marvellous light to shine forth from the mountains of plunder, that is, where our army seized on the spoils of the enemy. “<l>Turbati sunt omnes insipientes corde.</s>” St. Jerome’s translation is: <l>Spoliati sunt superbi corde.</s> The proud remained conquered and despoiled of everything.
5~These men, so proud of their power and of their riches, stricken by the sleep of death, have no longer found anything in their hands. This is the translation of Lallemant; but according to this sense I should prefer to render the verse thus: To the rich of the earth, at the hour of death, all the riches that they have possessed will seem like a dream, since then they will find nothing any more in their hands. Others, however, following the Hebrew text, which instead of “<l>Divitiarum</s>” has <l>Fortitudinis,</s> explain the passage in a sense quite different, thus: They slept and on awaking they found no strength in their hands, that is, they saw that their strength was gone. Bossuet, quoting the translation of St. Jerome, in which we read the word <l>Exercitus</s> for <l>Fortitudinis</s> or <l>Divitiarum,</s> gives still another interpretation: <l>Parte exercitus cæsa, et somnum mortis dormiente, reliqui, conterriti, nec pugnare potuerunt.</s> A part of the army being killed, the rest, seized with terror, were unable to fight anymore. I see no reason for departing from the first sense. The word <l>Fortitudinis,</s> given in the Hebrew, makes nothing against it; for men of the world regard riches as their strength. This fully accords with the Hebrew text.
6~By reason of Thy wrath, or of Thy chastisement, even those were smitten with death that thought themselves the strongest, because they were mounted on horseback.
7~“<l>Ex tunc ira tua.</s>” According to Estius and others: <l>Cum ira tua fuerit commota</s>—When Thy anger is aroused.
8~“<l>Judicium.</s>” The sentence of punishment launched against the enemy: “<l>Terra tremuit, et quievit.</s>” The earth quaked with terror, and then at once there was calm. But according to the Hebrew, instead of “<l>quievit</s>” it is “<l>siluit.</s>” That is: The inhabitants of the earth trembled and kept silence through terror.
9~“<l>Mansuetos.</s>” All those that are meek, that is, his humble servants.
10~This verse is obscure. Lallemant explains it thus: Hence Thy servants who have received mercies from Thee will never think of them without thanking and praising Thee for them; and the memory thereof will cause them to celebrate feasts in Thy honor. But others more commonly, as Maldonatus, Malvenda, Grotius, Mariana, Rotigni, Mattei, etc., supported by the Hebrew text, which instead of the word “<l>Cogitatio</s>” gives <l>Ira,</s> explain it thus: For the fury of hostile man will cause us to praise Thy goodness and power on seeing his defeat; and the remains of the enemy’s fury will serve Thee for a feast, since it will move us to celebrate a festival in Thy honor, in order to praise Thee and return Thee thanks.
12~“<l>Qui aufert spiritum principum.</s>” Who takes away life from princes; or, following this translation from the Hebrew: <l>Qui coercet spiritum principum</s>—Who subdues the pride of princes.
