0~According to a large number of interpreters, we have here the prayer that the captive people at Babylon offered up to God. However this may be, this psalm finds a natural place on the lips of those that are in affliction, who aspire, as St. Augustine says, to leaving the exile of this earth in order to enter the heavenly country.
1~“<l>Intendit mihi.</s>” The literal translation of the Hebrew is: <l>Aures mihi præbuit;</s> or according to St. Jerome: <l>Exaudivit me.</s>
3~The following is the explanation of Lallemant: My soul plunged in sorrow, refused all consolation: I remembered God, and this memory filled me with joy; but the thought of my evils made me fall again into despondency. Other interpreters, as Malvenda, Maldonatus, Rotigni, and Mattei, follow the Hebrew text, which instead of the word “<l>Delectatus</s>” gives <l>Conturbatus.</s> St. Jerome understands it in the same sense; we read in his commentary: <l>Memor fui Dei, et conturbabar. Qui olim, quamvis afflictus, audito Dei nomine, respirabam, nunc, minis ejus territus, divini nominis recordatione conturbor.</s> I remembered God, and was troubled. I who formerly, however much afflicted when I heard the name of God, would again breathe freely (or revive), now, terrified by his threats, am troubled at the recollection of the divine name. And so, following this interpretation of St. Jerome, which seems to be the one most received, the passage is explained thus: I remembered God, and instead of being consoled by his remembrance, I was thereby still more troubled. “<l>Exercitatus sum.</s>” St. Jerome translates thus: <l>Loquebar in memetipso.</s> The sense then of this latter part of the verse is: And speaking, complaining, in myself, I remained anxious and restless through sadness, so that my spirit fainted within me.
4~My eyes looked forward to the dawn, that is, I passed the whole night without being able to sleep because of the trouble that I suffered, and without saying a word.
5~“<l>Annos æternos.</s>” St. Jerome translates: <l>Annos sæculorum</s>—I thought of the ancient days, and I had in my mind the ages of the past. David recalled to his memory, in order to comfort himself, the graces and the favors that he had formerly received from God, and the benefits conferred upon his people.
6~“<l>Et meditatus sum.</s>” According to the Hebrew: <l>Recordabar cantici mei;</s> or, following the translation of St. Jerome: <l>Psalmorum meorum.</s> At night I meditated in my heart the time when I sang canticles; and thus I exercised myself, and searched out my spirit, that is, I examined my conscience. “<l>Scopebam.</s>” St. Augustine in his day read: <l>Perscrutabar</s>—I searched through.
7~“<l>Non apponet ut complacitior sit adhuc?</s>” Will he not show himself more appeased and propitious? Such is the sense that St. Jerome gives according to the Hebrew: <l>Non repropitiabitur ultra?</s> And thus also Bellarmine, Bossuet, etc., understand it.
10~“<l>Hæc mutatio.</s>” Some understand this change in respect to God, following the translation of St. Jerome, who renders the verse thus: <l>Et dixi: Imbecillitas mea est hæc: commutatio dexteræ Excelsi.</s> That is: I said that my weakness, or my wickedness, is the cause of the change of the right hand of the Most High, who from being clement has changed so as to become severe. But others, as Lallemant, with St. Augustine, understand the change to be wrought in the psalmist who speaks: “<l>Et dixi: Nunc cœpi ...</s>”; which is explained thus: I said that now I begin to breathe again by means of hope; or, according to others, I have now determined to change my life, and this change is the work of the right hand of the Most High, that is, of divine grace, <l>dispellentis,</s> writes St. Augustine, <l>priorem nebulam et caliginem:</s> of grace, which delivering me from the cloud of darkness in which I was before, draws me to himself with a new light. St. Antony, the abbot, enjoined, upon his disciples to repeat every morning, when renewing the good intention of giving themselves entirely to God, these words: <l>Et dixi: Nunc cœpi.</s>
11~“<l>Quia.</s>” According to the Hebrew: <l>Certe, quin etiam.</s> And assuredly, I shall continue to remember the wonderful things which Thou, O my God, hast wrought since the beginning of the world.
12~“<l>In adinventionibus tuis exercebor.</s>” St. Jerome translates: <l>Adinventiones tuas loquar.</s> And Bossuet explains the passage thus: <l>Sapientiæ tuæ arcana, et ad salutem nostram excogitata consilia</s>—I shall exercise myself in praising the loving inventions of Thy wisdom with a view to our salvation.
13~“<l>In sancto via tua.</s>” Bossuet: <l>Viæ tuæ sanctæ.</s> That is, following the explanation of Bossuet: Thy designs and Thy works are always in holiness.
14~“<l>Redemisti.</s>” Thou hast redeemed or delivered Thy people from the hands of their enemies.
15~The waters saw Thee, O God Almighty! they were stricken with terror, and out of reverence and awe they drew back to their abysses, that is, to their lowest depths. Bellarmine explains this of the waters of the Red Sea, which at the command of God divided to give a passage for the Hebrews.
16~Then there was heard a great sound, that is, the great roaring of the waves of the sea, when they rushed on the Egyptians to overwhelm them; the clouds also gave forth their voice, raining with fury on the enemies.
17~Lallemant translates: Thy lightnings flashed on all sides, and Thy thunderbolts broke up the wheels of the enemy’s chariots. But other interpreters render the sense better thus: The hailstones struck like arrows, and the voice of Thy thunder, that is, the thunder made a noise like that of a wheel creaking by reason of its rapid motion. “<l>In rota.</s>” Bossuet says: <l>Instar rotæ rapide discurrentis.</s> Thus also is it explained by Maldonatus and Mariana.
19~“<l>Vestigia tua non cognoscentur.</s>” St. Jerome translates: <l>Vestigia tua non sunt agnita.</s> Thy traces, that is, those of Thy people who passed over dry shod, were not known by the enemy, who remained submerged.
