0~This psalm recalls briefly all that the Lord has done for his people from the time of Moses till the days of David. The psalmist, while exalting the munificence of God, expresses his detestation of the ingratitude of the Hebrews.
1~“<l>Legem meam.</s>” My precepts, or my teaching.
2~“<l>In parabolis.</s>” The learned Mazzochi (Spicil. Bibl. in Num. xxiii. 7) says, that in Scripture the word <l>Parabola</s> is used for every kind of poetical composition; whence it is explained: I will open my mouth to sing in verse. “<l>Loquar propositiones ab initio.</s>” St. Jerome translates: <l>Loquar ænigmata antiqua</s>—I will speak ancient enigmas. This agrees with the Gospel of St. Matthew (13:35), in which we read: <l>Eructabo abscondita a constitutione mundi</s>—I will utter things hidden from the foundation of the world: I will declare unto you the mysteries of ancient deeds, come to pass since the beginning of the world.
3~“<l>Quanta audivimus.</s>” St. Jerome translates: <l>Qua audivimus.</s>
6~“<l>Suscitavit.</s>” St. Jerome translates: <l>Statuit</s>—He established. “<l>In Jacob, ... In Israel.</s>” Among the posterity of Jacob.
7~“<l>Quanta.</s>” According to the Hebrew: <l>Quæ</s>—Which.
10~“<l>Prava et exasperans.</s>” According to the Hebrew: <l>Amara et rebellis;</s> or, following the translation of St. Jerome: <l>Declinans et provocans</s>—Inconstant and irritating.
11~“<l>Non est creditus cum Deo.</s>” St. Jerome has: <l>Non credidit Deo</s>—Believe not God.
12~“<l>Filii Ephrem.</s>” The tribe of Ephraim.
15~“<l>Taneos.</s>” Tanis, the capital city of Lower Egypt (Menochius).
16~“<l>Quasi in utre.</s>” According to the Hebrew: <l>Quasi cumulum;</s> or, according to St. Jerome: <l>Quasi acervum</s>—Piled up high in a heap.
17~“<l>Diei, ... In illuminatione.</s>” St. Jerome translates: <l>Pre diem ... In lumine.</s> The Lord went before them to show the way by day in a pillar of cloud, and by night in a pillar of fire (Exod. 13:21).
18~“<l>Adaquavit.</s>” According to the Hebrew: <l>Potum dedit.</s> “<l>Velut in abysso multa.</s>” Menochius explains: <l>Ac si essent ad ripam profundissimi fluminis</s>—As though they were on the bank of a deep river.
20~“<l>Apposuerunt adhuc peccare.</s>” According to the Hebrew: <l>Iterum peccaverunt;</s> or, according to the translation of St. Jerome: <l>Addiderunt ultra peccare.</s> “<l>In inaquosa.</s>” According to the Chaldee: <l>In arido deserto.</s>
21~In the psalm of the <l>invitatorium,</s> verse 4, is explained what we read here. The Hebrews in asking of God for bread and flesh, in the midst of the desert (Exod. 16:3; Num. 11:4), wished to tempt him in order to see by this experiment whether he were really able to provide them with such food in a place deprived of everything.
22~“<l>Parare mensam.</s>” Prepare for us a table such as we desire.
25~“<l>Distulit.</s>” Mattei interprets: <l>Distulit implere</s>—He delayed to fulfil his promises; but it appears to me better to say: He suspended the course of his benefits to those ungrateful men. “<l>Jacob ... Israel.</s>” The posterity of Jacob.
27~“<l>Januas cæli aperuit.</s>” This is said to show the abundance of manna that came down from heaven.
28~“<l>Manna.</s>” Bellarmine says that this name comes from the wonder excited in the people when they saw the earth covered with this extraordinary food, spread over the ground like hoar-frost, and said to one another: <l>Man Hu?</s> which signifies: <l>Quid est hoc</s>—What is this? (Exod. 16:15). The same author adds that manna was the seed of the coriander. “<l>Panem cæli.</s>” The manna was thus called, because it came from heaven or from the atmosphere.
29~“<l>Panem angelorum.</s>” It was thus called, because it was formed by the operation of the angels.
30~According to the interpretation of Lallemant, the Lord caused the Auster or east wind to cease, and made the Africus or south wind blow in its place. But Bellarmine remarks that the east wind, Auster (or Eurus), denoted in the Hebrew text is not opposed to the Africus, but is rather next to it and united with it. Hence Theodoret, Euthymius, and others, do not give to the word <l>Transtulit</s> the sense of <l>Cessare fecit</s>—Made to cease; but that of <l>Flare jussit</s>—Commanded to blow; as if it were said, following the explanation of St. Augustine: <l>Transtulit de cælesti thesauro, et emisit in terram</s>—So that God ordained that these two winds together should bring the quails in the desert.
34~“<l>Ascendit.</s>” The same expression as in verse 25. When the fire of anger is great, its flame rises on high.
35~“<l>Pingues eorum.</s>” Bellarmine understands by this: The most voluptuous; Lallemant: The strongest. “<l>Electos Israel impedivit.</s>” This means, according to Lallemant, that he struck with death the choice or the pick of their youth; and, according to Bellarmine, that the strongest among them were by God prevented from escaping death.
36~“<l>Non crediderunt in mirabilibus ejus.</s>” Such wonders could not induce them to fear the Lord and trust in him.
37~They consumed uselessly their days in the desert; and their years were shortened.
40~They promised to love him; but this promise was only in their mouth, on their tongue, and they thus lied to God.
42~“<l>Non disperdet eos.</s>” God, who is always compassionate towards others, notwithstanding their sins, would not utterly destroy all his people as they deserved.
44~God remembers, that is, he considers that these sinners are men of flesh, weak, and filled with misery, whose life is as a passing wind that lasts but a short time, which comes and goes but does not return. Thus the young man passes on to old age, but does not return to youth.
47~“<l>De manu tribulantis.</s>” From the hand of their enemy, Pharao, who oppressed them.
48~“<l>Taneos.</s>” (See verse 15.)
49~“<l>In sanguinem.</s>” Into the color of blood. “<l>Flumina.</s>” Bellarmine says that by these rivers are to be understood the different branches of the Nile which run through Egypt. “<l>Imbres.</s>” This properly is not rain, of which there is hardly any in that country, but every kind of water, especially the overflowing of the Nile (Exod. 7:20).
50~“<l>Cœnomyiam</s>” (Exod. 8:24). It is a question whether this should be written <l>Cœnomyia,</s> the common fly, or <l>Cynomyia,</s> the dog-fly. The Vulgate has the first, but the Greek more commonly prefers the second; St. Jerome varies.
51~“<l>Ærugini.</s>” To the rust. Caterpillars and locusts, according to St. Jerome’s explanation, devour the herbs like rust or mildew (Exod. 10:13).
52~“<l>Moros.</s>” St. Jerome translates: <l>Sycomoros;</s> and St. Gregory makes this remark: <l>Sycomorus, quippe ficus fatua dicitur.</s> The word <si>Sycamore,</s> etymologically, meaning a foolish fig (Mor. l. 27, c. 27). “<l>In pruina.</s>” Mattei says that the Hebrew word signifies here great hail-stones.
53~“<l>Igni.</s>” By this fire, Mattei understands with probability, frost; which also burns the fields. He does this to avoid introducing another plague of Egypt, that of fire, of which Moses makes no mention.
56~“<l>Primitias omnis laboris eorum.</s>” Men labor hard to bring up their first-born, and for this reason they are called the first-fruits of their labors. “<l>In tabernaculum Cham.</s>” It was the descendants of Cham, son of Noe, who peopled Egypt after the deluge.
57~It is thus, says the psalmist, that God delivered his people from the slavery of Egypt.
58~He led the Israelites full of confidence and without fear, because their enemies were now sunk in the Red Sea; and thus their slavery was at an end.
59~“<l>In montem sanctificationis suæ.</s>” This, as Bellarmine explains, signifies the Promised Land; a mountain, that is, a mountainous land, which God had chosen for himself to be there honored by his people; a mountain, or land, which he had acquired by his own right hand; having wrought so many miracles to help the Israelites in conquering and driving out the idolaters who inhabited it.
60~“<l>Gentes.</s>” The hostile nations, or the Chanaanites, who inhabited the land. “<l>In funicula distributionis.</s>” The lands were measured with cords, according to the custom of those times, to be then distributed by lots to the families of the Israelites.
66~“<l>Silo.</s>” A town of the tribe of Ephraim, where abode for some time the Ark of the Covenant, which God caused to be made in the desert, and where the Lord in some sense dwelt amongst men; since it was thence he gave to them his answers.
67~“<l>Virtutem eorum et pulchritudinem eorum.</s>” The strength and the glory of the people of Israel was the holy Ark, as Menochius, Lallemant, and Bossuet, with St. Augustine, explain: God permitted that it should become the spoil of the enemy, namely, of the Philistines (1 Kings 4:11).
68~He suffered, moreover, that his people should be encompassed on all sides by the swords of their enemies; and thus he had to despise that people whom he had chosen as his heritage; that is, to be to him a peculiar and special people.
69~“<l>Ignis.</s>” The fire of war, or rather of the divine wrath “<l>Lamentatæ;</s>” Some explain this word in an active sense; but Bellarmine, Lallemant, and Mattei think with more reason that it should be taken in the passive sense; thus the meaning is: After the death of the young men, the young maidens whom they were to marry had no one to lament their sad lot; because in the general massacre every one had to bewail the losses in his own family, rather than those of others; and this explanation agrees well with the Hebrew text, which St. Jerome renders thus: <l>Virgines ejus (populi) nemo luxit</s>—No one mourned the virgins of the people.
70~“<l>Sacerdotes eorum.</s>” Ophni and Phinees, the sons of Heli (1 Kings 4:11). “<l>Non plorabantur.</s>” St. Jerome translates: <l>Non sunt fletæ.</s> None consoled nor even pitied them, because all were occupied with weeping the death of their own relatives.
71~But at last the Lord awoke, as wakes up a strong warrior who, heavy with wine, has fallen into a deep sleep. This is the interpretation given by Bellarmine, Menochius, Gordona, and Lallemant; they say that God when he does not punish the wicked seems to sleep a deep sleep. But Mattei justly remarks that the parallel of a drunken man waking up from sleep is ill becoming to God; and he adds that the verse contains not one but two similes; the first is that of the awaking “<l>Excitatus est tamquam dormiens;</s>” the second is that of the return that God makes against his enemies, like a mighty warrior, strengthened and whetted for fight by the wine that he has taken: <l>Tamquam potens miles exhilaratus a vino;</s> this agrees with the Hebrew text, which is rendered by <l>Ovans</s> or <l>Exhilaratus</s>—Cheered or Refreshed, instead of “<l>Crapulatus.</s>”
72~“<l>Inimicos suos.</s>” The Philistines. “<l>In posteriora.</s>” That is: <l>In secretiori parte natium</s> (1 Kings 5:6). God punished their pride by sores so disgraceful, that they were a perpetual cause of shame to them.
73~“<l>Tabernaculum Joseph.</s>” That is, the Tabernacle containing the Ark of the Covenant, which was at Silo, a city of the tribe of Ephraim, son of Joseph.
74~“<l>Elegit tribum Juda, montem Sion, quem dilexit.</s>” He chose the tribe of Juda, to establish his Tabernacle, Mount Sion, preferring it to all other places in Juda.
75~And on this Mount Sion, that is, at Jerusalem, a land that he established to last forever, he built his sanctuary, firm and strong as the horn of the unicorn. Bellarmine says that Jerusalem, which was afterwards destroyed, is here a figure of the Church, which is to endure till the end of the world. Mattei adds that Mount Sion was compared to the unicorn because upon it was the Temple, which was the only temple of Judea.
77~God took David from the humble condition of a shepherd, to place in his hand the royal sceptre and the government of his people, composed of the children of his servant Jacob.
78~David governed this people with a right heart, and directed them with counsel and prudence in all the works that he did for their good.
