0~This psalm shows us the miserable state of the Jewish people during the persecution of Antiochus Epiphanes, in the time of the Machabees. This at least is to be inferred from the first book of the Machabees (7:17), in which the author cites the second verse of our psalm as a prophecy realized in his presence. But, according to St. Augustine, reference is here made to the persecutions that the Church suffered under the pagan emperors.
1~“<l>In hereditatem tuam.</s>” Against Thy people, that is, Thy inheritance. “<l>In pomorum custodiam.</s>” St. Jerome translates: <l>In acervos lapidum</s>—They have made of it heaps of stone. In the first book of the Machabees, we read as follows: <l>Accepit spolia civitatis, et succendit eam igni, et destruxit domos ejus, et muros ejus in circuitu ... Et Jerusalem non habitabatur, sed erat sicut desertum</s>—He took the spoils of the city and burnt it with fire, and threw down the houses thereof round about ... And Jerusalem was not inhabited, but was like a desert (1 Mach. 1:33; 3:45).
4~“<l>Qui in circuitu nostro sunt.</s>” Namely, the Moabites, the Edomites, the Ammonites, and other Gentiles.
5~“<l>In finem.</s>” According to the Hebrew and Chaldee: <l>In perpetuum.</s> “<l>Zelus.</s>” Tirinus explains this to be: <l>Indignatio</s>—Indignation. “<l>Velut ignis.</s>” Like fire which is not extinguished till it has reduced everything to ashes, says Bellarmine: <l>Qui crescere solet in immensum, et in cinerem omnia reiligere.</s>
7~“<l>Jacob.</s>” The children of Jacob, that is. Thy people. “<l>Locum ejus.</s>” Their country; or, according to the Hebrew, their Temple.
8~“<l>Anticipent nos misericordiæ tuæ.</s>” That is: Prevent by Thy mercy the ruin with which our enemies threaten us.
9~“<l>Propter gloriam nominis tui ... propter nomen tuum.</s>” Not for our merits, but for the glory of Thy name. “<l>Libera nos.</s>” Deliver us from the miseries in which we are. “<l>Propitius esto peccatis nostris.</s>” Pardon us our sins which have drawn this persecution upon us.
10,11~“<l>Innotescat ... Ultio sanguinis servorum tuorum.</s>” Let Thy justice be manifest to all, by avenging the blood of Thy servants.
12~“<l>Posside filios.</s>” Possess, that is, preserve the children who have escaped from slaughter.
13~“<l>Vicinis nostris.</s>” To those enemies who are our neighbors. Some think that these are Edomites and Philistines; some others, as Bellarmine, those that brought ruin upon Jerusalem under Antiochus, king of Syria. “<l>Septuplum.</s>” Sevenfold, or many times as much, or simply the double, expressing a complete retribution. “<l>In sinu eorum.</s>” In the centre of their hearts.
