0~We find in this psalm, according as we take it in the literal or the mystical sense, the prayer which the Jews who were prisoners addressed to God for their deliverance, or which the patriarchs offered up, that the Messias might put an end to the tyranny of the devil.
1~“<l>Qui regis Israel.</s>” According to the Hebrew: <l>O Pastor Israel!</s> or, according to St. Jerome: <l>Qui pascis Israel:</s> O God, who as a shepherd rulest and feedest the people of Israel. “<l>Intende.</s>” St. Jerome translates: <l>Ausculta:</s> Hear, Thou who guidest as Thy flock the posterity of Joseph. “<l>Ovem.</s>” The Hebrew word, though singular, denotes a multitude, as Menochius remarks. “<l>Joseph.</s>” Menochius and Tirinus give the reasons why under the name of Joseph are comprised all the Israelites, descendants of Joseph and of his brethren (See Psalm 76:14).
2~“<l>Qui sedes super Cherubim.</s>” That is: Thou to whom the first angels in heaven serve as a throne. “<l>Manifestare.</s>” According to the Hebrew: <l>Splende, Inclarescere</s>—Make Thy power brilliantly shine forth. “<l>Coram Ephrem, Benjamin, et Manasse.</s>” By these three tribes are meant the whole people of Israel, according to the explanation of Bellarmine and others.
3~“<l>Excita potentiam tuam.</s>” Awake Thy power; for, as Bellarmine explains, it seems to be asleep, when Thou permittest our enemies to afflict us in this way. “<l>Ut salvos facias nos.</s>” By delivering us from this captivity.
4~“<l>Converte nos.</s>” According to the Hebrew: <l>Reduc nos</s>—Make us recover our liberty. “<l>Ostende faciem tuam.</s>” Look upon us with a benign countenance. This verse is thus well rendered by Mattei: “<si>Signor, da questi carceri, Deh per pieta richiamaci; Un sol tuo sguardo bastaci, E sarem salvi e liberi.</s>”—Ah! from these prisons forth, O Lord, In pity lead us, home restored; Enough, one gracious look from Thee, To save and set us captives free.
5~“<l>Servi tui.</s>” That is: Of Thy people; as Bossuet and others explain with St. Jerome.
6~“<l>In mensura.</s>” Bellarmine says that some misunderstand this phrase, as though it meant: With moderation; for the Hebrew word here means something great and multiplied, that is, in very full measure.
8~Repetition of verse 4.
9~Thou hast brought Thy vine, that is, Thy people, out of Egypt into the land of promise, after having driven therefrom the Gentiles; and there Thou hast planted it, that is to say, the Synagogue, which was the figure of the Christian Church.
10~“<l>Dux itineris fuisti in conspectu ejus.</s>” Lallemant translates thus: Thou didst convey (wert conductor of) this vine in the journey, without ever losing sight of it. But others more commonly continue the allegory, following the sense of the Hebrew text, namely: <l>Præparasti locum coram ea;</s> or, according to St. Jerome: <l>Præparasti ante faciem ejus.</s> Hence they translate: Thou hast prepared this land for this vine. <l>Plantasti radices,</s> etc. And Thou hast caused it to take such good root, that it has filled all this land.
11~“<l>Arbusta.</s>” St. Jerome translates: <l>Rami.</s> “<l>Cedros Dei.</s>” That is, according to Bellarmine and Lallemant: <l>Cedros altissimas</s>—The most lofty cedars, as were those of Lebanon.
12~“<l>Mare.</s>” The Mediterranean. “<l>Flumen</s>” The Euphrates. Such is the interpretation of Bellarmine, Lallemant, and others.
14~“<l>Aper de silva.</s>” Euthymius, Bellarmine, Malvenda, Mattei, and others understand by the wild boar Nabuchodonozor; and, allegorically, according to St. Jerome, it is the devil. “<l>Singularis ferus.</s>” Bellarmine, Mattei, and others say that according to the Hebrew phrase these words designate the same wild boar; it is the ordinary repetition.
15~“<l>Vide, et visita vineam.</s>” Consider our miseries, and visit with Thy compassion this vine thus brought to ruin.
16~“<l>Super Filium hominis.</s>” According to the Chaldee version: <l>Propter Regem Christum.</s> We beg Thee for the love of the Son of man; that is, the Messias, whom Thou hast confirmed; that is, hast established, as Thy Son. It is thus that St. Jerome, St. Augustine, Theodoret, Euthymius, Bellarmine, etc., explain this verse.
17~“<l>Ab increpatione vultus tui peribunt.</s>” Some, as Estius, Sa, and Bossuet, explain this passage thus: But those that have thus laid it waste shall perish through the wrath of Thy angry countenance. Others, more commonly, as Malvenda, Menochius, Rotigni, Tirinus, and Mattei, with Vatablus, Genebrard, Maldonatus, and Mariana, apply it to the Jewish people in this sense: If Thy countenance continues to appear threatening, and to show forth Thy wrath, all those that belong to the Synagogue will perish.
18~Cause Thy power to be known upon the Man of Thy right hand; and upon the Son of man whom Thou hast willed for Thy glory to send into the world to restore Thy vineyard.
19~“<l>Discedimus.</s>” St. Jerome translates: <l>Recedemus.</s> “<l>Vivificabis nos.</s>” Thou wilt give us the strength to serve Thee.
20~Repetition of verses 4 and 8.
