0~The psalmist reproves the people for the negligence with which they celebrate the praises of the Lord, and urges them to celebrate them with devotion and in thanksgiving for the benefits received from the Lord; for this end the feasts are instituted. Every Christian can apply this psalm to himself.
3~“<l>Neomenia.</s>” We should here remark, that the Hebrews celebrated every month the Feast of the New Moon; but the most solemn Feast of the New Moon was in September, when the trumpets were sounded, and hence it was called the Feast of Trumpets: <l>Dies clangoris est et tubarum</s> (Num. 29:1). “<l>Vestræ.</s>” According to the Hebrew: <l>Nostræ</s>—Our.
4~In the Book of Numbers (10:10).
5~“<l>In Joseph.</s>” That is: On the posterity of Joseph and his brethren; that is, on the people of Israel. “<l>Linguam quam non noverat.</s>” A language which he did not know, because this was the first time that God spoke to his people.
6~According to the Hebrew: <l>Liberavi ab onere dorsum ejus, et manus ejus a cophinis cessaverunt.</s> The prophet recalls to mind the burdens, the baskets full of mud and bricks, that the Israelites were condemned to carry.
7~Here it is God that speaks. “<l>Exaudivi te in abscondito tempestatis.</s>” This passage is variously interpreted. Mattei understands it as referring to the chastisements that God poured upon the enemies of his people; but I prefer the view of Genebrardus, who explains it thus: I heard thee in the tempest of afflictions which thou didst suffer at the hands of the Egyptians, when it seemed to thee that I hid myself away, and did not hear thy prayer. (This applies well to souls in a state of desolation, to whom it appears as if God does not hear them any more, whilst the Lord in the midst of this storm secretly, that is, without letting them know it, listens to them and helps them.) “<l>Probavi te apud aquam contradictionis.</s>” And yet I tried them and found them to be unfaithful near the water of Meriba. The Hebrew word <l>Meriba,</s> meaning contradiction or strife, and so translated in the Vulgate, is the name of the place where the people, suffering from the want of water, contradicted Moses and first refused to obey him. Thus says Mattei and others.
8~“<l>Contestabor te.</s>” Bellarmine explains: <l>Testatum faciam tibi quid a te requiram.</s> “<l>Si audieris me.</s>” If thou wilt obey me. “<l>Neque adorabis deum alienum.</s>” St. Jerome translates: <l>Et non adores deum peregrinum.</s>
9~“<l>Dominus Deus tuus.</s>” Thy only Lord and God. “<l>Dilata os tuum.</s>” That is: Enlarge thy desires, and ask of me what thou wilt. “<l>Implebo illud.</s>” I will satisfy thee fully.
10~“<l>Non intendit.</s>” According to the Hebrew: <l>Non acquievit,</s> or according to St. Jerome: <l>Non credidit,</s> that is, would not rest satisfied with believing my word.
11~“<l>Secundum desideria cordis eorum.</s>” That is, according to their disordered appetites. “<l>Ibunt in adinventionibus suis.</s>” St. Jerome translates: <l>Ambulabunt in consiliis suis</s>—They will walk to their ruin through following their evil designs.
14~“<l>Mentiti sunt ei.</s>” They have failed in keeping their word to him.
15~“<l>Ex adipe frumenti.</s>” With the flower of the flow of wheat. “<l>De petra melle.</s>” With honey gathered from the rocks; that is, in abundance, since the bees had even made their honey in the midst of rocks.
