0~This psalm shows us with what ardor the psalmist, desolate in finding himself far from the Temple of Jerusalem, sighed after the moment of seeing it again. And as the Temple was the figure of heaven, one must believe that he sighed at the same time after the happiness of going to contemplate God in the heavenly kingdom. Nothing is more fitted than this psalm to excite in us the desire of leaving the earth, and of entering the abode of the blessed.
1~“<l>Atria Domini.</s>” See verse 10.
2~That is: My soul and my body leap for joy in thinking of Thee, O living God! Our God is called the living God, in contrast with the gods of the Gentiles, who are dead gods.
3,4~For the sparrow finds its dwelling in some house, and the turtle a nest in which it places its young in safety; and cannot I retire near Thy altars, that is, in Thy Temple, which would be my happy asylum and my happy nest.—This is thus understood by Bellarmine, Maldonatus, and Lallemant. Mattei translates: <l>Altaria tua</s>—Thy altar was my nest, my haven.
6~This is the sense that St. Augustine gives to this verse: Happy the man that hopes to receive from Thee the help that he needs, having resolved in his heart to rise more and more to higher degrees of perfection, as long as he is in this valley of tears,—a place where God has placed him to gain merit. But Mattei with Bossuet interprets this in a very different manner. He says that the psalmist, sighing to return from Babylon to Jerusalem, imagines that he is already free, and exclaims: Happy he that hopes for and obtains Thy help; he already returns, he passes by the valley of Bocha, and is there refreshed by the water that Thou causest to rain down. The same author gives afterwards some explanations: 1. “<l>Ascensiones.</s>” This word, according to the Hebrew, expresses the return to Jerusalem, and it is this that the prophet represents to himself in spirit: “<l>In corde suo.</s>” 2. “<l>Disposuit.</s>” A verb that is found joined to the following words: “<l>In valle lacrymarum,</s>” which are expressed in Hebrew by the name of <l>Bocha,</s> which was an arid valley, called the Place of Tears: <l>Locus flentium, sive Lacrymarum</s> (Jud. 2:5. In the Hebrew we read: <l>Bochim</s>). 3. “<l>In loco quem posuit.</s>” Here the Hebrew word instead of <l>Locus</s>—Place, signifies <l>Fons,</s> a Fountain; so that we translate: <l>Fons ibi ponetur</s>—There shall be set a fountain of water.
7~Mattei, following the sense which he gives to the preceding verse, renders this verse as follows: <l>Etenim propitia dabitur pluvia; hinc ibit de cœtu in cœtum, donee videbit Deum deorum in Sion</s>—For a kindly rain shall be granted; and thence he shall go from company to company, till he comes to see the great God in Sion. Thus the psalmist imagining himself refreshed in the valley of Bocha with the water of a most salutary rain, and that he is marching in the midst of the companies of Israelites who are going to Jerusalem, rejoices as if he were already in the Temple and saw the God of gods. But others, following the sense that they at first adopted, give this explanation: For God, who has given the law, which is the road to arrive at life eternal, will give them his blessing; and so they will walk from virtue to virtue till they see the God of gods in the heavenly Sion. What is certain is that these two verses, 6 and 7, are obscure; and interpreters have made them still more so.
9~O God, who art our protector! regard us with a gracious eye, and especially look upon our king, who is the figure of the Saviour whom Thou art to send us. “<l>Christi.</s>” According to Bossuet: <l>Regis, qui est Christi figura</s>—The king who is a figure of Christ. But it may well be understood as applying principally to the Messias.
10~“<l>In atriis tuis.</s>” These words designate the Temple, says Mariana: <l>Sic Templum vocat, in quo varia atria erant</s>—He thus speaks of the Temple, in which there were various courts. Tirinus observes that the Temple allegorically signifies the Church, and anagogically, that is, in a higher spiritual sense, heaven.
11~“<l>In domo Dei mei.</s>” By this house of God Bellarmine with St. Augustine understands heaven; but Bossuet, Mattei, etc., understand the Temple, according to the Hebrew, and is thus translated: <l>Mallem esse custos liminis domus tuæ</s>—I would rather be a doorkeeper of the Temple; that is, amongst its most lowly servants, according to what we read of the most humble offices of the Levites (1 Parall. 9:19, <l>et seq.</s>). “<l>In tabernaculis.</s>” This expression here denotes the great houses, palaces.
12~That is: God is merciful and faithful to his promises; hence he wishes to grant us grace in this life, and glory in the next.
13~“<l>Bonis.</s>” Grace and glory are real good things. “<l>Qui ambulant in innocentia.</s>” Those that live, keeping away from sin.
