0~The psalmist goes to show us, on the one hand, the Jewish people delivered from slavery; on the other hand, mankind redeemed from the slavery of Satan. He enumerates, moreover, the fruits of the Redemption. The Church recites this psalm in the office of Christmas, and we ourselves may recite it to obtain that the fruits of the Redemption may be applied to us.
1~“<l>Benedixisti, Domine, terram tuam.</s>” St. Jerome translates: <l>Placatus es, Domine, terræ tuæ</s>—At last, O Lord, Thou hast been appeased in respect to Thy land, and Thou hast blessed it. “<l>Jacob.</s>” Of Jacob, or his children.
2~“<l>Operuisti omnia peccata eorum.</s>” Thou hast covered all their sins; or, as is very well explained by Bellarmine, Thou hast hidden them from Thy face, in order not to see them, nor to punish them. When God covers sins, he effaces them and remits them as if they had never existed. See what has been said in Psalm 31:1.
3~“<l>Avertisti ab ira indignationis tuæ.</s>” St. Jerome translates: <l>Conversus es ab ira furoris tui</s>—Thou hast put off Thy wrath, as Bellarmine explains it; Thou hast turned away from Thy anger and Thy indignation: <l>Avertisti te ab ira et indignatione tua.</s>
4~“<l>Deus salutaris noster.</s>” St. Jerome translates: <l>Deus, Jesus noster.</s>
6~“<l>Deus, tu conversus.</s>” St. Jerome translates: <l>Nonne tu convertens ...?</s> That is: If Thou, O Lord, art appeased, and turnest Thy eyes towards us, Thou wilt give us life, by causing us to rise again from sin to grace; and Thy people will rejoice in Thee, singing Thy praises.
7~“<l>Misericordiam tuam.</s>” The effects of Thy mercy. “<l>Salutare tuum da nobis.</s>” That is, according to Bellarmine and Menochius: Give us salvation by sending us the Saviour, or the expected Messias.
8~“<l>Loquetur pacem in plebem suam.</s>” He will speak of peace for his people, that is, of the reconciliation that Jesus Christ their Redeemer will obtain for them, who is called by Isaias: <l>Princeps pacis</s> (Is. 9:6).
9~He will make me understand that he wishes to save the just, and even the sinners, who entering into themselves will be converted, seriously and with all their heart; according to Bellarmine and Bossuet: <l>Qui serio resipiscunt.</s>
10~“<l>Verumtamen.</s>” According to the Hebrew: <l>Certe, Utique</s>—Surely, of a truth; as Malvenda, Menochius, Sa, Tirinus, and Lallemant observe. “<l>Salutare ipsius.</s>” The salvation that God will give them with the coming of the Messias. “<l>Gloria.</s>” That is: Jesus Christ; <l>Splendor gloriæ</s> (Heb. 1:3). Thus Maldonatus and Malvenda.
11~Mercy and truth, or justice, will meet at the coming of the Messias, so that then justice satisfied and peace bestowed shall embrace each other. St. Jerome and St. Augustine understand by <si>Mercy,</s> the coming of the Saviour for the Gentiles, to whom he was not promised; and by <si>Truth,</s> the faithfulness of the Messias with respect to the Jews, to whom he was promised. We have used the future <si>will meet</s> and <si>will embrace,</s> because in this psalm the coming of the Messias is predicted, as Bellarmine remarks, and the poetical language of the Orientals often expresses the future in the past tense, to denote the certainty of the prophecy.
12~“<l>Veritas de terra orta est.</s>” That is, according to Lallemant: Innocence will again spring up on earth. Others explain it thus: The inhabitants of the earth will embrace the truth, or the true faith. But the interpretation that seems to me better is that of Bellarmine and of Menochius, namely: Truth shall spring from the earth, that is, from the virginal womb of Mary; so also St. Augustine understands it of the Eternal Word, who is the Truth itself, clothing himself with human flesh in the womb of the Blessed Virgin.
13~God in his goodness will send his Son to become man; and our earth, the Blessed Virgin will give us her fruit, Jesus Christ, who was called the fruit of Mary’s womb (Luke 1:42); thus was accomplished the prophecy of Isaias: <l>Aperiatur terra, et germinet Salvatorem</s>—Let the earth be opened, and bud forth a Saviour (Is. 45:8).
14~That is: All his actions and all his steps during his life shall be conformed to rectitude and justice, in order that men by following him may arrive at the country of the Blessed.
