0~We have in this psalm one of those fervent prayers that the royal prophet addressed to God in the midst of his tribulations. For, according to the common opinion, David is the author of this psalm. Moreover, he initiates us into the sentiments that filled the soul of Jesus Christ during his Passion, and he prophesies the conversion of the Gentiles. Afflicted souls may use it during their trials to implore the help of God.
2~“<l>Custodit animam meam.</s>” Preserve my life. “<l>Sanctus sum.</s>” St. Jerome translates: <l>Sanctus ego.</s> According to the Syriac version and the Psalter of Milan: <l>Sanctus es;</s> but commonly the interpreters read: <l>Sanctus sum;</s> and Mattei says that we should not depart from the Hebrew. Hence this explanation: I am Thy faithful servant, devoted to Thy service.
3~“<l>Ad te clamavi.</s>” I have cried to Thee by asking Thee for mercy. “<l>Ad te ... animam meam levavi.</s>” Dom Calmet explains: I have desired Thy help with ardor. But Mattei’s translation is better: I have raised my heart to Thee.
4~“<l>Mitis.</s>” St. Jerome translates: <l>Propitiabilis</s>—Ready to be propitiated, to pardon.
5~“<l>Intende voci deprecationis meæ.</s>” Deign to listen to what I ask of Thee.
6~“<l>Exaudisti me.</s>” That is, according to Bellarmine, Menochius, Sa, and Mariana: Thou hast always been willing to hear me.
7~“<l>In diis.</s>” Among all the gods whom men adore.
8~“<l>Venient.</s>” They will come not by leaving the country that they inhabit, but by embracing the faith.
10~“<l>In via tua.</s>” In the way of Thy commandments. “<l>Ingrediar in veritate tua.</s>” Make me to enter it and walk in it with a firm step. Mattei says that according to the Hebrew the word <l>Veritas</s> marks the perfection of anything that is done. “<l>Lætetur cor meum.</s>” According to the Chaldee: <l>Uni cor meum;</s> that is, according to Mattei: <l>Collige cor meum;</s> this agrees with St. Jerome’s translation: <l>Unicum fac cor meum.</s> Unite, gather together to Thyself all the affections of my heart; make my heart to be only for Thee, so that it may fear nothing else than to give Thee displeasure.
12~“<l>Ex inferno inferiori.</s>” That is, according to some: From great dangers which were for me a deep grave. But it is better to understand it, with Gordona, of the depth of hell where are the damned; or the abyss of sin, which according to St. Jerome is a kind of hell.
13~“<l>Synagoga potentiun quæsierunt animam meam.</s>” My powerful enemies have assembled in numbers to seek for me and to take away my life. “<l>Non proposuerunt te in conspectu suo.</s>” They have not set before their eyes that Thou protectest the just and punishest the guilty. This is thus understood by Bellarmine and Lallemant, with St. Augustine.
14~“<l>Verax.</s>” That is: Faithful to Thy promises.
15~“<l>Imperium.</s>” According to the Hebrew Mattei notes: <l>Robur,</s> strength; or following St. Jerome’s translation: <l>Fortitudinem.</s> This passage, as Mariana, Sa, and Rotigni say, may easily apply to Jesus Christ the Son of the Blessed Virgin, who is called herself the servant of the Lord: <l>Ecce ancilla Domini.</s>
