0~The coming Passion of Jesus Christ is the subject of this psalm, according to St. Augustine, who says: <l>Domini hic Passio prophetatur.</s> Here, then, under the figure of a soul overwhelmed with sufferings, insults, tribulations, which prays to God to come to its aid, we see Jesus Christ in the midst of his most bitter sufferings and in his total dereliction addressing himself as man to his heavenly Father to ask his help. This is the explanation given by Bellarmine and many others, with St. Jerome and St. Augustine, who makes this remark: <l>Oravit enim et Dominus non secundum formam Dei, sed secundum formam servi: secundum hanc enim passus est</s>—For the Lord, too, prayed: not according to the form of God, but according to the form of a servant; for according to this, too, he suffered. Every soul in desolation can profitably use this psalm to obtain relief from God.
1~“<l>Deus salutis meæ.</s>” God, from whom I look for my salvation.
3~This verse agrees with what Jesus Christ said in the garden of Olives: <l>Tristis est anima mea usque ad mortem</s>—My soul is sorrowful even unto death (Matt. 26:38). It is thus applied by St. Augustine.
4~“<l>Inter mortuos liber.</s>” Here the word <l>Liber</s> gives rise to different interpretations. St. Augustine applies it to Jesus Christ in two ways: first, in the sense of, Free from sin, in contrast with other men who are subject to death by reason of sin: <l>Inter peccatores solus sine peccato</s>—Though among sinners he himself alone without sin; and then in this sense that he died not through necessity, but only by an act of his free will. This second explanation is adopted by Bellarmine and Bossuet; it appears to me to be more adequate according to the letter in relation to Jesus Christ, typified under the person of David. But, speaking literally of the person of David, Mattei says that the words <l>Inter mortuos liber</s> signify: Separate from the other dead. He cites the example of king Azarias, who, on account of his leprosy, dwelt in a free house: <l>in domo libera</s> (4 Kings 15:5); that is, in a free house—<l>in domo separata</s> (2 Parall. 26:21); and Josephus, the historian, attests that the same king when dead was also buried by himself in a place apart: <l>Seorsum solus sepultus est.</s> Hence Mattei, explaining this passage with regard to the person of David, renders it thus: I am reputed as separate even from the other dead, as though unworthy to remain amongst them.
5~“<l>Vulnerati.</s>” St. Jerome translates: <l>Interfecti</s>—Killed. “<l>De manu tua repulsi.</s>” That is, according to Bellarmine and Tirinus: Deprived of all help from Thee.
6~“<l>Posuerunt.</s>” St. Jerome translates: <l>Posuisti.</s> That is: Thou hast permitted that I should be deposed. “<l>In umbra mortis.</s>” St. Jerome translates: <l>In profundis.</s> According to Bellarmine, the sense is the same: he adds that the words <l>Umbra mortis</s> signify: A shadow so dense as it deprives of all light, like the shadow of death. He says, moreover, with St. Jerome, that this verse, applied to Jesus Christ, may be understood of his descent in Limbo.
7~“<l>Furor.</s>” St. Augustine justly remarks that this word is better rendered by <si>Indignation,</s> because fury (wrath) is ordinarily found in those that have a troubled mind. “<l>Omnes fluctus tuos induxisti super me.</s>” Thou hast heaped upon me all the floods of ills.
8~This was truly accomplished in Jesus Christ when he was abandoned by his disciples: <l>Tune discipuli omnes, relicto eo, fugerunt</s>—Then the disciples, all leaving him, fled (Matt. 26:56). <l>Stabant autem omnes noti ejus a longe</s>—And all his acquaintance ... stood afar off (Luke 23:49).
9~“<l>Traditus sum.</s>” I have been given up to the power of my enemies. “<l>Non egrediebar.</s>” That is, as Bellarmine explains: <l>Non volebam egredi.</s> I did not wish to withdraw myself, my Father having decreed that I should suffer for the salvation of men. “<l>Oculi mei languerunt præ inopia.</s>” That is, according to the same interpreter: My eyes have become faint, as if drained by reason of shedding tears.
10~To ask help according to what the Apostle says: <l>Preces supplicationesque, ad eum qui possit illum salvum facere a morte, cum clamore valido et lacrymis offerens</s>—Who in the days of his flesh with a strong cry and tears offering up prayers and supplications to him that was able to save him from death (Heb. 5:7).
12~“<l>Veritatem tuam.</s>” Thy fidelity to Thy promises. “<l>In perditione.</s>” After having lost his life.
13~Can the admirable prodigies of Thy goodness and justice be known in the darkness of the tomb and in this place of forgetfulness, to render Thee the homage that is due to Thee?
14~“<l>Mane oratio mea præveniet te.</s>” I will not cease to present to Thee my prayers from the break of day.
15~This may be understood of the prayer that Jesus Christ made in the garden of Olives: <l>Transeat a me calix iste</s>—May this chalice pass from me; a prayer that his Father did not hear because our Redeemer wished effectively to die, to save man; for, says Bellarmine, had the Son prayed absolutely, the Father would certainly have heard him.
16~“<l>Exaltatus autem, humiliatus sum et conturbatus.</s>” That is: No sooner have I received some relief than immediately I saw myself humbled and weighed down with afflictions.
17~“<l>Conturbaverunt me.</s>” St. Jerome translates: <l>Oppresserunt me.</s> That is: I am crushed under the blows of Thy justice, on account of the rigor with which all the sins of men have deserved to be punished.
19~“<l>A miseria.</s>” According to the Hebrew: <l>Ab obscuritate, a tenebris.</s> Hence this explanation that Mattei gives with Marco Marino: <l>Tenebris se abdunt, ne videantur a me</s>—They hide themselves, not to be seen by me and obliged to help me in my misery.
