0~St. Jerome divides this psalm into three parts. The first recalls the promise, several times repeated, which God made to David to maintain always royalty in the family. The second teaches us that this promise was not entirely fulfilled in the sons according to the flesh, nor in the temporal kingdom of David. The third shows us the prophet sighing for the coming of the Messias, in whom all was to be fully realized, since he alone was to put an end to the tribulations of his people. This is the reason why the Church recites this psalm in the Office of Christmas.
2~“<l>Veritatem tuam.</s>” According to the Hebrew: <l>Fidem tuam</s>—Thy fidelity to Thy promises.
3~“<l>In æternum misericordia ædificabitur.</s>” That is: Mercy shall be for us an eternal edifice of graces. “<l>Præparabitur.</s>” According to the Chaldee: <l>Stabilietur</s>—Shall be established. “<l>Veritas tua.</s>” That is: Thy fidelity, or the accomplishment of Thy promises.
4~“<l>Disposui testamentum.</s>” St. Jerome translates: <l>Percussi fœdus.</s> “<l>Electis meis.</s>” With my elect; namely, Abraham, Isaac, and the other Patriarchs, as is commonly understood by interpreters. “<l>Præparabo.</s>” St. Jerome translates: <l>Stabiliam.</s> God has promised (2 Kings 7:12) to intrust forever his kingdom to the posterity of David, and this promise was verified in the person of Jesus Christ, as is taught by St. Jerome, St. Augustine, Theodoret, etc. Mattei observes very well that the kingdom of David was perpetuated in Jesus Christ, his descendant, who has continued and will continue eternally to maintain and to govern the spiritual empire of the Church.
5~That is: I will establish for thee a royal throne through all ages. Bellarmine justly remarks that this was properly verified only in our Saviour, of whom David was the figure.
6~“<l>Etenim.</s>” According to the Hebrew: <l>Et, Etiam.</s> “<l>Veritatem tuam.</s>” Thy fidelity to the promises that Thou hast made.
7~“<l>In nubibus.</s>” That is: In the heavens. “<l>In filiis Dei.</s>” According to the Chaldee: Among the angels.
8~“<l>Sanctorum.</s>” That is: Of the angels.
9~“<l>Veritas tua in circuitu tuo.</s>” That is: Thy faithfulness always accompanies Thee. Mattei understands this part of the verse thus: Thou art powerful; and therefore Thou dost promise much, and Thou art faithful to fulfil Thy promises.
10~“<l>Potestati maris.</s>” St. Jerome translates: <l>Superbiæ maris</s>—The pride of the sea.
11~“<l>Vulneratum.</s>” The Hebrew word signifies, according to Menochius: Mortally wounded. “<l>Superbum.</s>” In Hebrew: <l>Rahab.</s> That is: King Pharao, or else Egypt. “<l>Dispersisti.</s>” Thou hast scattered Thine enemies by drowning them in the Red Sea, according to the interpretation of Bellarmine.
12~“<l>Aquilonem et mare.</s>” Bellarmine, Menochius, Lallemant, and Mattei, with Symmachus, hereby understand the North and the South.
13~“<l>Thabor et Hermon.</s>” That is, as Lallemant explains: The East and the West.
14~“<l>Firmetur.</s>” St. Jerome translates: <l>Roboretur.</s> “<l>Præparatio.</s>” According to the Hebrew: <l>Basis;</s> or, according to St. Jerome’s translation: <l>Firmamentum.</s>
15~“<l>Veritas.</s>” Fidelity to Thy promises. “<l>Præcedent faciem tuam.</s>” That is: Are always before Thy eyes. “<l>Beatus populus qui scit jubilationem.</s>” Happy the people that know the joy that is felt in praising Thee ! Thus Bellarmine, Menochius, Tirinus, and Bossuet.
16~That is, according to Bellarmine and Menochius: Those that praise Thee shall walk in the light of Thy grace, in following the way of Thy precepts; they shall exult with joy all the day long in celebrating Thy name; and Thy justice, which will never fail to recompense Thy servants, will elevate them to a higher degree of perfection.
17~Thou art the glory of their virtue, since all their vigor comes from Thy grace, and not from their own works; and it is only by Thy good pleasure that our strength will be raised against the enemy. “<l>In beneplacito tuo exaltabitur.</s>” St. Jerome translates: <l>In voluntate tua elevabis</s>—In Thy will shalt Thou raise up. “<l>Cornu.</s>” According to the Chaldee: <l>Robur</s>—Our strength.
18~“<l>Assumptio.</s>” St. Jerome translates: <l>Protectio.</s>
19~“<l>Sanctis tuis.</s>” To ye holy prophets. According to the Hebrew: <l>Sancto tuo;</s> which may be understood of the prophet Samuel; but Malvenda, Lallemant, and Mattei say that the other prophets may also be very well understood in accordance with the Vulgate. “<l>In potente.</s>” In a mighty man, who is David. “<l>Exaltavi.</s>” I have raised him to the throne.
20~“<l>Unxi eum.</s>” I have anointed him, or I will cause him to be anointed as king of Israel; as was done by the ministry of Samuel (1 Kings 16:13).
24~“<l>Veritas mea.</s>” My fidelity to my promises. “<l>In nomine meo.</s>” That is: By my help. The interpreters say that the expressions of this verse and of the following verses apply better to the person of Jesus Christ.
25~That is: I will give him the dominion of the sea and of the rivers. If one wishes to apply to David this verse, one may understand by the Sea the Persian Gulf, the Arabian Gulf, or the Red Sea, and the whole Erythraean Sea, where the Edomites, the Amalekites, and the Arabs, all tributaries of David, lived; and by the rivers, the Euphrates, the Orontes, and others subject to David, when he took Syria, Mesopotamia, and Damascus. But Maldonatus, Bellarmine, Menochius, and many others apply the verse better to Jesus Christ, of whom David was the figure, and to whom God made subject the seas, the rivers, and the whole earth.
26~Jesus Christ, speaking of God, calls him his Father, as to his divinity, and his God, his Saviour, as to his humanity. Such is the explanation given by Bellarmine and Menochius.
27~Bellarmine and Menochius say that Jesus Christ as God is the only Begotten, and that as man he is the First-born, because he was the Head of the predestined (Eph. 1). Others apply this verse to the person of David. Mattei justly remarks that in the spiritual sense the expressions in the verse are fully verified only in Jesus Christ.
28~St. Augustine also applies this verse to the person of Jesus Christ, saying: <l>Propter ipsum fidele testamentum;</s> which means that God on account of the merits of Jesus Christ kept his promise to save mankind. But others commonly apply it to David in this sense: I will be faithful to him in the promise that I have made him; namely, to give him a Son who shall be Jesus Christ, through whom his reign shall become eternal. This promise was made to David by the prophet Nathan (2 Kings 7:12). Such is the explanation given by Bellarmine and Menochius.
29~This verse corresponds to what we read in the Gospel: <l>Dabit illi Domimis Deus sedem David, patris ejus; et regnabit in domo Jacob in æternum, et regni ejus non erit finis</s>—The Lord shall give unto him the throne of David, his father; and he shall reign in the house of Jacob forever, and of his kingdom there shall be no end (Luke 1:32,33). It also corresponds to the prophecy of Isaias: <l>Super solium David et super regnum ejus sedebit, ut confirmet illud, et corroboret in judicio et justitia, a modo et usque in sempiternum</s>—He shall sit upon the throne of David, and upon his kingdom; to establish it and strengthen it with judgment and with justice, from henceforth and forever (Is. 9:7). Jesus Christ was, in fact, to reign over all Israel and over the whole earth; not, indeed, with a temporal rule, which it was not his will to exercise, but with a spiritual rule, of which the earthly kingdom of David was a figure. Hence the verse may be thus explained: I will preserve his race by giving him the Messias for his son, through Whom I will make his throne to endure as long as the heavens; that is, forever. Gordona here remarks that the temporal reign of David ended under Jechonias; whence, he says, this promise of an eternal kingdom can be understood only of Jesus Christ typified by David.
32~ The Lord threatens the rod and stripes, and not the sword and death, to show that he will come as a father to correct, and not as an executioner to take their life.
33~“<l>Misericordiam autem meam non dispergam ab eo.</s>” That is, the offence that the descendants of David will inflict upon me will not prevent me from keeping my promise of causing the Messias to be born in his family. “<l>Neque nocebo in veritate mea.</s>” According to the Hebrew: <l>Non mentiar in veritate mea</s>—I will not fail in the promise that I have made to him.
35~“<l>Juravi in sancto meo.</s>” Mattei observes that this is a recognized expression in Scripture; thus we read: <l>Juravit Dominus Deus in sancto suo</s>—The Lord God hath sworn by his holiness (Amos 4:2). “<l>Si David mentiar.</s>” The same interpreter says that in the imprecatory oaths the Hebrews left the second part of the imprecation to be understood; so that <l>Si mentiar</s> means the same as <l>Non mentiar;</s> it is as if God said: If I lie, I am no longer God. “<l>Semen ejus in æternum manebit.</s>” His posterity shall never come to an end, since Jesus Christ shall reign for all eternity.
36~“<l>Testis in cælo fidelis.</s>” That is, according to Bellarmine and Menochius: Like the rainbow which appears in heaven as a faithful witness of the peace which God wishes to keep with men (Gen. 9:16). But Lallemant explains it thus: This throne placed in heaven for the Son of David shall be there forever, a faithful witness of the truth of my promises.
37~“<l>Distulisti Christum tuum.</s>” Thou hast deferred sending the Messias whom Thou hast promised. St. Augustine says in regard to this passage: <l>Ergo, Domine, non imples quod promisisti</s>—Art Thou not, Lord, going to fulfil what Thou hast promised? He then adds: <l>Manet omnino, Deus, quod promisisti; nam Christum tuum non abstulisti, sed distulisti</s>—Thou still keepest Thy promise, for Thou hast not cast off Thy Christ, but Thou hast delayed him.
38~“<l>Sanctuarium.</s>” According to the Hebrew: <l>Diadema.</s> The verse is thus explained: It seems as if Thou hast revoked the covenant and the promise Thou hast made to Thy servant David; for Thou hast permitted Thy sanctuary to be profaned on earth, by allowing the crown to pass into the hands of a Gentile king, who has seized upon the throne. This happened when Jechonias and Sedecias, descendants of David, were taken captive. But St. Augustine, Bede, Cassiodorus, and others, apply this text to the destruction of Jerusalem by Titus.
39~“<l>Destruxisti omnes sepes ejus.</s>” Thou hast willed all the walls of the kingdom of David to be ruined, so that it remained as a vineyard without hedges. “<l>Posuisti firmamentum ejus formidinem.</s>” According to the Hebrew: <l>Posuisti in munitionibus ejus formidinem;</s> or, according to the translation of St. Jerome: <l>Posuisti munitiones ejus pavorem.</s> That is: Thou hast set fear in the place of the fortresses of the kingdom. Thus Lallemant explains it: <l>Fecisti ut in locum munitionis succederet formido</s>—Thou hast caused terror to take the place of defence.
41~“<l>Exaltasti dexteram.</s>” Thou hast increased the strength, the power.
42~St. Augustine, applying this passage to the destruction of the Jewish people, and to the ruin of their kingdom for having put to death Jesus Christ, exclaims: <l>Terram perdidit, pro qua Dominum occidit!</s>—It has lost that land for which it killed the Lord!
43~We translate this verse as Father Lallemant does. But St. Augustine explains differently the words “<l>Destruxisti eum ab emundatione;</s>” he says that the Jews not believing in Jesus Christ remained deprived of the grace which would have purified them: <l>Soluti sunt ab emundatione;</s> for faith alone was able to purify their hearts from their sins.
44~“<l>Minorasti dies temporis ejus.</s>” St. Augustine says that the Jews believed that their kingdom would last forever: <l>Putabant se in æternum regnaturos.</s>
45~“<l>Avertis.</s>” According to the Hebrew: <l>Absconderis</s>—Wilt Thou hide Thyself? “<l>In finem?</s>” Is it to be until our ruin is complete? The sense of the verse is: How long, O Lord, wilt Thou refuse to look graciously upon us? Is Thy anger, then, like fire, which is not quenched until it has utterly consumed whatsoever it lays hold of? Thus Lallemant explains the words with Bellarmine.
46~“<l>Memorare quæ mea substantia.</s>” Bellarmine thus translates the Hebrew: <l>Memorare ego quanti temporis sim</s>—Consider how short the time is that remains for me to live. St. Augustine, explaining these words with reference to Jesus Christ, makes David say: Remember, O Lord, what is my substance, that is, that Thy Son is to take flesh from my blood.
48~“<l>In veritate tua.</s>” That is, according to Thy fidelity.
49~“<l>Quod continui in sinu meo.</s>” Mattei explains: <l>Quibus opprobriis plenus est sinus meus</s>—Of which reproach my own heart is full.
50~“<l>Commutationem.</s>” According to the Hebrew: <l>Claudicationem</s>—Limping. That is: Thy enemies, O Lord, upbraid us, and for what? Because Thy Christ, or the Messias, comes limping with too slow a pace. When the Gentiles insulted the Jews, the latter answered them that the Messias would soon come to deliver them from their miseries; but the Gentiles, continuing their reproaches, rejoined: How is this? Is your Messias lame, that he never arrives?
51~That is: But may the Lord be blessed forever, for he cannot fail in his promises; let us, then, humbly pray to him to accomplish with all speed the promise that he has made to send us the Saviour.
