0~According to St. Jerome, it is Moses who in this psalm represents to God the brevity and the miseries of human life, and prays to him to have pity on his people. Other interpreters, however, apply it to the Jews who are captives at Babylon and implore help from God.
1~Thou hast been at all times our refuge, and Thou wilt be so to the end.
2~Thou hast ever been and wilt ever be the God that Thou art.
3~Some explain this verse thus: Do not Thou suffer that men should turn their back upon Thee to give themselves up to worthless creatures; for Thou hast said to them: O men! turn ye unto me, and I will make you feel the effects of my mercy. But others, as Maldonatus, Bossuet, Mattei, etc., follow the Hebrew text, which says: <l>Convertis hominem in pulverem,</s> or, according to St. Jerome: <l>Convertes hominem usque ad contritionem, et dices: Convertimini,</s> or <l>Revertimini, filii Adam;</s> and they explain the verse thus: Thou, O Lord, art eternal; but Thou hast ordained that all men should one day return to the dust out of which they are formed. This explanation is founded on the Hebrew text; but the former, which follows the Vulgate, appears more simple and natural.
4~Even if we were to live a thousand years, what more would these be in Thy sight, that is, compared with Thy eternity, than as yesterday which is already past? Such is the explanation that the learned commonly give, as Malvenda thus attests: <l>Omnes fere.</s>
5~All these thousand years are no more than one of the four watches into which the night is divided, and which are counted as nothing; what then do all the years of men count when compared with eternity?
6~St. Jerome translates: <l>Mane floruit et abiit; ad vesperam conteretur atque siccabitur</s>—The life of man is like a blade of grass that soon passes; in the morning it flourishes and in the evening it falls, withers, and dries up.
7~Such is our lot, because by our sins we have provoked Thy wrath; we have become mortal, and we are afflicted by the horror and the fear of death on account of Thy just anger. So it is explained by Bellarmine and many others.
8~When God wills to punish the sinner, he keeps his eyes fixed on his faults; when, on the contrary, he wills to show him mercy, he turns away his eyes in order not to see them: <l>Avertit faciem.</s> It is for this reason that David says in Psalm 1.: <l>Avertit faciem tuam a peccatis meis</s>—Turn away Thy face from my sins. “<l>In illuminatione vultus tui.</s>” Thou exposest to the light and examinest our most secret faults. These explanations are given by Bellarmine, Lallemant, etc.
9~That is: Our life is shortened, and we succumb under the weight of Thy wrath which we have excited by our sins. This is the sense given by Bellarmine and Menochius.
10~Our life is like the web which the spider wastes its own self to make, and which is destroyed by the least touch. As to the number of our years, they do not generally exceed seventy. “<l>Anni nostri sicut aranea meditabuntur.</s>” The Hebrew according to Bellarmine is: <l>Anni nostri sicut meditatio;</s> and according to St. Jerome: <l>Consumpsimus annos nostros quasi sermonem loquens.</s> But these different renderings signify the same thing, namely, that our life passes away like a thought, a meditation, or like a word that is over the moment that it is uttered.
12~When we shall reach that age, seeing ourselves near death we shall correct the sentiments of pride which we had during our life. This interpretation will agree with the Hebrew text, which is thus rendered: <l>Quoniam tonsio celeriter, et avolabimus.</s>—For quickly is the cutting off, and we have fled away. And with St. Jerome: <l>Transibimus cito, et avolabimus</s>—We have passed away quickly and have fled.
13~Who has ever understood how great, O Lord! is the power of Thy wrath, and who can measure the greatness of Thy indignation, which surpasses all that we can conceive, and all that is commonly believed?
14~Make us know the strength of Thy arm, and cause us to be fully informed of Thy avenging justice; and thus made wise we shall come to Thee. St. Jerome translates it thus: <l>Sic ostende, et veniemus corde sapienti</s>—Thus show to us, and we shall come to Thee with a wise heart.
15~Turn to us with a gracious countenance; how long wilt Thou show Thyself in anger? Suffer Thyself to be moved by the prayers of Thy servants.
16~And thus we shall at once see ourselves filled with Thy mercy; we shall exult with joy and we shall be glad all the days of our life.
18~“<l>In servos tuos et in opera tua.</s>” That is, according to Menochius and Tirinus: Upon Thy servants, who are the work of Thy hands—“<l>Et dirige filios eorum.</s>” Look graciously upon their children, and direct them in the way of salvation.
19~May the grace of our Lord shine upon us: direct in us our actions and all that we do.
