0~David here exhorts the people to praise God for the protection that he has given to the just, and for the chastisements inflicted on sinners in order to correct them.
1~It is just to give glory to God by rendering him thanks for his benefits, and by singing his praises.
2~“<l>Veritatem tuam.</s>” Thy faithfulness to Thy promises.
3~“<l>In decachordo psalterio.</s>” Mariana and Sa understand thereby two different instruments, following in this the Hebrew, which St. Jerome thus translates: “<l>In decachordo et in psalterio.</s>” But Bellarmine thinks that the copulative particle in the Hebrew is redundant; he depends, moreover, on the version of the Septuagint, and on other like expressions that we find in Psalms 32:2, and 143:10.
4~“<l>In factura tua, et in operibus manuum tuarum.</s>” Mattei says with reason that these two expressions are synonymous.
5~“<l>Magnificata.</s>” According to the Chaldee: Magnified, magnificent. “<l>Cogitationes tuæ.</s>” Thy thoughts, or, according to Sa and Mariana, Thy counsels; or with Menochius, the designs of Thy Providence. “<l>Nimis profundæ.</s>” Impenetrable to our weak intelligence.
7,8~“<l>Apparuerint.</s>” According to the Hebrew: <l>Floruerint.</s> Explanation of these two verses: When sinners are born into this world, they are multiplied as the grass which grows up thick apace; and when all the wicked have made a show upon earth, with their dignities and riches, they still perish forever, while Thou, O Lord! shalt ever be the same that Thou art.
10~My strength, or glory, by Thy grace, shall rise on high, as on the head of the unicorn rises its single horn, which is its strength and glory; and my old age shall be consoled by Thy mercy, abounding in gifts and helps.
11~“<l>Despexit.</s>” St. Jerome translates: <l>Respiciet</s>—My eyes shall see my enemies cast down so that, far from fearing them, I shall despise them, and my ears shall hear the chastisement inflicted on those that are risen against me in their malice to plot my ruin.
12~The just shall flourish and shall endure as the palm-tree, which always remains green; they shall grow to a great height, like a cedar of Libanon.
13~Planted in the house of the Lord, and cultivated by him, they shall flourish; that is, they will always preserve their vigor and their beauty.
14~“<l>Uberi.</s>” Abundant in fruits of virtue. “<l>Bene patientes.</s>” According to the Hebrew: <l>Virentes et florentes</s>—Green and flowering; and St. Jerome translates: <l>Frondentes</s>—Leafy. That is: Of a temperament full of strength, they will be well able to bear up against fatigues. “<l>Ut annuntient.</s>” Bellarmine says that this verb should be joined to the following verse.
15~To make known to all the world, by word and example, that the Lord is right and just in all things, and that there is no iniquity or injustice in him because he allows the wicked to prosper; for in his own time, he will reward the just and punish sinners as they deserve.
