0~The subject of this psalm is the Providence of God, attentive to the punishing of the wicked and to the rewarding of the just; although, by a judgment full of wisdom, it often happens that the wicked prosper in this world and the just are afflicted. The first fourteen verses of this psalm show us the just who are afflicted and who lament in seeing the prosperity of the wicked. The psalmist rebukes the just for their little faith, and exhorts them to be patient and to put their trust in God.
1~The Lord is the God of vengeance, that is, he that punishes crimes; he punishes them, and there is no one that can prevent him from doing so. In the Hebrew this verse is in the imperative mood, and St. Jerome thus translates it: <l>Deus ultionum, Domine, Deus ultionum ostendere</s>—O Lord, God of vengeance, show the power That thou hast of punishing the wicked.
2~“<l>Exaltare.</s>” That is: Let Thy all-powerful justice be known. St. Augustine here remarks that the prophet, under the imperative form, is simply predicting. He says: <l>Prophetia est prædicentis, non audacia jubentis</s>—The prophecy of one that predicts, not the presumptuousness of one that commands.
5~“<l>Humiliaverunt.</s>” According to the Hebrew: <l>Attriverunt.</s> That is: They have oppressed and tormented this people who are Thy inheritance.
6~That is: They did not hesitate to put to death all those that they found before them: the widows, the orphans, and even strangers whom they did not know.
7~“<l>Nec intelleget Deus Jacob.</s>” According to St. Augustine: <l>Deus nec advertit ut sciat</s>—God does not pay attention to know these things.
9~“<l>Plantavit.</s>” That is: Has formed. “<l>Considerat.</s>” St. Jerome translates: <l>Videbit</s>—Shall he not see?
10~“<l>Corripit.</s>” St. Jerome and St. Augustine translate: <l>Erudit</s>—Instructs. “<l>Qui docet hominem scientiam.</s>” St. Augustine says: <l>Ipse non scit, qui te fecit scire?</s>—Does he not know who made thee know?
11~“<l>Vanæ.</s>” Vain: or, as Mattei prefers, Evil; he says that in the language of the Bible vanity means sin.
12,13~“<l>Ut mitiges ei.</s>” According to the Hebrew: <l>Ut quietem des illi</s>—That Thou mayest give him rest; or, according to St. Jerome’s translation: <l>Ut quiescat</s>—That he may rest. Hence it is thus explained: Happy he whom thou dost instruct, so as to mitigate his pain in the time of tribulation. “<l>Fovea.</s>” The pit of the grave, that is, death; this signifies that the sinner, though he is not afflicted in this life, yet has to die.
14~“<l>Plebem suam, et hereditatem suam.</s>” His people who are faithful to him, and his inheritance which is the same faithful people. (See verse 7.)
15~Different interpretations are given to this verse; but the following appears to me clear: God does not abandon his faithful servants until justice is resolved into judgment, and according to the same justice, all those that are upright in heart shall be judged. This sense seems to me to be that of St. Jerome’s translation, although it is expressed in different terms, namely: <l>Quoniam ad justitiam revertetur judicium, et sequentur illud omnes recti corde</s>—Because judgment shall return to justice, and all the upright in heart shall follow it (that is, judgment).
16~“<l>Consurget mihi ... Stabit mecum.</s>” St. Jerome repeats: <l>Stabit pro me</s>—Will stand up for me.
17~“<l>In inferno.</s>” St. Augustine understands thereby the real hell of the damned; he thus explains: <l>Prope rueram in illam fossam quæ paratur peccatoribus</s>—I was on the point of falling into the pit which is prepared for sinners.
18~“<l>Motus est pes meus.</s>” That is: I am in danger of falling.
20~That is: Wouldst Thou have a throne like that of unjust judges, Thou who feignest or imaginest that Thy precepts are accomplished only with labor and irksomeness? Estius says that here in the Hebrew the word “<l>Laborem,</s>” signifies Affliction. So also Bellarmine, whose explanation seems to be the best.
