0~We see, according to 1 Paral. 16:7-36, that David composed this psalm when the Ark was transferred from the house of Obededom to the Tabernacle erected on Mount Sion, which is the figure of our holy Church. In this psalm the Jews are exhorted to praise the Lord, and especially are Christians called on to serve Jesus Christ. With St. Jerome, St. Augustine, St. Ambrose, and with the generality of interpreters, Bellarmine says that David in this psalm aimed chiefly at foretelling the coming of the Messias and the establishment of his kingdom.

2~“<l>Salutare ejus.</s>” According to the Hebrew: <l>Salutem ejus;</s> and the Chaldee: <l>Redemptionem ejus.</s> That is: The salvation that he has procured us by Redemption.
5~“<l>Dæmonia.</s>” According to the Hebrew: <l>Dii vani, falsi, nihil</s>—Vain, false gods, nothing.
6~“<l>Confessio et pulchritudo in conspectu ejus.</s>” According to the Hebrew: <l>Gloria et decor coram eo;</s> and Mattei says that in the Bible the word <l>Confessio</s> is taken for the praise that is given to God. “<l>In sanctificatione ejus.</s>” Mattei understands: <l>In ipso Sancto</s>—In him the Holy One by essence. We may also translate these words according to the Hebrew: <l>In sanctuario ejus,</s>—In his Temple, or Tabernacle.
7~“<l>Patriæ gentium.</s>” Estius, according to the Hebrew, says that we should read: <l>Familiæ gentium.</s> So also Menochius, Tirinus, and others, with St. Jerome, who translates: <l>Families populorum.</s>
8~“<l>Hostias.</s>” Bellarmine and Menochius say that the Hebrew word denotes an unbloody offering, and especially one made of flour; this points to the Holy Eucharist. Jansenius of Ghent, Tirinus, Rotigni, Sa, and others, make the same remark.
9~“<l>Commoveatur.</s>” St. Jerome translates: <l>Paveat.</s> “<l>Regnavit.</s>” St. Justin (Dial, cum Tryph.), St. Augustine, and St. Leo read: <l>Regnavit a ligno</s>—Hath reigned from the wood. But the Church no longer uses this version, except in the hymn <l>Vexilla Regis,</s> in which she sings: <l>Regnavit a ligno Deus.</s>
10~“<l>Correxit.</s>” According to the Hebrew and the Chaldee: <l>Firmavit</s>—Has made firm, or established.
11~“<l>Plenitudo ejus.</s>” All that is in the sea, as the islands, the fishes, etc. “<l>Omnia quæ in eis sunt.</s>” All that is found in the fields, as the flocks and herds, the plants, etc.
13~“<l>In æquitate ... In veritate sua.</s>” That is: With an exact judgment as regards the good and the wicked.
