0~David here gives excellent instructions to those that govern, and particularly to princes how they should live well. Also, every father of a family will find in this psalm rules for his conduct.
2~“<l>Psallam.</s>” I will sing Thy praises upon the psaltery. “<l>Intelligam in via immaculata.</s>” According to the Hebrew: <l>In via perfecta.</s> I will apply myself to know and to follow the pure and perfect way. “<l>Quando venies ad me?</s>” But when wilt Thou come to my help?
3~“<l>Perambulabam.</s>” Some explain this and the following verse in the past tense, as they are in the Vulgate and in the Greek; but the Hebrew has them in the future, and thus St. Jerome translates: <l>Ambulabo</s>—I will walk. “<l>Domus meæ.</s>” That is, of those belonging to my house.
4~That is, with the verbs in the future tense: I will never propose to do anything unjust; I will hate, or I hold in abomination, all the transgressors of Thy law.
5~“<l>Non adhæsit mihi cor pravum.</s>” St. Jerome translates: <l>Cor pravum recedet a me.</s> Explanation of this verse: I will never associate with those who have their heart perverse; and if any one of those wicked persons keeps away from me, that is, does not wish to have me for a friend by changing his conduct, I will not know him, that is, I will show that I do not wish to know him.
6~That is: For him who secretly rends the character of his neighbor, I will keep him at a distance, or I will ever persecute him by reproaching him with his vice.
7~I will never sit at table with those who have a proud eye, that is, who look upon others with contempt; nor with the insatiable of heart, that is, with the ambitious and avaricious.
8~My eyes shall be attentive to choose for my companions faithful men who live with me on this earth, and I will not have myself served or aided in my needs except by those that live apart from vice.
9~The proud man shall not live in my house, and he that speaks unjustly, by lies or detraction, shall not remain long before my eyes, that is, I will drive him from my presence. “<l>Non dixerit.</s>” According to the Hebrew: <l>Non firmabitur</s>—shall not be established.
10~I will hasten to exterminate all the wicked from the country, taking care that they are punished; thus I shall banish from the city of the Lord all those that lead bad lives, and who seek to have companions in evil.
