0~According to the interpreters, this psalm presents a brilliant description of the glory of the Saviour as manifested in the works of nature. In it we find a eulogy of the wisdom and of the power that God has, shown forth in creating heaven and earth. The author of the arguments, placed at the head of the psalms in the Compilation of Venice, adds that we learn here how to see nature and the manifold variety of created things.
1~“<l>Vehementer.</s>” St. Jerome translates: <l>Nimis:</s> Beyond all measure, exceedingly. That is: Thou hast made Thy greatness known by Thy works in a wonderful manner.
2~“<l>Confessionem.</s>” According to the Hebrew: <l>Gloriam</s>—Glory.
3~“<l>Pellem.</s>” According to the Hebrew: <l>Tentorium.</s> “<l>Aquis.</s>” Estius understands by this the clouds. According to Mattei, this part of the heavens is really covered with waters.
4~Thou ridest upon a cloud, as upon a chariot which goes whither Thou willest; Thou walkest flying on the winds as if they were birds that had their wings extended.
5~Thou makest the celestial spirits who are always before Thy throne Thy angels; and of these same spirits who burn with the fire of Thy love Thou makest messengers, to execute Thy orders with promptitude and efficacy. Thus St. Augustine interprets this verse; so also St. Gregory (In Evang. hom. 54); and this agrees with the absolute application that St. Paul makes of it to the angels.
6~“<l>Stabilitatem suam.</s>” St. Jerome translates: <l>Bases suas.</s> That is, as Lallemant well explains: Thou hast made it firm by its own weight; so that, as Mattei adds, it supports itself.
7~“<l>Abyssus.</s>” Mattei says that this word in the language of the Bible signifies an accumulation of waters. “<l>Stabunt.</s>” According to the Hebrew: <l>Stabant.</s> The sense of the verse is: There was a time when Thou didst cover the earth with waters in such a manner that these waters were higher than the mountains (Gen. 7:20).
8~Then at the sound of Thy voice, that is, of Thy command, as at the roar of threatening thunder, these waters withdrew, as if seized with terror in the place assigned to them, which was the sea.
9~At this command it seems that the mountains rose up and the plains descended to the place which Thou didst destine for them.
12~“<l>Onagri.</s>” Wild asses, by which may be understood all wild animals.
13~“<l>Super ea.</s>” According to the Chaldee: <l>Juxta eos.</s> Above or beside these fountains or these springs of water. “<l>De medio petrarum.</s>” According to the Hebrew: <l>Inter ramos;</s> or according to St. Jerome’s translation: <l>De medio nemorum</s>—In the midst of the neighboring groves.
14~Thou waterest the mountains with the upper waters, which descend from the clouds; thus the earth by Thy Providence shall be satisfied, and shall abound in fruit.
16~“<l>Vinum lætificet cor hominis.</s>” Here St. John Chrysostom makes this reflection: “Some say: Let there be no wine; but we should rather say: Let there be no drunkenness; for wine is the work of God, but drunkenness the work of the devil” (Ad pop. Ant. Hom. 1).
17~We should here remark, that according to Theodoret, Maldonatus, Menochius, Tirinus, and others, the Orientals used to anoint the face with oil to show a cheerful countenance. The sense then is: Thou producest the olives, the oil of which serves to anoint the countenance to make it look joyous, and grain to make bread wherewith to sustain the life of man.
18~“<l>Saturabuntur.</s>” Shall be sated with these waters of fountains and of rains. “<l>Ligna campi.</s>” Mattei hereby understands wild plants. “<l>Passeres.</s>” The sparrows and the other birds.
19~“<l>Herodii.</s>” It is uncertain what kind of bird this name denotes: according to St. Jerome, it is the kite; but Estius, Lallemant, and others, following the Chaldee, say that it is the stork. “<l>Herodii domus dux est eorum.</s>” According to the Hebrew: <l>Herodii abies est domus ejus.</s> That is: The top of the fir-tree is her house. “<l>Herinaciis.</s>” According to the Greek, <l>Leporibus</s>—For the rabbits. See Mattei.
20~“<l>Fecit lunam in tempore.</s>” The Hebrews used to regulate their calendar by the moon: <l>A luna signum diei festi</s>—From the moon is the sign of the festival day (Ecclus. 63:7). “<l>Sol cognovit occasum suum.</s>” The sun runs its course to its setting; or as Malvenda explains the verse, the sun knows how to go through its course without the variations incident to the moon.
22~The lions come forth roaring with their cubs to seek for prey in the forests; and by their roaring they seem to ask of God their food.
25~“<l>Possessione tua.</s>” According to the Greek: <l>Creatura tua</s>—With Thy creatures. Menochius and Mattei explain thus: The earth is filled with the goods that Thou hast created.
26~“<l>Reptilia.</s>” Properly: Reptiles, animals without legs, that crawl on their bellies. Here the word signifies every kind of fish.
28~“<l>Draco.</s>” St. Jerome writes: <l>Leviathan.</s> Others, as Lallemant, and perhaps all, commonly say that it is the whale; but according to Mattei this is not certain; it is only certain that some sea-monster is signified. “<l>Ad illudendum ei.</s>” According to the Hebrew: <l>Ut luderet in eo.</s> Thus it is understood by Maldonatus, Estius, Sa, Malvenda, Mattei, etc.
30~That is: If Thou withdraw Thy gracious looks, they will languish; Thou wilt take away their life and they will cease to be; they return to the dust whence Thou didst draw them.
31~That is: Thou wilt send forth the breath of life into other animals, to which Thou wilt give being, and thus Thou wilt renew the face of the earth. Du Hamel applies this in a mystical sense to the Holy Ghost, who by his grace renews the face of the earth, that is, of the souls living in this world; and thus the Church uses this verse in her Liturgy at Pentecost.
32~That is: Let then the Lord be glorified forever! and let us act in such a manner that he may rejoice in us, who are his works, and that he may not be saddened by our faults.
33~That is: Let us beware of provoking this powerful Lord, who with a single glance makes the earth tremble, and who by touching the mountains causes them to smoke with his thunder and lightning, as he did on Mount Sinai: <l>Totus autem mons Sinai fumabat</s>—And all Mount Sinai was in a smoke (Exod. 19:18).
