0~The prophet urges the Jews to praise God, and to thank him for all the benefits bestowed on their fathers.
3~“<l>Laudamini in nomine sancto ejus.</s>” That is: Render yourselves worthy of praise by your zeal in procuring glory to his holy name.
4~Be constant in seeking God; try to be in spirit always in his presence.
5~“<l>Judicia oris ejus.</s>” His commandments, or his law.
6~I say this to you who are the posterity of Abraham, and the servants of the Lord; to you, children of Jacob, who are the chosen people of God.
7~“<l>In universa terra judicia ejus.</s>” That is: He governs the whole earth.
8~He has always been mindful of his covenant with his servants, and of the promise that he made them in words that expressed his will, to make all subsequent generations have part therein.
10~“<l>Præceptum.</s>” According to the Hebrew: <l>Statutum, Decretum.</s> “<l>Testamentum æternum.</s>” A covenant or compact that was always to be observed.
11~“<l>Terram Chanaan.</s>” The Land of Promise, where the Chanaanites dwelt. “<l>Funiculum hereditatis vestræ.</s>” This land will be possessed by your children as an inheritance distributed with a line of cord.
12~“<l>Incolæ.</s>” According to the Hebrew: <l>Peregrini, Advenæ.</s>
13~The patriarchs Abraham, Isaac, and Jacob had to pass from one country to another, as from Palestine to Egypt (Gen. 12, 20, 26, 28, 31, 36).
15~“<l>Christos meos ... Prophetis meis.</s>” My anointed ... my prophets; that is, the patriarchs.
16~“<l>Firmamentum panis.</s>” That is: The support of human life, which consists in bread.
17~He ordained that Joseph, who had been sold by his brethren, should be taken before them into Egypt, and thus deliver them from famine (Gen. 37:28).
18~“<l>Ferrum per transiit animam ejus.</s>” According to the Greek: <l>Anima,</s> instead of “<l>Animam.</s>” The Hebrew may be understood either way; but Bellarmine says that in the Vulgate the sense is clearer, and that thus St. Jerome, St. Augustine, and others explain the passage; namely: The pain caused by the iron fetters afflicted the soul of Joseph. “<l>Donec veniret verbum ejus.</s>” That is: Until the accomplishment of his prophecy concerning the release from prison of Pharao’s chief butler, which release was followed by his own (Gen. 40:12, 41:9).
19~The spirit of prophecy with which Joseph felt himself inspired was as a torch which inflamed him; that is, which encouraged him to make this prediction. Then king Pharao, this prince of many peoples, set him at liberty.
20~“<l>Principem omnis possessionis suæ.</s>” Chief of his whole kingdom.
21~“<l>Principes ejus.</s>” The great men of his court, of his possessions. “<l>Senex ejus.</s>” The ancients of his council.
22~“<l>Israel ... Jacob.</s>” Jacob with his family. “<l>Terra Cham.</s>” Egypt. We have already said (see Psalm 77:56) that this country was peopled by the descendants of Cham, son of Noe; it was Mesraim, son of Cham, who first established himself in Egypt.
24~That is: By multiplying the Israelites, God gave occasion to the Egyptians to be exasperated against his faithful people, to seek every means of oppressing his servants (Exod. 1).
25~Then the Lord sent his servant Moses, and Aaron his brother whom he chose to be his fellow-helper. “<l>Ipsum.</s>” Bellarmine observes that the Hebrew may be rendered by <l>Ei;</s> but he says, with St. Augustine, that among the Hebrews the word <l>Ipsum</s> is used simply for elegance, and therefore adds nothing to the sense.
26~“<l>Verba signorum.</s>” A Hebraism, which means: The power to work miracles.
27~In this verse, and in the eight following verses, David describes the miraculous prodigies wrought to punish the Egyptians. “<l>Misit tenebras.</s>” This darkness lasted three days (Exod. 10:22). “<l>Non exacerbavit sermones suos.</s>” Some would omit the particle <l>Non;</s> but according to Bellarmine this correction is admissible; for the Vulgate here agrees with the Hebrew text, of which the rendering is: <l>Non exacerbaverunt sermones ejus.</s> That is: Moses and Aaron did not resist the orders of God, who had commanded them to work those wonders.
38~“<l>Expandit nubem in protectionem eorum.</s>” The Lord spread a cloud above the waters to protect them from the heat of the day. But here we must remark with Bellarmine that this cloud is not the pillar spoken of in Exodus: <l>Dominus autem præcedebat eos, ad ostendendam viam, per diem in columnam nubis</s>—And the Lord went before them to show the way by day in a pillar of cloud (Exod. 13:21). The pillar was to go before them to show them the way, and not to be spread out over their heads; moreover, the cloud spread out above them could not take the shape of a pillar. Hence, adds Bellarmine, we are justified in saying that besides the pillar of cloud which went before the Israelites, and which once we read went behind them to protect them against the Egyptians (Exod. 14:19), there was another cloud spread out over them to shelter them from the heat during their journey. This explanation is supported by the Hebrew text, which St. Jerome thus renders: <l>Expandit nubem in tentorium</s>—He spread out a cloud for a tent or covering; as well as by the following words in the Book of Wisdom: <l>Fuit illis in velamento diei, et in luce stellarum per noctem</s>—She was to them for a covert by day, and for the light of stars by night (Wisd. 10:17).
39~The Israelites asked for means to feed on flesh and bread; the Lord sent among them an abundance of quails, and he satiated them with manna, which he caused to fall from heaven.
40~They were thirsty, and the Lord by the hand of Moses broke a rock, whence ran waters seen flowing as torrents in that arid place (Num. 20:11).
43~“<l>Labores populorum possederunt.</s>” They came into possession of the labors of those nations, that is, of the cities which they had built, and of the fields which they had cultivated.
