0~The psalmist exhorts the Israelites to thank the Lord for all the wonders wrought in their behalf from the time that they left Egypt till the time of the Judges, and reproaches them for their ingratitude to the Lord. A matter of confusion for us Christians, who have received from God far greater benefits.
1~“<l>In sæculum.</s>” St. Jerome translates: “<l>In æternum.</s>”
2~“<l>Loquetur.</s>” According to the Chaldee: <l>Eloqui poterit.</s> That is: Who shall show forth...?
3~“<l>Judicium.</s>” Judgment, equity, or the law of God.
4,5~In the Hebrew, according to St. Jerome and the other interpreters, instead of the plural, “<l>Nostri,</s>” etc., is found the singular, namely: <l>Mei, Me, Videam, Læter.</s> “<l>In beneplacito populi tui.</s>” St. Jerome translates: <l>In repropitiatione populi tui.</s> That is: According to the goodness which Thou hast so often shown towards Thy people. “<l>In salutari tuo.</s>” According to the Hebrew: <l>In salute tua;</s> and according to the Chaldee: <l>In redemptione tua.</s> That is: By sending us salvation, or redemption through Jesus Christ, as St. Augustine explains: <l>Ipse est enim Salvator ...; de illo quippe dixit Simeon senex: Quia viderunt oculi mei salutare tuum</s>—Because my eyes have seen Thy salvation. “<l>Ad videndum in bonitate.</s>” According to the Hebrew: <l>Ut videam bonum;</s> or, according to St. Jerome, <l>bona</s>—In order that I may see the good things prepared for Thy elect. “<l>Ad lætandum in lætitia gentis tuæ.</s>” That is, according to the Hebrew: That I may rejoice in the joy, or that I may have part in the joy, of Thy faithful people. “<l>Ut lauderis cum hereditate tua.</s>” That is: That Thou mayest be forever praised in the midst of this people who are Thy inheritance, or Thy domain, chosen for all eternity.
7~That is: They did not appreciate the wonders wrought by Thee for their deliverance, and too soon they forgot Thy many mercies towards them.
8~“<l>Ascendentes in mare.</s>” According to the Hebrew: <l>Juxta mare.</s> That is: They provoked Thy anger near the Red Sea, where they received so many benefits (Exod. 14).
10~Here the prophet returns to speak of the benefits done them in their progress through the Red Sea. “<l>Increpuit Mare Rubrum.</s>” St. Jerome translates: <l>Comminatus est Mari Rubro.</s> God threatened the Red Sea to make it obey; that is, he bade the Red Sea to dry up, its waters withdrawing on both sides to make a way for the Israelites.
13~They then chanted the Canticle of Moses (Exod. 15).
14~“<l>Fecerunt.</s>” They made a change. “<l>Obliti sunt operum ejus.</s>” They forgot all the wonders that God had wrought in their favor. “<l>Non sustinuerunt consilium ejus.</s>” St. Jerome translates: <l>Non expectaverunt voluntatem ejus</s>—They would not wait for the execution of his will.
15~“<l>In inaquosa.</s>” St. Jerome translates: <l>In solitudine.</s>
16~“<l>Misit saturitatem in animas eorum.</s>” That is: God sent them to satiety the food that they craved.
17~“<l>Irritaverunt.</s>” According to the Hebrew: <l>Inviderunt;</s> and the Chaldee: <l>Invidia commoti sunt.</s> Reference is here made to the envy that Dathan and Abiron, named in the following verse, had conceived against Moses and Aaron on seeing them constituted leaders of the people, envy that led them to address to Moses and Aaron these words: <l>Cur elevamini super populum Domini?</s>—Why lift you up yourselves above the people of the Lord? (Num. 16:3.) “<l>Sanctum Domini.</s>” Aaron, consecrated to God as his priest.
18~The earth swallowed them both up, with all those that had joined their party of revolt (Num. 16:32).
19~“<l>Synagoga eorum.</s>” The multitude of those that murmured the following day (Num. 16:41).
20~The psalmist refers here to another rising of the Israelites, when they worshipped the golden calf (Exod. 32). “<l>In Horeb.</s>” near Mount Horeb, or Sinai.
21~“<l>Gloriam suam.</s>” Some understand these words to mean the glory of the Israelites; but according to the Chaldee we read: <l>Gloriam Domini sui;</s> and Estius says the sense of the verse is: They gave to the image of a calf the glory that is due to God.
23~That is: God then declared that he would destroy his people (Exod. 22:10), and so he would have done if Moses, whom he had chosen to be their leader, had not interposed in his presence as their mediator. “<l>In confractione.</s>” According to the Hebrew: <l>In ruptura,</s> or <l>divisione;</s> and St. Jerome translates: <l>Medius (stetisset medius contra faciem illius).</s>
24~“<l>Terram desiderabilem.</s>” The land that God had promised them, and that was so worthy of their desires.
26,27~“<l>Manum suam.</s>” His hand armed with the sword of justice. Bellarmine here remarks that the first of these chastisements was inflicted in the desert itself, where all the murmurers twenty years old and upwards were condemned to die (Num. 14:29); the second, namely, the dispersion, had its accomplishment later on, at first by means of the king of Babylon, and more fully afterwards by Titus and Vespasian.
28~Here David mentions another sin of the Israelites which they committed when, led away by the daughters of Moab, they began to worship their idol Beelphegor (Num. 25). Don Calmet, in a dissertation at the beginning of the Book of Numbers, shows that Beelphegor is the same as Adonis. “<l>Sacrificia mortuorum.</s>” St. Jerome translates: <l>Victimas mortuorum.</s> That is: Sacrifices offered to dead gods, such as are the gods of the Gentiles; while our true God is a living God.
29~“<l>In adinventionibus suis.</s>” With their perverse inventions, that is, with their superstitions. “<l>Multiplicata est in eis ruina.</s>” According to the Hebrew: <l>Erupit in eos plaga.</s> That is: A great slaughter was made of them on account of this sacrilege; the number of those that perished on this occasion amounted to twenty-four thousand (Num. 25:9).
30~Phinees, grandson of Aaron, burning with zeal for God, slew one of the transgressors of the law, with his accomplice. “<l>Stetit.</s>” He stood firm for the honor of the law. “<l>Placavit.</s>” St. Jerome translates: <l>Dijudicavit</s>—He judged and punished the guilty one. Others, according to the Chaldee: <l>Oravit;</s> or <l>Oratione placavit</s> He interposed by praying for his people, and appeased the anger of God. “<l>Cessavit quassatio.</s>” That is, according to some interpreters: The disorder ceased. But the sense of the Chaldee is: <l>Cessavit mors;</s> and St. Jerome translates in the same sense: <l>Est retenta percussio</s>—The slaughter ceased. This last interpretation is the best; for we read in Numbers: <l>Cessavitque plaga a filiis Israel</s>—And the scourge ceased from the children of Israel (Num. 25:8).
31~This act of Phinees was ascribed to him for merit, as a work of justice and of true zeal. He received in recompense the dignity of high-priest (Num. 25:13), which continued in his family for more than thirteen centuries, according to Mattei, with Mariana, Menochius, etc. “<l>In sempiternum.</s>” That is: He received this reward for as long as the Mosaic law should last; <l>Quamdiu lex duraret,</s> says Emmanuel Sa.
32~The Israelites committed another sin (Num. 20) when, suffering from want of water in the desert, they broke out in unjust murmurings. Moses then, though he had received from God the command to speak to the rock, hesitated somewhat, having conceived a certain feeling of diffidence; however, he struck the rock and water flowed from it in great abundance. God, displeased with Moses on account of his hesitation, punished him by making him die before entering the Promised Land. “<l>Ad aquas contradictionis.</s>” That is: In the place where on account of the want of water there arose a contradiction and a contest against Moses. “<l>Exacerbaverunt spiritum ejus.</s>” They so embittered his soul that he hesitated to execute the order that God had given him to speak to the rock.
33~God with his own mouth rebuked the Hebrews, reproving them for not having exterminated the Gentiles, as he had commanded them.
37~“<l>Fornicati sunt.</s>” In the Bible apostasy from the faith is called Fornication, or treason like to that of unfaithful spouses, who are false to their plighted troth. “<l>In adinventionibus suis.</s>” That is: With their superstitions.
38~“<l>Hereditatem suam.</s>” Those whom he had chosen for his own people.
41~“<l>In consilio suo.</s>” According to the Hebrew: <l>In consilio ipsorum</s>—By the purpose, as Menochius explains, which they formed of serving idols. “<l>Humiliate sunt in iniquitatibus suis.</s>” According to Mattei we are by this not to understand that they were humbled in their wickedness, but that they grew more wicked in their humiliations.
42~However, the Lord, seeing them thus afflicted, had pity on them and lent his ear to their prayers.
43~“<l>Testamenti sui.</s>” That is, of the promises made to their fathers. “<l>Pœnituit eum.</s>” According to the Chaldee: <l>Conversus est ab ira sua.</s> He turned aside from his anger, as though he felt sorrow for having punished them.
44~That is, according to Maldonatus, Mariana, Tirinus, and Mattei: He caused them to meet with compassion from their enemies, who held them captives.
45~“<l>Congrega nos de nationibus.</s>” Gather us together by delivering us from the midst of the Gentiles, where we are scattered.
46~That is: In order that we may come to render Thee thanks in celebrating ...
47~Then we shall sing: Blessed be, etc.
