Interpreters have given various explanations of this psalm. Some apply it to Saul giving vent to his anger against Doeg and those that resemble him. Others to David predicting in form of imprecation the chastisements reserved for Doeg and Achitophel, his enemies. Others, as Xavier Mattel, Mark Marius, and Louis Mingarella suppose that the imprecations are uttered against David and Jesus Christ by their enemies. But commonly the Fathers and the other interpreters regard these imprecations as pronounced against Judas and the other enemies of our Lord. This interpretation, which we follow, agrees especially with that of St. Augustine. 
Hide not my praise, that is, make known my innocence; for the mouth of an impious man and traitor is opened against me. <l>"Super me."</s> St. Jerome translates: <l>Contra me.</s> St. Augustine explains : <l>Odium, quod dolo tegebatur, erupit in vocem</s>—The hatred, treacherously concealed, broke forth in words.

"Detrahebant" St. Jerome translates: <l>Adversabantur</s>—They contradicted me. "Orabam." St. Augustine adds: <l>Pro eis ipsis</s>—At the same time I prayed for these very men.

St. Augustine applies this verse to Judas, and by the sinner he understands Satan himself, which he thus explains: <l>Diabolo subditus sit, qui Christo subditus esse noluit</s>—Let him be subject to the devil, who refused to be subject to Christ. And in fact Judas was possessed by Satan : <l>Post buccellam, introivit in eum Satanas</s>—After the morsel (that is, after Holy Communion) Satan entered in him (John 13:27).
<l>"Cum judicatur"</s> When he shall be judged at the tribunal of God. <l>"Oratio ejus fiat in peccatum"</s> That is, as Lallemant very well explains : If he dares speak in self-defence, may it be ascribed to him as a new crime on account of his temerity.
<l>"Episcopatum ejus"</s> Some understand by this his place of honor or administration ; but it may be justly remarked that by the word Episcopate we must understand the apostolate, as St. Peter interprets it in applying this passage to Judas in the assembly of the apostles, who afterwards addressed this prayer to the Lord : <l>Ostende quem elegeris ex his duobus unum, accipere locum ministerii hujus, et apostolatus, de quo prævaricatus est Judas</s>—Show which of these two Thou hast chosen, to take the place of his ministry and apostleship, from which Judas hath by transgression fallen (Acts 1:20-24).
Here we must remark, that St. John Chrysostom, Theodoret, and Euthymius are of opinion that Judas was never married. Moreover, Genebrardus and Tirinus think that these imprecations against Judas did not all have their effect in his person, but those only that could reach him. On the other hand, St. Augustine teaches that they were verified with regard to the Jewish people, of whom Judas is here the figure: for by the destruction of Jerusalem the Synagogue became a widow, and the Jews, her children, were made orphans.
This happened after the destruction of Jerusalem. <l>"Nutantes transferantur."</s> St. Jerome translates : <l>Justabiles vagentur.</s>
Here Menochius remarks : <l>In excidio Hierosolymitano, adeo Judtæorum divitias scrutabantur milites Romani, ut etiam, corporibus sectis aliquorum, viscera scrutati sint, sperantcs se aurum, quod deglutivissent, inventuros. Testis Josephus</s>—In the destruction of Jerusalem the Roman soldiers made such a close search after the riches and property of the Jews, that they even ripped up the bodies of some and searched their bowels to find gold which they might have swallowed, as Josephus testifies (De Bello Judaico, l. 6, c. 15).

That is, as Lallemant explains : May death carry off his children before they are able to have their father's name pass to a second generation.
