vv. 21-30
<l>"Cor meum conturbatum est intra me."</s> St. Augustine refers this passage to what Jesus Christ said in the garden : <l>Tristis est anima mea usque ad mortem</s>—My soul is sorrowful even unto death (Matt 26:38). 
<l>"Excusans sum sicut locustce"</s> The locust goes lopping from place to place; and thus, says Du Hamel, did it happen to Jesus Christ : <l>Ex uno tribunali in aliud jactatus</s>—Who was cast about from one tribunal to another.
<l>"Propter oleum."</s> St. Jerome translates: <l>Absque oleo</s>—Without oil. We should then understand that ill and infirm condition of body was brought on not by the use of oil, but through being debarred from its use ; for Estius, Sa, Mariana, Malvenda, Tirinus, and Mattel say that unctions with the use of oil were customary among the Hebrews, and that their health suffered if they failed to use them. Hence Mattei asserts that to understand here that flesh was lost by the use of oil is a most evident error. Besides, Bellarmine thus translates and explains the Hebrew literally : <l>Caro mea immutata est a pinguedine ; id est, ex pingui macilenta reddita est.</s> And according to the Chaldee we read : <l>Macilenta est absque pinguedine.</s> The sense, therefore, is : My flesh has been changed from being fat, and is become lean for want of food that produces fatness. Otherwise, I do not see how this verse can with propriety be applied to Jesus Christ. 
<l>"Moverunt capita sua."</s> They shook their heads to insult me. This was verified, as Bellarmine remarks, when the enemies of Jesus Christ blasphemed him as he was on the cross : <l>Prætereuntes autem blasphemabant eum, moventes capita sua</s>—And they that passed by blasphemed him, wagging their heads (Matt 27:39). 

That is, as Menochius explains it : Let them know that all that I have suffered, I have suffered by Thy will, according to the words of Isaias : <l>Propter scelus populi mei percussi eum</s>—For the wickedness of my people have I struck him (Is 53:8).
<l>"Malediccnt illi"</s> They will curse me. And thus St. Paul wrote : <l>Christus nos redemit de maledicto legis, factus pro nobis maledictus</s>—Christ hath redeemed us from the curse of the law, being made a curse for us (Gal 3:13). Du Hamel comments on the last words thus : <l>Nostram ipse suscipiens maledictionem</s>—Taking upon himself our curse. <l>"Confundantur."</s> May they remain confounded, and be converted, as St. Augustine understands it.
<l>"Diploide."</s> With a double cloak, that is, according to St. Augustine, both within and without.
<l>"Nimis...In medio multorum."</s> St. Jerome translates : <l>Vehementer...In medio popitlorum</s>—In the midst of the people.
He has stood at my side in my misery, to defend me and to save my life from the hands of my persecutors. Bellarmine understands this of the resurrection of Jesus Christ, whereby ne resumed the life which the Jews had taken from him.
