0~Interpreters have given various explanations of this psalm. Some apply it to Saul giving vent to his anger against Doeg and those that resemble him. Others to David predicting in form of imprecation the chastisements reserved for Doeg and Achitophel, his enemies. Others, as Xavier Mattei, Mark Marius, and Louis Mingarella suppose that the imprecations are uttered against David and Jesus Christ by their enemies. But commonly the Fathers and the other interpreters regard these imprecations as pronounced against Judas and the other enemies of our Lord. This interpretation, which we follow, agrees especially with that of St. Augustine.
1~Hide not my praise, that is, make known my innocence; for the mouth of an impious man and traitor is opened against me. “<l>Super me.</s>” St. Jerome translates: <l>Contra me.</s> St. Augustine explains : <l>Odium, quod dolo tegebatur, erupit in vocem</s>—The hatred, treacherously concealed, broke forth in words.
3~“<l>Detrahebant.</s>” St. Jerome translates: <l>Adversabantur</s>—They contradicted me. “<l>Orabam.</s>” St. Augustine adds: <l>Pro eis ipsis</s>—At the same time I prayed for these very men.
5~St. Augustine applies this verse to Judas, and by the sinner he understands Satan himself, which he thus explains: <l>Diabolo subditus sit, qui Christo subditus esse noluit</s>—Let him be subject to the devil, who refused to be subject to Christ. And in fact Judas was possessed by Satan : <l>Post buccellam, introivit in eum Satanas</s>—After the morsel (that is, after Holy Communion) Satan entered in him (John 13:27).
6~“<l>Cum judicatur</s>” When he shall be judged at the tribunal of God. “<l>Oratio ejus fiat in peccatum</s>” That is, as Lallemant very well explains : If he dares speak in self-defence, may it be ascribed to him as a new crime on account of his temerity.
7~“<l>Episcopatum ejus.</s>” Some understand by this his place of honor or administration; but it may be justly remarked that by the word Episcopate we must understand the apostolate, as St. Peter interprets it in applying this passage to Judas in the assembly of the apostles, who afterwards addressed this prayer to the Lord: <l>Ostende quem elegeris ex his duobus unum, accipere locum ministerii hujus, et apostolatus, de quo prævaricatus est Judas</s>—Show which of these two Thou hast chosen, to take the place of his ministry and apostleship, from which Judas hath by transgression fallen (Acts 1:20-24).
8~Here we must remark, that St. John Chrysostom, Theodoret, and Euthymius are of opinion that Judas was never married. Moreover, Genebrardus and Tirinus think that these imprecations against Judas did not all have their effect in his person, but those only that could reach him. On the other hand, St. Augustine teaches that they were verified with regard to the Jewish people, of whom Judas is here the figure: for by the destruction of Jerusalem the Synagogue became a widow, and the Jews, her children, were made orphans.
9~This happened after the destruction of Jerusalem. “<l>Nutantes transferantur.</s>” St. Jerome translates: <l>Justabiles vagentur.</s>
10~Here Menochius remarks: <l>In excidio Hierosolymitano, adeo Judæorum divitias scrutabantur milites Romani, ut etiam, corporibus sectis aliquorum, viscera scrutati sint, sperantes se aurum, quod deglutivissent, inventuros. Testis Josephus</s>—In the destruction of Jerusalem the Roman soldiers made such a close search after the riches and property of the Jews, that they even ripped up the bodies of some and searched their bowels to find gold which they might have swallowed, as Josephus testifies (De Bello Judaico, l. 6, c. 15).
12~That is, as Lallemant explains: May death carry off his children before they are able to have their father’s name pass to a second generation.
13~“<l>Iniquitas patrum ejus</s>” The iniquity of the fathers of this same people, to be punished in him, as St. Augustine explains, applying the text of the Gospel: <l>Ut veniat super vos omnis sanguis Justus, qui effusus est super terram, a sanguine Abel...</s> That upon you may come all the just blood that hath been shed upon the earth from the blood of Abel... (Matt 23:33). “<l>Matris ejus.</s>” By this the holy Doctor understands Jerusalem.
14~“<l>Fiant contra Dominum semper.</s>” May the iniquity of their fathers and the sin of their mother, with their own crimes, be always before the eyes of God in punishment. 
15~“<l>Hominem inopem...</s>” Jesus Christ himself, who was thus treated without pity. 
16~“<l>Dilexit maledictionem.</s>” St. Augustine applies this to the time when the Jewish people cried out: <l>Sanguis ejus super nos et super filios nostros</s>—His blood be upon us and upon our children (Matt. 27:25).
17~That is, as St. Augustine explains: May cursing wrap round his body and penetrate within his soul. 
19~“<l>Hoc opus.</s>” St. Jerome translates: <l>Hæc est retributio</s>—This is the punishment.
20~“<l>Propter nomen tuum.</s>” For the glory of Thy name. “<l>Suavis</s>” St. Jerome translates: <l>Bona.</s> Bent on helping the afflicted.
21~“<l>Cor meum conturbatum est intra me.</s>” St. Augustine refers this passage to what Jesus Christ said in the garden: <l>Tristis est anima mea usque ad mortem</s>—My soul is sorrowful even unto death (Matt 26:38).
22~“<l>Excusans sum sicut locustæ</s>” The locust goes lopping from place to place; and thus, says Du Hamel, did it happen to Jesus Christ: <l>Ex uno tribunali in aliud jactatus</s>—Who was cast about from one tribunal to another.
23~“<l>Propter oleum.</s>” St. Jerome translates: <l>Absque oleo</s>—Without oil. We should then understand that ill and infirm condition of body was brought on not by the use of oil, but through being debarred from its use; for Estius, Sa, Mariana, Malvenda, Tirinus, and Mattei say that unctions with the use of oil were customary among the Hebrews, and that their health suffered if they failed to use them. Hence Mattei asserts that to understand here that flesh was lost by the use of oil is a most evident error. Besides, Bellarmine thus translates and explains the Hebrew literally: <l>Caro mea immutata est a pinguedine; id est, ex pingui macilenta reddita est.</s> And according to the Chaldee we read: <l>Macilenta est absque pinguedine.</s> The sense, therefore, is: My flesh has been changed from being fat, and is become lean for want of food that produces fatness. Otherwise, I do not see how this verse can with propriety be applied to Jesus Christ.
24~“<l>Moverunt capita sua.</s>” They shook their heads to insult me. This was verified, as Bellarmine remarks, when the enemies of Jesus Christ blasphemed him as he was on the cross: <l>Prætereuntes autem blasphemabant eum, moventes capita sua</s>—And they that passed by blasphemed him, wagging their heads (Matt 27:39).
26~That is, as Menochius explains it: Let them know that all that I have suffered, I have suffered by Thy will, according to the words of Isaias: <l>Propter scelus populi mei percussi eum</s>—For the wickedness of my people have I struck him (Is. 53:8).
27~“<l>Maledicent illi.</s>” They will curse me. And thus St. Paul wrote: <l>Christus nos redemit de maledicto legis, factus pro nobis maledictus</s>—Christ hath redeemed us from the curse of the law, being made a curse for us (Gal. 3:13). Du Hamel comments on the last words thus: <l>Nostram ipse suscipiens maledictionem</s>—Taking upon himself our curse. “<l>Confundantur.</s>” May they remain confounded, and be converted, as St. Augustine understands it.
28~“<l>Diploide.</s>” With a double cloak, that is, according to St. Augustine, both within and without.
29~“<l>Nimis ... In medio multorum.</s>” St. Jerome translates: <l>Vehementer ... In medio populorum</s>—In the midst of the people.
30~He has stood at my side in my misery, to defend me and to save my life from the hands of my persecutors. Bellarmine understands this of the resurrection of Jesus Christ, whereby he resumed the life which the Jews had taken from him.
