0~David offers here his solemn thanksgiving for the victory that he gained over his enemies, and for all the other benefits that had been conferred upon him; he thanks him specially for having given to the world Jesus Christ, the Redeemer of mankind.
1-4~The prophet begins by inviting all men to praise God for the mercy that he continually exercises towards them. He then calls specially on the Israelites, among whom were all the apostles; he next invites all the priests, who were to propagate the holy faith; and lastly all the faithful.
5~“<l>In latitudine.</s>” By sending me abundant help.
6,7~God is my protector; this is the reason why I shall fear nothing of all the evils that men think to do me; I will despise all the efforts and snares of my enemies.
10-12~“<l>Ultus sum.</s>” I have been revenged. It must be observed that this expression is not to be understood here of vengeance properly speaking, but of a victory gained over the enemy. It applies specially to Jesus Christ triumphing over his enemies, and to all the faithful who by his help overcome their temptations. We may, then, take these three verses together, and explain them thus: My enemies have closed in around me from every side, as an angry swarm of bees, or as a burning flame in a bundle of thorns; but thanks to the protection of the Lord, I have been avenged on them, that is, I have overcome them all.
15~In the tabernacles or tents of the just, no voices were heard but of gladness and victory in thanksgiving to God for having saved me, and caused me to triumph over my enemies.
16~The hand of God in aiding me has shown forth its strength.
17~“<l>Non moriar.</s>” As I shall not die as my enemies had hoped.
18~“<l>Castigans castigavit me.</s>” He has chastised me, but with the tender compassion of a father.
19~The gates of justice are the gates of heaven; for justice is the gate of the kingdom of God; hence we should seek it before all things: <l>Quærite ergo primum regnum Dei, et justitiam ejus</s>—Seek first the kingdom of God and his justice (Matt. 6:33). Since justice is the only gate by which we can come to God, it is only the just that enter through it. Such is the sense given to this passage by St Jerome, St. John Chrysostom, and St. Augustine.
20~Once having entered this gate, as I have desired, I will, O my God! sing Thy praises always, and render Thee thanks for having heard my prayer, and for having become my Saviour.
21~This verse is to be understood only of Jesus Christ and his Church as St. Peter explains it to the Jews: <l>Hic est lapis qui reprobatus est a vobis ædificantibus, qui factus est in caput anguli</s>—This is the stone which was rejected by you the builders: which is become the head of the corner (Acts 4:11). God sent upon earth this most precious Stone, that is, his own beloved Son; but the Jews, who at that time formed the Church, rejected him. This Stone, however, became the head of the corner, joining together the two walls, namely, the Hebrew nation and the Gentile people, into one Church.
23~This is specially a happy day; it is a particular work of God: let it ever be a day of joy and thanksgiving for the immense benefits received.
24~Save me, O Lord! and be ever gracious to me, so that I may never cease to repeat: Blessed be he that is come in the name of the Lord to save us! This precisely was the cry of the multitude when Jesus Christ made his triumphant entry into Jerusalem: <l>Hosanna Filio David! benedictus, qui venit in nomine Domini!</s>—Hosanna to the son of David: Blessed is he that cometh in the name of the Lord (Matt. 21:9).
25,26~We wish and bespeak you a thousand blessings, you who are of the Church of the Lord; for he is the true God, and he has manifested himself to us by taking to him our human flesh. Celebrate, then, this day with solemn pomp by adorning the temple even to the altar with green and leafy boughs.
