0~The prophet shows here that the knowledge and the providence of God extend to all things. He seeks, moreover, to induce us to unite ourselves to the just, whom God enriches with blessings, and to detach ourselves from sinners, whom his justice constrains him to punish.
1~“<l>Tu cognovisti sessionem meam et resurrectionem meam.</s>” Thou hast known perfectly the time when I should sit down and when I should rise up, that is, when I should take repose and when I should work; this taken in a moral sense may mean: the time when I should be humbled and when exalted. Bellarmine says that this verse may well be applied to Jesus Christ, speaking of his death and of his resurrection, as, indeed, the Church does apply it on Easter Sunday in the Introit.
2~“<l>Semitam meam et funiculum meum.</s>” The path that I should follow, and the term at which I should arrive.
3~Thou hast foreseen my ways, that is, my actions, before my tongue has uttered a word to reveal them.
4~Thou hast known all things that concern me, whether old or new; for Thou hast formed me; Thou hast busied Thy hands to create me, and make me Thy servant.
5~“<l>Ex me.</s>” A Hebraism, says Bellarmine, for <l>Super me</s>—Above, beyond me; this is explained by the following words: “<l>Confortatus est, et non potero ad eam.</s>” That is: Thy knowledge is too high for me to comprehend it.
6~“<l>A spiritu tuo.</s>” That is: Away from Thy knowledge. “<l>A facie tua.</s>” Away from Thy gaze.
7-9~That is: Thou art in every place through Thy immensity, and Thou exercisest everywhere Thy power. I shall be unable to free myself.
10~St. Jerome translates this verse thus: <l>Si dixero: Forte tenebræ operient me; nox quoque lux erit circa me.</s> Hence the verse is thus explained: If I should say that perhaps darkness will hide me from Thy eyes, I should deceive myself; for night from Thy eyes is a light that surrounds me, and discovers to Thee all my actions. But we may also, as Bellarmine observes, explain the words of the Vulgate in this manner: If I should hide myself in the darkness of the night in order not to be seen, while indulging in pleasures so shameful as shun the light of day, still I could not for all that withdraw myself from Thy gaze.
12~“<l>Renes meos.</s>” That is: The most inward parts of my body, and consequently my affections and my desires.
13~O Lord! I will praise Thee always, because Thou hast made me know Thy greatness in a fearful manner, that is, Thou who commandest respect and a holy fear in Thy admirable works which my soul knows too well not to be greatly impressed.
14~Of all that Thou hast in secret formed within me, that is, my bowels and bones, nothing is hidden before Thee; so that the whole substance of my body is known to Thee, as also whatever is hidden in the deepest bowels of the earth.
15~Thy eyes have seen my imperfection, that is, my body, when it was shapeless, without distinction of members; for in Thy book, that is, in Thy mind, all men are found written, so that Thou knowest what is to become of them. The meaning is brought out better by what follows: “<l>Dies formabuntur, et nemo in eis.</s>” Menochius explains: Days shall succeed to days, and not one of them shall be missing in Thy book so as to escape Thy knowledge.
16~“<l>Mihi.</s>” To my mind, according to my judgment. Thou honorest and Thou exaltest Thy enemies in calling them to enjoy eternal glory when they shall be made princes of the eternal kingdom.
17~“<l>Ex surrexi.</s>” According to the Hebrew: <l>Evigilavi</s>—Have wakened from sleep. “<l>Adhuc sum tecum.</s>” That is: I am united with Thee up to the present moment, and I hope to continue thus united till the end.
18,19~I know, on the other hand, that Thou wilt destroy the wicked, and I say to them: Men of blood, depart from me; for you say in your thought, that is, among yourselves: In vain, O Lord! will Thy servants occupy the cities that Thou hast given them.
22,23~Prove me, and penetrate all the affections of my heart; interrogate me, that is, examine me and weigh all my ways, all my actions, and if Thou seest that I am in the way of iniquity, do Thou lead me into the eternal way, that is, make me walk by that way which will bring me to the possession of eternal good.
