0~In this psalm, as well as in the two following, (Psalms 149,150) all creatures are called upon to praise and thank the Lord for the victory gained over the enemies of his holy name. In an allegorical sense all Christians are invited to bless God for the victory that he helped them to gain over the devil, the world, and the flesh; a victory so great that for it they will be honored by being appointed judges at the day of judgment.
4~“<l>Aquæ omnes quæ super cælos sunt.</s>” With regard to these waters there are various opinions. Some, as St. Bonaventure, Ambrose and Catharinus, etc., say that they are the crystalline heaven. Others, as St. Athanasius (Cont. Arian. or. 2, n. 28, E.B.), St. Basil (In Hexam. hom. 3), St. Ambrose (Hexam. l. 2, c. 2,3), St. John Chrysostom (In Genes, hom. 4), Bede (In Hexam.), etc., believe that these waters are above the firmament or starry heavens, and they cite for this opinion Genesis: <l>Et fecit Deus firmamentum, divisitque aquas quæ erant sub firmamento, ab his quæ erant super firmamentum</s>—And God made a firmament, and divided the waters that were under the firmament from those that were above the firmament (Gen. 1:7). And St. Augustine, who holds the same view, says: <l>Major est Scripturæ hujus auctoritas, quam omnis humani ingenii capacitas</s>—The authority of this Scripture is greater than all the capacity of the human mind (De Gen. ad litt. l. 2, c. 5, n. 9). This opinion is also followed by many modern interpreters cited by Tirinus. Others, in fine, such as Rupert, Lorinus, Mariana, etc., with the greatest number of modern commentators, understand by these waters the clouds that are suspended over the earth.
6~“<l>Ea.</s>” That is, the angels and the heavenly bodies.
7~“<l>Dracones.</s>” This is the name given by Scripture to sea-monsters. “<l>Abyssi.</s>” Abysses, that is, deep waters.
8~“<l>Spiritus procellarum.</s>” These are violent winds.
10~“<l>Serpentes.</s>” Animals that crawl upon the earth. “<l>Volucres pennatæ.</s>” Birds that fly in the air.
12~“<l>Exaltatum est nomen ejus solius.</s>” God is raised above everything; it is to him alone all glory belongs.
13~Let then the praises of the Lord resound through heaven and earth, since he has willed to exalt by his power his faithful people, in giving them Jesus Christ, who has made his servants victorious over the devils.
14~Let praise be given at the same time to all his saints, and to all the true children of Israel who form the people that by their faith and virtue approach near to God.
