0~The title of this canticle sufficiently explains its contents, thus: <l>Scriptura Ezechiæ, regis Juda, cum ægrotasset, et convaluisset de infirmitate sua</s>—The writing of Ezechias, king of Juda, when he had been sick, and was recovered of his sickness. In the first part Ezechias complains of his sad state, and in the second he thanks God for having restored him to health. This canticle perfectly applies to the Christian who bewails his spiritual infirmities and who then thanks the Lord for the help that he has given to him.
1~I said: In the middle of my life s course I shall enter the tomb.
2~I set myself to consider the rest of the years which I might have lived, and I said: So here on earth I shall not any more have the joy of going to the temple, there to visit and to adore my Lord and my God.
3~I shall see no more the inhabitants of my kingdom, who now live in peace.
4~Behold I remain deprived of all posterity, and my family will be destroyed, as is the wont to destroy a shed of shepherds. Such is the explanation of St. Jerome, St. Thomas, and others.
5~My life is being cut off like a web that is cut off by the weaver; I was still weaving it when the Lord cut it off; thus, my God, from morning till evening, Thou wilt make an end of me, that is, within the space of one day Thou wilt bring my life to a close.
6~I hoped to live until the morning of the second day; but the violence of the disease, like a lion, has broken all my bones, that is, has taken away all my strength.
7~My state is such that I cannot now last to see the evening. Like a little callow swallow that is in the nest, without feathers, suffering from cold and hunger, I cry out and beg for pity; and like a plaintive dove, so do I meditate upon my miseries, and implore for help by my moanings.
9~O Lord! I am oppressed by evil; do Thou answer for me. But what is it that I ask for, or what will the Lord reply to me since it is he himself who has done it, that is, it is he that has reduced me to the state in which I am?
10~This being so, I will go over in thought all my past years, in bitterness of soul for the sins that I have committed.
11~If this be man’s life, that is, a life of sin, and if thus my life has been passed, punish me, and thus preserve my life. Behold, in the time even of my great bitterness I have regained peace.
12~But Thou, O my God! hast delivered me from death; and in order to deliver me therefrom, Thou hast cast all my sins behind Thy back, no more to behold them.
13~He that is dead in the tomb can no longer praise Thee, nor can he hope to see the fulfilment of Thy promises.
14~Only the living sing Thy praises, as I am doing this day; and so fathers shall recount to their children Thy fidelity to the promises which Thou hast made to them.
15~Save me, and so I shall celebrate Thy glories in Thy temple all the days of my life. Bellarmine (Ps. 6:5) thinks, with St. Jerome and other Fathers, that Ezechias speaks here of eternal death and hell, as the preceding verse Eruisti animam, etc., would seem to indicate. The just soul, he adds, after the death of its body, is always alive and continues to praise God; and even without its body, in the tomb, it awaits the truth of God, who has promised to resuscitate it. We may see similar passages in the psalm 5:5; 87:11-13; 113:26, 27.—As we recite this canticle in the Office of the dead, it is then proper to apply it to the souls of the dead in the sense given by the holy Fathers; hence the House of the Lord, v. 15, can only be heaven.
