<?php

	img();
	space('RubricH');
	headSt(1102,1,'in Commem. Omnium Fidelium Defunctorum','the Commem. of all the Faithful Departed');
	
	rubp('<snr>¶</s> Commemoratio omnium Fidelium defunctorum excludit tum festa occurrentia, tum festa transferenda cujusvis ritus. Si tamen inciderit in dominicam, iisdem cum juribus, in seq. feria secunda celebratur, translato, vel penitus omisso, juxta rubricas, quolibet alio festa.','<snr>¶</s> This feast excludes all occuring feasts and also all transferred feasts of any rite. If it should fall on a Sunday, it is celebrated with the same privileges on the following Monday; any other feast being transferred or omitted, according to the rubrics.');
	rubp('Omnia dicuntur ut in communi Officio Defunctorum, circa finem Breviarii <snr>p. '. bkref('offDef') .'</s>, præter ea quæ hic habentur propria.','All as in the Office of the Dead, near the end of the Breviary, <snr>p. '. bkref('offDef') .'</s>, except those parts given here as proper.');
	hour('L');
	rubp('Absolute incipitur ab ant. <snr>Exultábunt Dómino, p. '. bkref('offDefL') .'</s>', 'The hour begins immediately with the ant. <snr>The humbled, p. '. bkref('offDefL') .'</s>');
	rubp('Repetita post canticum <snr>Benedíctus</s> antiphona, dicitur flexis genibus:','After repeating the antiphon at the end of the <snr>Benedíctus</s>, the following is said kneeling:');
	vr('pater_silent_vr.php');
	vrS('a_porta_inferi.php');
	vrS('requiescant_in_pace.php');
	vrS('domine_exaudi_orationem_meam.php');
	vrS('dominus_vobiscum_non.php');
	rubrics('oremus.php');
	prayer('offDef/offDef.php');
	vrS('requiem_aeternam.php');
	vrS('requiescant_in_pace.php');
	rubp('Et ita absolvuntur Laudes, neque aliud adjungitur','And thus Lauds is ended, and nothing else is added.');
	space();

	hour('P');
	rubp('Absolute incipitur a psalmis sequentibus.','The hour begins immediately with the following psalms.');
	psalm(87);
	vrS('requiem_aeternam.php',6);
	psalm(27);
	vrS('requiem_aeternam.php',6);
	psalm(31);
	vrS('requiem_aeternam.php',6);
	space();
	rubp('Expletis psalmis, dicitur flexis genibus:','After the psalms, the following are said kneeling:');
	vr('pater_silent_vr.php');
	vrS('a_porta_inferi.php');
	vrS('requiescant_in_pace.php');
	vrS('domine_exaudi_orationem_meam.php');
	vrS('dominus_vobiscum_non.php');
	rubrics('oremus.php');
	prayer('offDef/prime1.php');

	rubp('Deinde in choro legitur Martyrologium, ut ibi suo loco notatur.','Next, in choir, the Martyrology is read, as noted its own place.');
	rubp('Deinde, etiam extra chorum, licet omissa fuerit lectio Martyrologii, subjungitur:','Next, even out of choir, although the Martyrology may have been omitted, is said:');
	vrS('in_memoria_aeterna_erunt_justi.php');
	rubrics('oremus.php');
	prayer('offDef/prime2.php');
	vrS('requiem_aeternam.php');
	vrS('requiescant_in_pace.php');
	rubp('Et ita absolvuntur Prima, neque aliud adjungitur','And thus Prime is ended, and nothing else is added.');
	space();

	hour('T');
	rubp('Absolute incipitur a psalmis sequentibus.','The hour begins immediately with the following psalms.');
	psalm(37,1);
	reading('vr/requiem_aeternam.php',0);
	psalm(37,2);
	reading('vr/requiem_aeternam.php',0);
	psalm(55);
	reading('vr/requiem_aeternam.php',0);
	space();
	rubp('Expletis psalmis, dicitur flexis genibus:','After the psalms, the following are said kneeling:');
	vr('pater_silent_vr.php');
	vrS('a_porta_inferi.php');
	vrS('requiescant_in_pace.php');
	vrS('domine_exaudi_orationem_meam.php');
	vrS('dominus_vobiscum_non.php');
	rubrics('oremus.php');
	prayer('offDef/offDef.php');
	vrS('requiem_aeternam.php');
	vrS('requiescant_in_pace.php');
	rubp('Et ita absolvuntur Tertia, neque aliud adjungitur','And thus Terce is ended, and nothing else is added.');
	space();

	hour('S');
	rubp('Absolute incipitur a psalmis sequentibus.','The hour begins immediately with the following psalms.');
	psalm(69);
	reading('vr/requiem_aeternam.php',0);
	psalm(84);
	reading('vr/requiem_aeternam.php',0);
	psalm(85);
	reading('vr/requiem_aeternam.php',0);
	space();
	rubp('Expletis psalmis, dicitur flexis genibus:','After the psalms, the following are said kneeling:');
	vr('pater_silent_vr.php');
	vrS('a_porta_inferi.php');
	vrS('requiescant_in_pace.php');
	vrS('domine_exaudi_orationem_meam.php');
	vrS('dominus_vobiscum_non.php');
	rubrics('oremus.php');
	prayer('offDef/offDef.php');
	vrS('requiem_aeternam.php');
	vrS('requiescant_in_pace.php');
	rubp('Et ita absolvuntur Sexta, neque aliud adjungitur','And thus Sext is ended, and nothing else is added.');
	space();

	hour('N');
	rubp('Absolute incipitur a psalmis sequentibus.','The hour begins immediately with the following psalms.');
	psalm(101,1);
	reading('vr/requiem_aeternam.php',0);
	psalm(101,2);
	reading('vr/requiem_aeternam.php',0);
	psalm(101,3);
	reading('vr/requiem_aeternam.php',0);
	space();
	rubp('Expletis psalmis, dicitur flexis genibus:','After the psalms, the following are said kneeling:');
	vr('pater_silent_vr.php');
	vrS('a_porta_inferi.php');
	vrS('requiescant_in_pace.php');
	vrS('domine_exaudi_orationem_meam.php');
	vrS('dominus_vobiscum_non.php');
	rubrics('oremus.php');
	prayer('offDef/offDef.php');
	vrS('requiem_aeternam.php');
	vrS('requiescant_in_pace.php');
	rubp('Et ita absolvuntur Nona, neque aliud adjungitur','And thus None is ended, and nothing else is added.');
	space();

	hour('V');
	rubp('Si concurrat cum dominica vel festo I classis, Officium Commemorationis omnium Fidelium defunctorum cessat post Nonam.', 'If concurrent with a Sunday or a I class feast, the Office commemorating all the Faithful departed ends after None.');
	rubp('Absolute incipitur ab ant. <snr>Placébo, p. '. bkref('offDefV') .'</s>', 'The hour begins immediately with the ant. <snr>I will please, p. '. bkref('offDefV') .'</s>');
	rubp('Repetita post canticum <snr>Magníficat</s> antiphona, dicitur flexis genibus:','After repeating the antiphon at the end of the <snr>Magníficat</s>, the following is said kneeling:');
	rubp('<snr>Pater noster</s> et preces, ut supra ad Nonam.', '<snr>Our Father</s> and prayers, as above at None.');
	rubp('Et ita absolvuntur Vesperæ, neque aliud adjungitur','And thus Vespers is ended, and nothing else is added.');
	space();

	hour('C');
	rubp('Non dicitur <snr>Jube, domne</s>, nec lectio brevis, neque versus <snr>Adjutórium nostrum</s>, neque oratio dominica; sed, facta confessione et absolutione, statim sine antiphona incipitur a psalmis sequentibus.','<snr>Jube, domne</s> is not said, nor the brief lesson, nor the verse <snr>Adjutórium nostrum</s>, nor the Lord’s prayer: but, after the confession and absolution, the following psalms are begun immediately without antiphon.');
	rubp('Ubi vero, juxta rubricas, Completorium dicitur tamquam ultima diei precatio, in qua fit examen conscientiæ, tunc, si recitatur in choro vel in communi, moderator chori vel communitatis, signo dato, indicat esse examen conscientiæ; quo absoluto, dicitur <snr>Confíteor, Misereátur, Indulgéntiam, p. '. bkref('confiteor') .'</s>','When, according to the rubrics, Compline is said as the final prayer of the day and the examination of conscience is made, then, if said in choir or community, the leader of the choir or community gives a sign to indicate the beginning of the examination of conscience; when finished, the <snr>Confíteor, Misereátur, Indulgéntiam</s> are said, <snr>p. '. bkref('confiteor') .'</s>');
	space();
	psalm(122);
	reading('vr/requiem_aeternam.php',0);
	psalm(141);
	reading('vr/requiem_aeternam.php',0);
	psalm(142);
	reading('vr/requiem_aeternam.php',0);
	space();
	rubp('Expletis psalmis, statim subjungitur.','After the psalms, the following is said immediately.');
	canticle('simeon.php');
	reading('vr/requiem_aeternam.php',0);
	space();

	rubp('Deinde dicitur flexis genibus:','Then the following are said kneeling:');
	vr('pater_silent_vr.php');
	vrS('a_porta_inferi.php');
	vrS('requiescant_in_pace.php');
	vrS('domine_exaudi_orationem_meam.php');
	vrS('dominus_vobiscum_non.php');
	rubrics('oremus.php');
	prayer('offDef/compline.php');
	vrS('requiem_aeternam.php');
	vrS('requiescant_in_pace.php');
	rubp('Et ita absolvitur Completorium, nequi aliud adjungitur.','The hour of Compline is thus concluded, and nothing else is added.');
	space();
?>
